### ISSUE TITLE
Cut a version before JuliaCon?

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/PackageCompiler.jl#101]
Hi! Would it be possible to tag and release a version of PackageCompiler before JuliaCon?

Specifically, now that the `static_julia` parts work on julia `v0.7`, it would be really nice to have that be running live 😊.
Sorry I haven't looked at getting the other parts of this package working on `v0.7` yet, though...

Thaaanks for the consideration. I'm sure it's a busy time for everyone, so no pressure either way. :)

**Comment by lucatrv** [comment]
I'm implementing a few last features and corrections that I had in my TODO list, I should finish by this coming weekend, then in my opinion we could tag a new release, maybe 0.4.0?

**Comment by lucatrv** [comment]
Ok, with the last commits I completed my TODO list for now, @SimonDanisch do you agree to tag a new release 0.4.0?

**Comment by SimonDanisch** [comment]
Sure, let's do that :)

**Comment by SimonDanisch** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/16277

**Comment by NHDaly** [comment]
Hooray, thanks! :)
