### ISSUE TITLE
Error building `PackageCompiler`

### ISSUE THREAD

**Issue by hajsf** [JuliaLang/PackageCompiler.jl#109]
I'm trying to  `Pkg.add("PackageCompiler")` but got the below error:

> ┌ Error: Error building `PackageCompiler`: 
> │ ERROR: LoadError: syntax: try without catch or finally

My laptop os MacBook Air, macOS High Sierra, v 10.13.6

![jerr](https://user-images.githubusercontent.com/26045838/44307969-05695f80-a3b5-11e8-862c-3930029a1252.png)

**Comment by ho0ber** [comment]
Same issue on the same version of OSX on my 2018 Macbook Pro.

Also on Windows 10:
![image](https://user-images.githubusercontent.com/431445/44894808-a31b3380-acbf-11e8-90d0-cf0eab2b010e.png)

**Comment by JaapHaitsma** [comment]
Fix is here https://github.com/JuliaLang/PackageCompiler.jl/pull/107

**Comment by lucatrv** [comment]
Julia v1.0 support added with PR #116
