### ISSUE TITLE
fails Pkg.test with Julia v1.0 

### ISSUE THREAD

**Issue by geoff2273** [JuliaLang/PackageCompiler.jl#119]
ERROR: LoadError: UndefVarError: Test not defined
Stacktrace:
 [1] include at .\boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at .\loading.jl:1038
 [3] include(::Module, ::String) at .\sysimg.jl:29
 [4] include(::String) at .\client.jl:388
 [5] top-level scope at none:0
in expression starting at C:\Users\GEvans\.julia\packages\PackageCompiler\5u3Km\test\runtests.jl:2

Need to replace line 2: "using Base.Test" with "using Test"

Now just need to find out why the test are failing...

**Comment by geoff2273** [comment]
Also need to add "using Pkg" to the top of snooping.jl due to line 99: Pkg.dir(package)

This then raises a warning that Pkg isn't in the deps.

Then I get errors about joinpath: ERROR: MethodError: no method matching joinpath(::Nothing, ::String)

I think this package is not yet Julia v1.0 ready! I will check again in a few months.

**Comment by lucatrv** [comment]
Julia 1.0 support is still WIP, see PR #113 and #116

**Comment by lucatrv** [comment]
Julia v1.0 support added with PR #116
