### ISSUE TITLE
Idea: generating the snoopfile using the C driver

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/PackageCompiler.jl#125]
I feel like having to write a Julia snoopfile is a bit redundant.

Currently, you write a driver program in C (or just `examples/program.c` when using `build_executable`), which calls exactly the Julia code you care about. But then you have to write this separate `.jl` file that calls the same code to get the precompile statements. I was wondering if it might be easier to just have the `.csv` be generated incrementally by calling the C driver with all the combinations of input arguments that you care about, and then use the precompile statements in the `.csv` to compile the system image (again).

What do you think?

**Comment by KristofferC** [comment]
Another way to do this is to start julia with `--trace-compile=precompile.jl`, mess around with your package in the REPL and try "record" as much as you can and then use the `precompile.jl` file (which will now include all precompile statements).

**Comment by tkoolen** [comment]
Thanks for the suggestion. I'll experiment with this.

So if you wanted to do this from the C code, I guess you could just set the `trace_compile` option in `jl_options`, similar to

https://github.com/JuliaLang/PackageCompiler.jl/blob/08b80f4d12e7790284ae6e44e9c726af954aea5a/examples/program.c#L28

It looks like `--trace-compile=precompile.jl` overwrites `precompile.jl` instead of appending to it if you run Julia a second time, so you'd need to store a separate precompile file for each tuple of program arguments you care about. Is there any performance penalty for duplicate precompile statements? I.e., would it be beneficial at all to manually prune duplicates, or is it OK to just include all the generated precompile files without further modification?

**Comment by KristofferC** [comment]
Another problem I encountered when testing this in practice is that you also need to import all modules in (or before) the precompile file is included (for example `REPL` will likely be in there).

**Comment by tkoolen** [comment]
Ah, but that should be less of a problem if the Julia process that generates the precompile file is started from the C code, right?

**Comment by KristofferC** [comment]
I think the current workflow is ok. Having to compile the whole thing takes significant time and then you have to recompile with new precompilation statements.
