### ISSUE TITLE
Segfault on Julia 1.0.1 (but not on 1.0.0)?

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/PackageCompiler.jl#134]
If I run `test PackageCompiler` locally in Julia 1.0.1, I get

```julia
Launching new julia process to run commands...

signal (11): Segmentation fault
in expression starting at no file:0
jl_array_ptr_ref at /buildworker/worker/package_linux64/build/src/julia.h:786 [inlined]
jl_has_call_ambiguities at /buildworker/worker/package_linux64/build/src/gf.c:2000
jl_mt_assoc_by_type at /buildworker/worker/package_linux64/build/src/gf.c:1095
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2153
reinit_stdio at ./libuv.jl:120
__init__ at ./sysimg.jl:470
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2184
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1537 [inlined]
jl_module_run_initializer at /buildworker/worker/package_linux64/build/src/toplevel.c:90
_julia_init at /buildworker/worker/package_linux64/build/src/init.c:813
julia_init__threading at /buildworker/worker/package_linux64/build/src/task.c:302
main at /buildworker/worker/package_linux64/build/ui/repl.c:227
__libc_start_main at /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
_start at /opt/julia-1.0.1/bin/julia (unknown line)
Allocations: 2646 (Pool: 2637; Big: 9); GC: 0
```

Tests pass on 1.0.0. Can anybody reproduce this?

**Comment by ianfiske** [comment]
Might be system dependent.  I just run `test PackageCompiler` on OS X with Julia 1.0.1 and didn't segfault.  Looks like you're on Linux.

**Comment by NHDaly** [comment]
Is this related to https://github.com/JuliaLang/PackageCompiler.jl/issues/136?

**Comment by tkoolen** [comment]
I just started with a clean slate (re-downloaded Julia 1.0.1, removed PackageCompiler and did a `pkg> gc`), and I can no longer reproduce the issue. I suspect that maybe PackageCompiler was trying to reuse a 1.0.0 sysimg, but I'm not sure. Anyway, I'll close this issue for now.

**Comment by tkoolen** [comment]
Oh, I did have to comment out `jl_options.compile_enabled = JL_OPTIONS_COMPILE_OFF`; that's maybe because of #136.

**Comment by tkoolen** [comment]
This happened again when I downgraded from 1.0.1 to 1.0.0. This time I solved it by just deleting `PackageCompiler/sysimg`. Would be nice to add a check to ensure that the Julia version matches the sysimg version.

**Comment by SimonDanisch** [comment]
>Would be nice to add a check to ensure that the Julia version matches the sysimg version.

PR welcome :) 
Sadly, there are still enough other segfaults though...
