### ISSUE TITLE
Simple C# DLL import fails

### ISSUE THREAD

**Issue by geoff2273** [JuliaLang/PackageCompiler.jl#139]
First off, let me say how great this tool is. I've been able to generate exes with Julia 1.0, which is very pleasing. This is on Windows 10 x64.

However, I'm now struggling to import a DLL generated using this tool into a simple C# program because it raises an access violation:

```
Test!


Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x0 --
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at JuliaDllCall.Program.julia_main(String[] args)
   at JuliaDllCall.Program.Main(String[] args) in C:\.....\JuliaDllCall\JuliaDllCall\Program.cs:line 17
Press any key to continue . . .
```

Here is the culprit code

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;

namespace JuliaDllCall
{
    class Program
    {
        static void Main(string[] args)
        {
            System.Console.WriteLine("Test!\n");
            julia_main(new string[] { "" });
        }

        [DllImport(@"C:\...\Julia\builddir\hello.dll")]
        public static extern int julia_main(String[] args);
    }
}
```

hello.dll has been compiled running build_shared_lib("hello.jl") and is the example hello.jl distributed with PackageCompiler. 

I've set Visual Studio to target x64, I already dealt with an earlier error which was due to targetting x86.

**Comment by geoff2273** [comment]
Ok I think I understand where I am going wrong with this. Is it the case that I need to also link against libjulia.dll too? I can't find any example of how to do this for Julia with C#, if that is indeed possible.

I can find examples of how to embed Julia in a C application. I also see how PackageCompiler builds the exe by linking the DLL to program.c. However, my C is sufficiently poor that I don't understand how to write a DLL that enables me to call a Julia function multiple times without the overhead of jl_init every time. I will attempt to at least produce a DLL that loads jl_init every time as a stepping stone...

Any help greatly appreciated.

**Comment by geoff2273** [comment]
Solved!

Everything started working when I kept JULIAC_PROGRAM_LIBNAME consistent in my compile options:
`'-DJULIAC_PROGRAM_LIBNAME="hello.dll"'`

I have no idea what the point of JULIAC_PROGRAM_LIBNAME  is supposed to do, but if it changes it seems to give the image consistency check error.

**Comment by netlander** [comment]
Having the same problem:

Can you summarise what you have actually done?

Was using program.c really necessary?

Where do you set `-DJULIAC_PROGRAM_LIBNAME="hello.dll"` flag?

Thanks

**Comment by mroavi** [comment]
You may want to take a look at this related [issue](https://github.com/JuliaLang/PackageCompiler.jl/issues/257#issuecomment-517550657) which shows how to build a shared library with PackageCompiler.jl and call the resulting library from C++.

**Comment by KristofferC** [comment]
https://github.com/simonbyrne/libcg has examples for C and Rust and it should not be too hard to adopt that to C#.
