### ISSUE TITLE
Asked for Authontication

### ISSUE THREAD

**Issue by hasanOryx** [JuliaLang/PackageCompiler.jl#142]
I failed to get it as I got requisted for authentication as below!

<img width="409" alt="capture" src="https://user-images.githubusercontent.com/26045838/47612190-9d0abe80-da86-11e8-810a-2a94c5f73a2a.PNG">

**Comment by geoff2273** [comment]
Have you tried running as administrator (windows) or using sudo (linux)?

**Comment by jpsamaroo** [comment]
This is probably not an issue with PackageCompiler and is likely a JuliaPro issue. I recommend this be closed unless there's some further justification why this is specific to PackageCompiler.

**Comment by KristofferC** [comment]
JuliaPro issue
