### ISSUE TITLE
init_jl_runtime does not work with Python ctypes

### ISSUE THREAD

**Issue by tkf** [JuliaLang/PackageCompiler.jl#144]
I find that loading .so file created by PackageCompiler.jl using Python ctypes is a bit tricky.  It seems just calling `init_jl_runtime()` does not work.

Here is a MWE that works with Python ctypes. I had to call `jl_init_with_image` (or `jl_init_with_image__threading`) directly with the full path to the generated `.so` file:
https://gist.github.com/tkf/7a1b24ae13d01f417d616293db164b31

This version doesn't work. It calls `init_jl_runtime()` (and uses current master ded640502f230761a626e8ce0f2e3c629d31f6d9):
https://gist.github.com/tkf/d6562fc948b6418e82fb61560fd59719

It failed with:

```
ERROR: could not load library "/usr/bin/test.so"
/usr/bin/test.so: cannot open shared object file: No such file or directory
```

where `/usr/bin/` was picked presumably because that's where my `python` executable is.

Both versions should be reproducible by just running `make`.

**Comment by KristofferC** [comment]
`init_julia` from the output of `create_library` should work. I tried it a day ago with `ctypes`.
