### ISSUE TITLE
Tests fail: it tries to execute from /tmp/

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/PackageCompiler.jl#147]
I tried running `Pkg.test("PackageCompiler")` but it failed at some point with ```IOError: could not spawn `/tmp/tmpG4Jm0q/build/hello`: permission denied (EACCES)```. We always mount `/tmp/` with `noexec`, and this error shows that tests try to run an executable from there.

**Comment by KristofferC** [comment]
It is not strange for packages to want to use `tmp`. You could redirect your temp dir (https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.tempdir) when testing.
