### ISSUE TITLE
Passing multiple flags to gcc

### ISSUE THREAD

**Issue by nlw0** [JuliaLang/PackageCompiler.jl#149]
juliac takes a `--cc-flags` argument, but I'm not sure it supports passing multiple flags to gcc. It seems to pass just the value as a single string, so we can only pass a single flag. I am trying to cast the "-Ofast -march=native -funroll-loops" spell, but it's not coming through. Or is there a trick to make this work?

**Comment by lucatrv** [comment]
Fixed with PR #150, you can pass multiple flags by repeating `--cc-flag`, they will all be passed to `gcc`.

**Comment by nlw0** [comment]
Awsome, thanks!
