### ISSUE TITLE
Signalize julia code is being statically compiled

### ISSUE THREAD

**Issue by phlavenk** [JuliaLang/PackageCompiler.jl#153]
I'm dealing with [BinaryProvider issue](https://github.com/JuliaPackaging/BinaryProvider.jl/issues/140#issue-383802239) and I'd like to make an if-branch for the case the code is being statically compiled for deployment (and I need to load binary libraries from a relative location or $PATH). 
Is it possible to introduce some const or environmental variable that would signalize this in all steps that are spawned by PackageCompiler?

**Comment by KristofferC** [comment]
This should be "fixed" by using the artifact system so that PackageCompiler bundles the needed libraries.
