### ISSUE TITLE
Handle juliaprog = nothing in static_julia

### ISSUE THREAD

**Issue by jdchn** [JuliaLang/PackageCompiler.jl#156]
[`build_sysimg`](https://github.com/JuliaLang/PackageCompiler.jl/blob/9c774dad6872df3486517c050aa4e50e87ca12a6/src/api.jl#L13) calls [`static_julia`](https://github.com/JuliaLang/PackageCompiler.jl/blob/9c774dad6872df3486517c050aa4e50e87ca12a6/src/static_julia.jl#L70) with `juliaprog = nothing` if the `userimg_path` argument is not specified. This use case may occur if a user simply wants to rebuild the system image.

This condition causes errors in `static_julia` since it assumes `juliaprog` will be a valid path to a Julia file.

The errors can be easily avoided with a few `julia != nothing && ...` guards in `static_julia` and [`build_object`](https://github.com/JuliaLang/PackageCompiler.jl/blob/9c774dad6872df3486517c050aa4e50e87ca12a6/src/static_julia.jl#L233). 

Alternatively, `build_sysimg` can be changed to fail fast if `userimg_path == nothing`. If this option is chosen, the [docstring](https://github.com/JuliaLang/PackageCompiler.jl/blob/9c774dad6872df3486517c050aa4e50e87ca12a6/src/api.jl#L2) should be updated.

**Comment by lucatrv** [comment]
Merged, thanks!!
