### ISSUE TITLE
rename [to AOTCompiler ? ]

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/PackageCompiler.jl#160]
@StefanKarpinski and others have contemplated to rename PackageCompiler. I forgot what we actually came up with, but I personally started liking AOTCompiler, since this package is mainly about compiling Julia packages/executables/script ahead of time. The whole static compilation track seems a bit misleading - it is related, but you can definitely also just ahead of time compile an executable of a completely dynamic julia program.

**Comment by StefanKarpinski** [comment]
I don't recall what was proposed but I think the current name is better than AOTCompiler. Perhaps just Compiler.jl or JuliaCompiler.jl?

**Comment by lucatrv** [comment]
I vote for JuliaCompiler.jl

**Comment by 564064202** [comment]
I vote for JuliaAotCompiler.jl

**Comment by musm** [comment]
`JuliaCompiler.jl` sounds like the Julia compiler itself, which is kinda confusing. I don't mind `AOTcompiler.jl`, which  sounds pretty reasonable.

**Comment by StefanKarpinski** [comment]
`AppCompiler`? The key is that it's not really a compiler for packages—it compiles applications.

**Comment by ararslan** [comment]
I think the best proposal so far has been AppCompiler. None of the others really clarify what this is intended to do. AOTCompiler pretty jargony; do people who make applications necessarily know the acronym?

**Comment by vtjnash** [comment]
A compiler is (part of) what it uses, but doesn't really say what this is, which is a tool to build and deploy applications. How about ApplicationBuilder.jl?

**Comment by lucatrv** [comment]
Other options could be `JuliaMake`, `JuliaBuild`, `JuliaBuilder`. Let's not forget that it can be used also to build static libraries alone. [`ApplicationBuilder.jl`](https://github.com/NHDaly/ApplicationBuilder.jl) already exists, and relies on `PackageCompiler.jl`.

**Comment by lucatrv** [comment]
I actually like `JuliaMake`, as it gives the idea of a build tool.

**Comment by StefanKarpinski** [comment]
> AOTCompiler pretty jargony; do people who make applications necessarily know the acronym?

This. Most people seeing `AOTCompiler` would think “what’s and AOT and why would I want to compile it?” But if they see `AppCompiler` they'll think “ooo, I can compile my app? nice!”

**Comment by musm** [comment]
I agree with Stefan on AOTCompiler.   And indeed the current name is pretty misleading. AppCompiler does indeed sound like a good compromise if everyone is on board.

**Comment by StefanKarpinski** [comment]
There was some ephemeral discussion of this and it was pointed out that this package can compile both packages and applications and since we (meaning I) have decided that "project" is the umbrella term for packages and applications, perhaps `ProjectCompiler.jl` would be the most accurate name. There also seemed to be a fair amount of support for that name when I mentioned it. I didn't realize that I hadn't posted it somewhere non-ephemeral (i.e. here) so I'm doing so now!

**Comment by tknopp** [comment]
`ProjectBuilder` or `BinaryBuilder`?

I am with Jameson here that this is more about a build tool and not the compiler itself

**Comment by jpsamaroo** [comment]
> `BinaryBuilder`

This is already exists :)

**Comment by tknopp** [comment]
I know, but lets brainstorm without constraints. This here has potential to get into stdlib and in turn has highest precedence.

**Comment by jpsamaroo** [comment]
...BinaryBuilder is BinDeps2, if you didn't realize. Both of these packages are of equal importance (and regardless, expecting a pre-existing package to change its name just because you want it for another package is unfair and unkind).

**Comment by tknopp** [comment]
> expecting a pre-existing package to change its name just because you want it for another package is unfair and unkind

not at all. If several people agree that a naming was not optimal it is absolutely ok if people try to come up with better naming. (This is not specific about BB). Why should a discussion about naming be unfair or unkind?

**Comment by musm** [comment]
I'm confused why you suggest BinaryBuilder ? This package doesn't build binaries so it's inappropriate.

**Comment by tknopp** [comment]
> This package doesn't build binaries so it's inappropriate

what does it then? And just to be clear: A system image (.so on linux) is a binary.

**Comment by jpsamaroo** [comment]
It definitely does build binaries, let's just not assume BB wants to be renamed (that would cause so much confusion if PackageCompiler took that name anyway). I'm all for any of the Project* names, and totally against anything using the word "App" (way overused and makes people think we're building stuff specifically for phones or app stores).

**Comment by tknopp** [comment]
Ok forget about my concrete suggestion `BinaryBuilder`. The point I wanted to make is that
 - the terms `Binary` and `Builder` are describing quite well what this package does
 - one should take a name that allow transition into `stdlib` since there is some potential that this ends up living there.

**Comment by tknopp** [comment]
`BinaryMaker`, `BinaryBaker`, or `BinaryFactory`?

**Comment by StefanKarpinski** [comment]
I'm not sure that the emphasis belongs on the binary generation part. The main benefit is that it takes your Julia project and compiles it, not that it generates binaries. It could, for example, compile your Julia project to C code using the LLVM backend, which is still compilation but is not generating a binary. The name `BinaryBuilder` is appropriate for the use it already has since in that case the point is to generate binary files which can be loaded from within Julia (Julia cannot load external code otherwise).

Based purely on emoji reactions, `ProjectCompiler` seems to be the leader here.

**Comment by tknopp** [comment]
Well `compiler` is the thing that makes `binaries`, so these are certainly linked. Using the term `compiler` highlights the process, how this is done. `binary` focuses more on the product that is generated. 

> It could, for example, compile your Julia project to C code using the LLVM backend, which is still compilation but is not generating a binary.

yes and from my impression, this package is focussing 100% on the binary generation and not  alternative outputs. `Projects` are also `compiled` when I call them from within the Julia REPL. The point of this package is to store `binary` code on disk. At least I thought that this is the purpose.

**Comment by StefanKarpinski** [comment]
The point is that what this package provides is specifically the ability to compile Julia projects, regardless of what form the output of the compiler takes. There's nothing specific about this package about generating binaries aside from the fact that binaries are the default output of compilation.

**Comment by StefanKarpinski** [comment]
But I see your point about saving the otherwise transient compiled code.

**Comment by tknopp** [comment]
So in other words. Is the generation of the shared library / executable an implementation detail of this package or is it part of the interface.

One issue of this naming discussion is that it is somewhat unclear how this package will evolve over time. My hope is that this gets upstreamed into the stdlib and tighly integrated with Pkg. In the end, I hope that Pkg recognizes that new updates are available and that a new system image needs to be baken. So maybe its just best to wait with a rename until things get clear.

**Comment by KristofferC** [comment]
I think this name will stay.
