### ISSUE TITLE
UndefVarError - function accidentally removed on v0.6.0

### ISSUE THREAD

**Issue by asinghvi17** [JuliaLang/PackageCompiler.jl#171]
See this [comment](https://github.com/JuliaLang/PackageCompiler.jl/commit/266eaf10553a47fb75d26dd3af99f52ce1f2e7c4#r32108127) on the latest commit by @SimonDanisch - in Julia v1.1, PackageCompiler v0.6.0, 

```julia
using PackageCompiler
compile_package("Makie", force = false)
```
yields the output
```julia
ERROR: UndefVarError: snoop_userimg not defined
Stacktrace:
 [1] #compile_package#70(::Bool, ::Bool, ::Bool, ::Nothing, ::Array{Symbol,1}, ::Function, ::Tuple{String,String}) at /Users/anshul/.julia/packages/PackageCompiler/osIMW/src/PackageCompiler.jl:118
 [2] compile_package at /Users/anshul/.julia/packages/PackageCompiler/osIMW/src/PackageCompiler.jl:116 [inlined]
 [3] #compile_package#67 at /Users/anshul/.julia/packages/PackageCompiler/osIMW/src/PackageCompiler.jl:94 [inlined]
 [4] compile_package(::String) at /Users/anshul/.julia/packages/PackageCompiler/osIMW/src/PackageCompiler.jl:88
 [5] top-level scope at none:0
```

**Comment by SimonDanisch** [comment]
oh wait, I thought I fixed this -.- 
Well, if you can, you should use compile_incremental!

**Comment by SimonDanisch** [comment]
there we go - uncommitted change on my home computer -.-
Welp, at least it's not lost! Will test + commit + tag asap!
But note that I do plan to deprecate `compile_package`, since `compile_incremental` works much better (e.g. it will also contain the precompiled code from the system image - so faster repl startup).... And it also compiles much faster!

**Comment by asinghvi17** [comment]
#172 adds compile_incremental to the export statement of PackageCompiler.jl so it can be used normally.  Currently undergoing automated CI.

**Comment by asinghvi17** [comment]
Thanks for the suggestion about `compile_incremental`, though - it does help a lot.

**Comment by SimonDanisch** [comment]
hm tests are hanging with the fix -.- I'll need to continue this tomorrow ;)

**Comment by SimonDanisch** [comment]
Hopefully fixed on newest tag...windows seems to be a bit bitchy about the changes - not sure if that's a new problem, since the `compile_package` didn't fully survive the 1.0 migration in any case...
