### ISSUE TITLE
filepath problems on windows when using builddir and snoopfile

### ISSUE THREAD

**Issue by korbinian90** [JuliaLang/PackageCompiler.jl#178]
Some strange thing happens with the path of the file to compile.
-> X:\Z:\julia\test.jl
It compiles fine if I leave out either the builddir option or the snoopfile option.
The problem arises only when using both.

```
julia> build_executable("Z:/julia/test.jl"; builddir = "X:/julia/builddir", snoopfile = "unwrapTestWin.jl")
Julia program file:
  "Z:\julia\test.jl"
C program file:
  "C:\Users\IDEAUSER\.julia\packages\PackageCompiler\SGFCk\examples\program.c"
Build directory:
  "X:\julia\builddir"
  2.404433 seconds (29.63 M allocations: 1.067 GiB, 6.93% gc time)
[ Info: used 145 out of 145 precompile statements
ERROR: LoadError: LoadError: could not open file X:\Z:\julia\test.jl
```

**Comment by SimonDanisch** [comment]
I guess it's the use of relpath in this line:
https://github.com/JuliaLang/PackageCompiler.jl/blob/master/src/static_julia.jl#L156

**Comment by KristofferC** [comment]
It might be fixed with new implementation. Please try and report back :)
