### ISSUE TITLE
Build fails with gcc error

### ISSUE THREAD

**Issue by ValdarT** [JuliaLang/PackageCompiler.jl#185]
I get this error at the build step on macOS Mojave, Julia v1.1 and PackageCompiler v0.6.3
```
Error: Error building `PackageCompiler`: 
│ [ Info: Installing GCC
│ ERROR: LoadError: Please make sure to provide a working gcc in your path!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] build() at /Users/user/.julia/packages/PackageCompiler/oT98U/deps/build.jl:56
│  [3] top-level scope at none:0
│  [4] include at ./boot.jl:326 [inlined]
│  [5] include_relative(::Module, ::String) at ./loading.jl:1038
│  [6] include(::Module, ::String) at ./sysimg.jl:29
│  [7] include(::String) at ./client.jl:403
│  [8] top-level scope at none:0
│ in expression starting at /Users/user/.julia/packages/PackageCompiler/oT98U/deps/build.jl:63
```

**Comment by SimonDanisch** [comment]
> LoadError: Please make sure to provide a working gcc in your path!

Did you try doing that? I don't know how to install gcc on macos, but I believe it should be fairly simple ;)

**Comment by ValdarT** [comment]
Oh, sorry, the `Info: Installing GCC` make me think that it is supposed to do this automatically :)

**Comment by SimonDanisch** [comment]
It tries, but since I don't know how to do it on OSX, it fails^^

**Comment by essenciary** [comment]
@SimonDanisch FYI I'm getting the same error when trying to add PackageCompiler to a container built off the official Julia docker image (ubuntu based).

**Comment by kdheepak** [comment]
The [Julia docker images](https://github.com/docker-library/julia/) don't appear to have a C compiler installed. See https://github.com/docker-library/julia/issues/13 and try the steps suggested in that issue?

**Comment by kdheepak** [comment]
And maybe the error message here can be improved.

**Comment by essenciary** [comment]
@kdheepak Thanks - I just added the apt-get command to the Dockerfile. My point was that it might be beneficial if at all possible, to add it as a step in the build process of the package as it's not just a macOS issue.
