### ISSUE TITLE
In windows, if Julia was not booted with admin previlege, error occurs.

### ISSUE THREAD

**Issue by K-Tank** [JuliaLang/PackageCompiler.jl#186]
Dear developers, 

I could not compile test hello.jl in my Julia 1.1 on Win 10. 
I found it was because Julia was not booted with admin previlege.
( at least, with admin previlege, compile passed)

I searched documentation for referring to need for admin, but I could not find. 
Please note need for admin previlege in Win Julia PackageCompiler.jl

Yours,

**Comment by SimonDanisch** [comment]
I think this isn't a packagecompiler issue, but rather a BinaryProvider issue...
Please reopen with more details (e.g. stacktrace + error messages), if you think this is a PackageCompiler issue.
