### ISSUE TITLE
Snooping doesn't record all functions anymore

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/PackageCompiler.jl#188]
As discussed on Slack, the new snooping implementation seems to be missing some function calls. Just opening an issue to keep track of this.

**Comment by SimonDanisch** [comment]
Thanks for keeping track! Btw, I rather don't suspect the snooping, since the numbers have barely changed as far as I can tell ;)

**Comment by KristofferC** [comment]
Fixed in 1.3.
