### ISSUE TITLE
Possibility to strip libs and executables

### ISSUE THREAD

**Issue by Astrych** [JuliaLang/PackageCompiler.jl#189]
Created executables and libraries are not stripped from debug symbols and info. Especially the big ones like libjulia libLLVM, application library and so on.
I know it can be done in a shell after whole building process but I think it would be good to have that option also inside PackageCompiler. It can save some disk space, especially when you have several independent Julia apps.

**Comment by KristofferC** [comment]
This feels out of scope for the package. We need to implement it for all platforms etc. You can easily just write your own little script if it is important to you.
