### ISSUE TITLE
Do I need to precompile PackageCompiler.jl as well?

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaLang/PackageCompiler.jl#195]
Theoretically, should we precompile PackageCompiler.jl?

**Comment by lucatrv** [comment]
I am not sure what you mean by "do I need", to use `juliac` you do not "need" to precompile it, but yes producing a `juliac` executable was one of my initial targets, that is the reason for the following definition in `juliac.jl`:

```julia
Base.@ccallable function julia_main(args::Vector{String})::Cint
```

When I attempted to do it time ago it did not work though, but I have not tried recently.

**Comment by NHDaly** [comment]
Here are some notes from our last attempt: https://github.com/JuliaLang/PackageCompiler.jl/issues/78 🙂
