### ISSUE TITLE
[Feature request] Skip precompilations that cause segfaults

### ISSUE THREAD

**Issue by asinghvi17** [JuliaLang/PackageCompiler.jl#198]
Currently, to get some packages to compile, it is necessary to remove segfaulting lines from the snoopfile.  Is it possible to automate this using a `while` loop or something similar, such that the compilation process will run, a line will error out, then it will be removed from the file and can be tried again?  This would make compiling packages a lot easier.

**Comment by KristofferC** [comment]
What precompile statements makes Julia segfault? This shouldn't happen and bug reports should be filed against Julia for it.
