### ISSUE TITLE
Local package using other local package

### ISSUE THREAD

**Issue by loicspace** [JuliaLang/PackageCompiler.jl#200]
I am trying to compile a local package "AstroDynamics" that I have "dev-ed" in Julia 1 that depends on another package "CSpice", also "dev-ed" and when running:

```
using PackageCompiler
compile_package("AstroDynamics", force = false)
```

or

`compile_package("CSpice","AstroDynamics", force = false)`

I get the following error:

```
[ Info: Recompiling stale cache file /home/loic/.julia/compiled/v1.0/AstroDynamics/zNHh5.ji for AstroDynamics [28105d2d-cb57-5bb8-9872-e195576fa943]
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: LoadError: Unsatisfiable requirements detected for package CSpice [86c8f9a4]:
 CSpice [86c8f9a4] log:
 ├─CSpice [86c8f9a4] has no known versions!
 └─restricted to versions * by an explicit requirement — no versions left
```

When trying to compile the two packages together, the first one, CSpice, seems to go through, the error occurs in both instances when dealing with the second package, AstroDynamics, the one that has the dependency on the other local package. The dependency is properly recorded in project.toml and manifest.toml as far as i can tell.

Am I missing something? Thanks!

**Comment by mohamed82008** [comment]
I am getting the same error here. Any chance this will get some love soon?

**Comment by SimonDanisch** [comment]
You could try: sd-notomls, where I simplify the Pkg3 shenanigans and simply just automatically install all dependencies.
I'm testing this branch right now with Makie:
https://nextjournal.com/a/KyzheSmqGkv7si3iBNk8x?token=LvoV1mZo98HorurW2GePs

**Comment by mohamed82008** [comment]
So this seems to work initially, but I ran into another trouble with compiling CuArrays. That's a different issue though. Thanks for the quick response!

**Comment by KristofferC** [comment]
I think this should work now.
