### ISSUE TITLE
Understading `compile_package`

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaLang/PackageCompiler.jl#203]
If I want to have both `DataFrames` and `DataFramesMeta` compiled do I need to do them at once? Or can I do them one after the other?

E.g. must I do this 
```julia
compile_package("DataFrames", "DataFramesMeta", force = false) 
```
or I can do this

```julia
compile_package("DataFrames", force = false) 
compile_package("DataFramesMeta", force = false) 
```

**Comment by asinghvi17** [comment]
You would need to do both together, and you would be better off using `compile_incremental`
