### ISSUE TITLE
Base.Multimedia.displays

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/PackageCompiler.jl#209]
with julia 1.1 and PackageCompiler master i `compile_package("Gadfly", force=false)`.  first-time-to-plot is ~10x faster!

however, there is one glitch in that `Base.Multimedia.displays` has `REPLDisplay` as the last entry, and `GadflyDisplay` second to last, so just doing a `using Gadfly; plot(y=[1,2,3])` does not automatically display the plot in your default browser, like it does without pre-compilation of a new sysimg :(

i tried `compile_package("REPL", "Gadfly", force=false)` but that did not put GadflyDisplay last.  is there a proper way to fix this?

the workaround is to run this code, perhaps in your startup.jl:

```
function putatend(idisplay, display::Gadfly.GadflyDisplay)
 gadflydisplay = splice!(Base.Multimedia.displays, idisplay)
  push!(Base.Multimedia.displays, gadflydisplay)
  true
end
putatend(idisplay, display) = false

for (idisplay, display) in enumerate(Base.Multimedia.displays)
  putatend(idisplay, display) && break
end
```

**Comment by KristofferC** [comment]
Needs https://github.com/JuliaLang/julia/pull/30922. Not much that can be done from PackageCompiler's side.

**Comment by ppalmes** [comment]
any updates on this?
