### ISSUE TITLE
Failing to deserialize JLD files after packagecompile

### ISSUE THREAD

**Issue by jonbarkerlondon** [JuliaLang/PackageCompiler.jl#227]
After compiling my application with PC, I can no longer load serialized JLD files from disk due to type names changing - I just receive warnings (and eventual fails) about types being reconstructed.

> ┌ Warning: type Dates.UTInstant{Dates.Millisecond} not present in workspace; reconstructing
> └ @ JLD C:\Program Files\ReSolver.DistributedJulia\depot\packages\JLD\1BoSz\src\jld_types.jl:703
> ┌ Warning: type Dates.Millisecond not present in workspace; reconstructing
> └ @ JLD C:\Program Files\ReSolver.DistributedJulia\depot\packages\JLD\1BoSz\src\jld_types.jl:703
> 

My application doesn't normally work within a Module, so I added in some translate code.
Initially i was prefixing with `anon_module.`, but switched to `Mod.` but this still isn't working.

How does the package compiler change type names around? Why doesn't DateTime for example remain under Main.Dates? Why does it move to Main.Mod.Dates?

Any advice or hints as to what's happening behind the scenes would be appreciated!

Jon

**Comment by jonbarkerlondon** [comment]
Update, i may have cracked it by using JLD translate redirects between the original types and the compiled types:

	
JLD.translate("Dates.DateTime", "Mod.Dates.DateTime")

JLD.translate("Dates.UTInstant{Dates.Millisecond}","Mod.Dates.UTInstant{Mod.Dates.Millisecond}")

JLD.translate("Dates.Millisecond", "Mod.Dates.Millisecond")	

JLD.translate("PortfolioType", 		"Mod.PortfolioType")

JLD.translate("PortfolioType_v3", 	"Mod.PortfolioType")

Anyone have any better ideas?

**Comment by KristofferC** [comment]
I think this is fixed in the same vein as https://github.com/JuliaLang/PackageCompiler.jl/issues/235.
