### ISSUE TITLE
Output byte code?

### ISSUE THREAD

**Issue by dogiv** [JuliaLang/PackageCompiler.jl#232]
I'm trying to transpile Julia into C using the instructions [here ](https://juliacomputing.com/blog/2016/03/10/j2c-announcement.html) but I haven't found a way to produce a .bc file now that the --output-bc option no longer works. It seems like PackageCompiler must be producing bytecode as an intermediate result... does anyone know how to output the .bc file?

**Comment by jamie-arcc** [comment]
I am definitely interested in this, too.  It would be great to be able to produce cross-platform builds in one "executable" that can then be JIT or fully compiled by llvm on the target host

**Comment by KristofferC** [comment]
What do you mean `--output-bc` no longer works?

**Comment by dogiv** [comment]
When I run it with the --output-bc flag it always tells me "ERROR: could not open file boot.jl"
I can't remember where but I read somewhere that this option was deprecated.
I'm running Julia 1.2.0 on Windows.
e.g.
C:\>c:\julia\bin\julia.exe hello.jl
hello world
C:\>c:\julia\bin\julia.exe --output-bc hello.jl
ERROR: could not open file boot.jl
C:\>c:\julia\bin\julia.exe --compile=all --output-bc hello.jl
ERROR: could not open file boot.jl
C:\>c:\julia\bin\julia.exe --compile=all hello.jl
hello world

**Comment by KristofferC** [comment]
You need to explicitly give a sysimage with `-Jpath/to/sysimage` when you do `output-(o/bc/ji)`.
