### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Pbellive** [JuliaLang/PackageCompiler.jl#243]
Hi,
      I've been using some of the features added to PackageCompiler since the last release (including the ones I added) pretty regularly. Current master seems to be working nicely. I'm wondering if it would be possible to release a new version incorporating changes merged into master since the last release? or are you waiting for more changes to accumulate or for some of the open PRs to be merged? No worries if you'd like to hold off on a release, just wondering.

**Comment by SimonDanisch** [comment]
https://github.com/JuliaRegistries/General/pull/1418

**Comment by Pbellive** [comment]
This is great. Thanks for getting the realease out.
