### ISSUE TITLE
Sort out PRs

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/PackageCompiler.jl#245]
@SimonDanisch do you think there is a chance you could go over the open PRs and either merge them, close them, or write a really short response what their status is?

I'd like to contribute some to this package, but a number of the open PRs change things I would want to touch, and so I'm not sure where to start with the current state of affairs.

**Comment by SimonDanisch** [comment]
https://github.com/JuliaLang/PackageCompiler.jl/pull/204 is the new implementation you should focus any effort on. 
It's almost done, just needs to update the tests and figure out how to work with packages that are only in the load path. The other PRs don't do much!

**Comment by davidanthoff** [comment]
Cool!

I'm about to add custom sysimage support to the VS Code extension (https://github.com/julia-vscode/julia-vscode/pull/761), but ended up using a slightly different strategy than what I thought I would do just a few days ago :) If you have thoughts/comments on the approach in that PR, I'd be very interested!

**Comment by KristofferC** [comment]
Should be obsolete.
