### ISSUE TITLE
Package compilation in debian/ubuntu linux dockerized image is not working

### ISSUE THREAD

**Issue by ppalmes** [JuliaLang/PackageCompiler.jl#250]
I tried to use compile_incremental(:Packagename,include=true) but always have pipeline_error. If I install the same linux OS in virtualbox, compile_incremental works.

Question: Aside from build-essential, are there any packages i need to install to compile_incremental DataFrames or Makie? It seems that dockerized image may not have enough packages compared to full installation of debian/ubuntu linux in virtualbox.

**Comment by ppalmes** [comment]
Anybody who did successfully use PackageCompiler in docker?

**Comment by SimonDanisch** [comment]
Yes: https://nextjournal.com/julia-environments
Most of those articles freeze the result into a docker environment, which can be easily used by remixing these articles:
https://nextjournal.com/julia

**Comment by ppalmes** [comment]
thanks for the links! i'll try to compile again and get back here if there are still issues. otherwise, i'll close this issue.
