### ISSUE TITLE
Add the option to skip adding stdlibs to the sysimage 

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaLang/PackageCompiler.jl#251]
Per the discussion in the static-compilation channel on Slack, we should provide the option to not build certain stdlibs into the sysimage that the user doesn't want or need. This is generally as simple as modifying the array of stdlib names in `base/sysimg.jl` to remove the ones that are undesired (of course, somehow taking inter-stdlib dependencies into account). Additionally, to make this work, the `generate_precompile` step needs to be disabled as it relies on being able to use the Julia REPL to generate precompile statements.

Doing this allows one to shrink the sysimage by a considerable size, which is beneficial in constrained use cases or where numerous Julia processes will run at once (since each of them take up ~200MB of resident memory before loading any user code).

**Comment by gabrielfreire** [comment]
In my opinion shrinking the size of the final standalone executable is the most important feature of this whole package. Is there any work going on related to tree-shaking ??

**Comment by jpsamaroo** [comment]
That 200MB final executable is so huge partly because of the stdlibs, so this would help with that. Tree shaking is also something that needs to be done, but will probably need explicit codegen support (note how CUDAnative doesn't bundle the whole sysimage in its GPU kernels).

**Comment by gabrielfreire** [comment]
The CUDAnative has it's own compiler written in Julia, i don't understand very much how it works but it seems to me that it is very specific to work with CUDA and not very generic, am i right ?

**Comment by jpsamaroo** [comment]
CUDAnative drives Julia and LLVM to generate code for a specific LLVM backend (NVPTX in the case of CUDA), but can be repurposed to generate code for any other backend without too much difficulty. MCAnalyzer.jl and AMDGPUnative.jl are working examples of this (for X86/native and AMDGPU backends, respectively). This mechanism is similar to how Julia itself generates code for the sysimages that this package produces, but gives more control over what methods are compiled into the final binary (allowing one to strip out code that won't be needed by your program).

**Comment by KristofferC** [comment]
This is now possible (`filter_stdlibs` option).
