### ISSUE TITLE
Compiling inside docker under Linux OS works but fails in OS X

### ISSUE THREAD

**Issue by ppalmes** [JuliaLang/PackageCompiler.jl#254]
- creating a docker with compile_incremental(package, install=true) works in Linux OS but fails in Mac OS
- compile_package(package) in a dockerized julia fails in both Linux and Mac OS
- it's a puzzle that the same Dockerfile with compile_incremental workflow works in Linux OS but not in Mac OS using Debian Buster as the docker base image. same issues with ubuntu base image.

**Comment by KristofferC** [comment]
Ref https://github.com/JuliaComputing/PackageCompilerX.jl/issues/106.

Please comment if this still fails on the current PackageCompiler.
