### ISSUE TITLE
Have to run WinRPM.update() manually on fresh install

### ISSUE THREAD

**Issue by changhe3** [JuliaLang/PackageCompiler.jl#260]
The package fails to build on a fresh install of Julia 1.1.1 on Windows 10 x64 and I have to run WinRPM.update() manually for it to build. I did this a few days ago so I forgot to copy the error message, but this seems to be a very trivial bug so I'll just post it here.

**Comment by DilumAluthge** [comment]
I think this can be closed now. The new PackageCompiler does not use WinRPM.
