### ISSUE TITLE
Error creating EXE for large program

### ISSUE THREAD

**Issue by mtwhite4** [JuliaLang/PackageCompiler.jl#265]
Hi all, 

I am attempting to create an executable version of a program that I made. This program is very dependent-heavy (read: uses a lot of outside packages including a custom module) and the `build_executable()` function returns the error shown at the link below. Any help would be much appreciated as I am new to this whole process.
Error: https://pastebin.com/PVBUM2fY

**Comment by KristofferC** [comment]
Please try with new version of PackageCompiler
