### ISSUE TITLE
Failed to compile with ERROR: GCC wasn't found

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaLang/PackageCompiler.jl#267]
I get the below GCC error. I am on Windows PRo 10,  using Julia 1.1.1 and I am using `]dev PackageCompiler`.

I was trying to `compile_incremental(:DataFrames, force = false)`

Clearly gcc is in on the path as I can do `;gcc` which gives

> shell> gcc
> gcc: fatal error: no input files
> compilation terminated.

**Fulll error message below**

> ERROR: LoadError: LoadError: LoadError: LoadError: GCC wasn't found. Please make sure that gcc is on the path and run Pkg.build("PackageCompiler")
> Stacktrace:
>  [1] error(::String) at .\error.jl:33
>  [2] top-level scope at C:\Users\RTX2080\.julia\packages\PackageCompiler\CJQcs\src\static_julia.jl:11
>  [3] include at .\boot.jl:326 [inlined]
>  [4] include_relative(::Module, ::String) at .\loading.jl:1038
>  [5] include at .\sysimg.jl:29 [inlined]
>  [6] include(::String) at C:\Users\RTX2080\.julia\packages\PackageCompiler\CJQcs\src\PackageCompiler.jl:1
>  [7] top-level scope at none:0
>  [8] include at .\boot.jl:326 [inlined]
>  [9] include_relative(::Module, ::String) at .\loading.jl:1038
>  [10] _require(::Base.PkgId) at .\loading.jl:986
>  [11] require(::Base.PkgId) at .\loading.jl:858
>  [12] require(::Module, ::Symbol) at .\loading.jl:853
>  [13] include at .\boot.jl:326 [inlined]
>  [14] include_relative(::Module, ::String) at .\loading.jl:1038
>  [15] include(::Module, ::String) at .\sysimg.jl:29
>  [16] top-level scope at none:0
> in expression starting at C:\Users\RTX2080\.julia\packages\PackageCompiler\CJQcs\src\static_julia.jl:3
> in expression starting at C:\Users\RTX2080\.julia\packages\PackageCompiler\CJQcs\src\PackageCompiler.jl:8
> in expression starting at C:\Users\RTX2080\.julia\dev\PackageCompiler\packages\incremental_precompile.jl:17
> in expression starting at C:\Users\RTX2080\.julia\dev\PackageCompiler\sysimg\run_julia_code.jl:10
> ERROR: failed process: Process(`'C:\Users\RTX2080\AppData\Local\Julia-1.1.1\bin\julia.exe' --optimize=3 '--output-o=C:\Users\RTX2080\.julia\dev\PackageCompiler\sysimg\sys.a' -g1 --track-allocation=none --startup-file=no --code-coverage=none --history-file=yes --inline=yes --math-mode=ieee --handle-signals=yes --warn-overwrite=no --compile=yes --depwarn=yes --cpu-target=native --track-allocation=none --sysimage-native-code=yes '--sysimage=C:\Users\RTX2080\AppData\Local\Julia-1.1.1\lib\julia\sys.dll' -g1 --compiled-modules=yes --optimize=2 'C:\Users\RTX2080\.julia\dev\PackageCompiler\sysimg\run_julia_code.jl'`, ProcessExited(1)) [1]
> Stacktrace:
>  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
>  [2] pipeline_error at .\process.jl:785 [inlined]
>  [3] #run#515(::Bool, ::Function, ::Cmd) at .\process.jl:726
>  [4] run at .\process.jl:724 [inlined]
>  [5] #run_julia#1 at C:\Users\RTX2080\.julia\dev\PackageCompiler\src\compiler_flags.jl:225 [inlined]
>  [6] #run_julia at .\none:0 [inlined]
>  [7] #compile_incremental#62(::Bool, ::Bool, ::Bool, ::Nothing, ::Function, ::String, ::String) at C:\Users\RTX2080\.julia\dev\PackageCompiler\src\incremental.jl:82
>  [8] #compile_incremental#63 at .\none:0 [inlined]
>  [9] (::getfield(PackageCompiler, Symbol("#kw##compile_incremental")))(::NamedTuple{(:force,),Tuple{Bool}}, ::typeof(compile_incremental), ::Symbol) at .\none:0
>  [10] top-level scope at util.jl:156
> 
> shell> gcc
> gcc: fatal error: no input files
> compilation terminated.

**Comment by SimonDanisch** [comment]
Did you run `]build PackageCompiler`?

**Comment by xiaodaigh** [comment]
Yes. I followed the advice. To rebuild.

**Comment by xiaodaigh** [comment]
I checked the `build.log` for PackageCompiler and it says

> C:\Users\RTX2080\.julia\dev\PackageCompiler\deps\build.log

**Comment by xiaodaigh** [comment]
I fixed this by doing the followig steps

* In Julia `]rm PackageCompiler
* Manually remove the PackageCompiler folder from `C:\Users\UserName\.julia\dev\PackageCompiler`
* Manually remove the PackageCompiler folder from `C:\Users\UserName\.julia\packages\PackageCompiler`
* Manually remove C:\Users\RTX2080\.julia\compiled\v1.1\PackageCompiler
* Close down Julia

Then install PackageComipler again. This time, the `build.log` says

> [ Info: Installing GCC
> [ Info: Using `gcc` from WinRPM as C compiler
