### ISSUE TITLE
Error compiling Makie on 1.3.0-rc2

### ISSUE THREAD

**Issue by j-fu** [JuliaLang/PackageCompiler.jl#276]
Hi, while I was able to compile Makie for 1.2.0, the same procedure failed for 1.3.0-rc2 on openSUSE Tumbleweed, see [pr.txt](https://github.com/JuliaLang/PackageCompiler.jl/files/3632994/pr.txt) .

For a smaller package (ExtendableSparse) it however worked, so it does not seem entirely broken.
Makie without precompilation works  as well.

**Comment by KristofferC** [comment]
Looks the same as https://github.com/JuliaLang/julia/issues/33590.

**Comment by KristofferC** [comment]
Should be fixed in Julia
