### ISSUE TITLE
Feature request: allow julia argument `--color=yes` in build_executable

### ISSUE THREAD

**Issue by cihga39871** [JuliaLang/PackageCompiler.jl#278]
Is it possible to add an option `color` in `build_executable` to get color output?

**Comment by kdheepak** [comment]
You are requesting for `--color=yes` in the output binary from `build_executable`? You can use `ArgParse` in the Julia file that you are trying to compile using PackageCompiler and add custom command line arguments. I'm not sure if `--color=yes` can be triggered though. Can you give an example of what you are trying to do?

**Comment by kdheepak** [comment]
See this as an example: https://github.com/carlobaldassi/ArgParse.jl/issues/63

**Comment by cihga39871** [comment]
Thank you, @kdheepak .

Julia binary has an option `--color={yes,no,auto}` which controls color output, such as the output of `@info "text"`. Consider the following output from a terminal:

```bash
$ julia --color=yes -e '@info ARGS' arg1 arg2 arg3  # output 'Info:' is cyan.
[ Info: ["arg1", "arg2", "arg3"]

$ julia --color=no -e '@info ARGS' arg1 arg2 arg3  # output 'Info:' has the same color as '["a", "b", "c"]' 
[ Info: ["arg1", "arg2", "arg3"]
```

`--color=yes` does not send to `Main.ARGS`. It is parsed and saved in `jl_options.color` in C. Then, Julia provides a function to get acess to it: 

```julia
Base.JLOptions() = unsafe_load(cglobal(:jl_options, JLOptions))`
```

However, fields in `JLOptions` are unchangeable. I did not find a way to modify it and change the color output in Julia code.

---

If we build an executable for this file (arginfo.jl):

```julia
module ArgInfo
Base.@ccallable function julia_main(ARGS::Vector{String})::Cint
    @info "Input arguments are" ARGS
    return 0
end
end
```

It will generate those files:
 - arginfo (executable)
 - arginfo.so (extension is .dll in Windows or .dylib in OSX)

We cannot get color output if calling `./arginfo arg1` from a terminal.
To get a color output, we need to use `julia --color=yes -J arginfo.so arg1`.

Therefore, is it possible to add an option `color` in `build_executable` to get color output? Like this:
```julia
build_executable(...; color="yes", kw...)
```

**Comment by asinghvi17** [comment]
https://github.com/JuliaLang/PackageCompiler.jl/blob/b762532eea7dacd43d1d80588398aaaad6f9c153/src/static_julia.jl#L192-L233

This function and its callers might be worth looking into.

**Comment by cihga39871** [comment]
Thank you, @asinghvi17 .
I will look into it tomorrow.

**Comment by KristofferC** [comment]
`color=yes` shouldn't be needed in Julia 1.5 (it should happen automatically based on stdout being a TTY). Let's just wait for that.
