### ISSUE TITLE
Building multiple binaries in parallel is broken

### ISSUE THREAD

**Issue by dhazeghi** [JuliaLang/PackageCompiler.jl#282]
Building multiple binaries in parallel has been broken since 0.6.1.  Basically, if you compile n different programs, you end up with n different copies of the same program.

```
$ cat /tmp/other.jl
Base.@ccallable function julia_main(ARGS::Vector{String})::Cint
    println("DARA other")
    return 0
end
$ cat /tmp/test.jl
Base.@ccallable function julia_main(ARGS::Vector{String})::Cint
    println("DARA test")
    return 0
end
$ julia /test/julia-1.3.0-rc3/pkg/dev/PackageCompiler/juliac.jl -vae -c -t -d /tmp/build_other /tmp/other.jl &
$  julia /test/julia-1.3.0-rc3/pkg/dev/PackageCompiler/juliac.jl -vae -c -t -d /tmp/build_test  /tmp/test.jl &
$ wait
$ /tmp/build_other/other
DARA test
$ /tmp/build_test/test
DARA test
```

It looks like this is due to the wrapper source being written to a fixed location.  See compiler_flags.jl:
```
    # for better debug, let's not make a tmp file which would get lost!
    file = sysimg_folder("run_julia_code.jl")
    open(io-> println(io, code), file, "w")
```

I've worked around this by setting file path to a temp directory, and copying the resulting file to the fixed location.

**Comment by KristofferC** [comment]
This is still a problem for non-incremental builds. https://github.com/JuliaLang/PackageCompiler.jl/blob/e14fe82391cd4960b867372ecd302974c32b2945/src/PackageCompiler.jl#L128-L137.

I will fix it.
