### ISSUE TITLE
Generated executable is slow (doing JIT?)

### ISSUE THREAD

**Issue by PGS62** [JuliaLang/PackageCompiler.jl#292]
This is a [cross-post](https://stackoverflow.com/questions/58939416/how-to-eliminate-jit-overhead-in-a-julia-executable-with-mwe) from StackOverflow.

Though I can get `build_executable` to generate an exe file, that exe's performance is poor, consistent with it carrying out a JIT compilation every time it's called, despite my having used a snoop file designed to avoid that. This may be a bug (perhaps restricted to Windows?) or I may be failing correctly to use the functionality provided by PackageCompiler.

Here is my MWE:

`TestBuildExecutable.jl` contains:

```
module TestBuildExecutable

Base.@ccallable function julia_main(ARGS::Vector{String}=[""])::Cint
    @show sum(myarray())
    return 0
end

#Function which takes approx 8 seconds to compile. Returns a 500 x 20 array of 1s
function myarray()
    [1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1;
     1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1;
	 
# PLEASE EDIT TO INSERT THE MISSING 496 LINES, EACH IDENTICAL TO THE LINE ABOVE!

     1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1;
     1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
end

end #module
```

`SnoopFile.jl` contains:

```
module SnoopFile

currentpath = dirname(@__FILE__)
push!(LOAD_PATH, currentpath)
unique!(LOAD_PATH)

using TestBuildExecutable

println("Start of snoop file execution!")
TestBuildExecutable.julia_main()
println("End of snoop file execution!")

end # module
```

In a fresh Julia instance, `julia_main` takes 8.3 seconds for the first execution and half a millisecond for the second execution:

```
julia> @time TestBuildExecutable.julia_main()
sum(myarray()) = 10000
  8.355108 seconds (425.36 k allocations: 25.831 MiB, 0.06% gc time)
0

julia> @time TestBuildExecutable.julia_main()
sum(myarray()) = 10000
  0.000537 seconds (25 allocations: 82.906 KiB)
0
```

Call `build_executable`:
```
julia> using PackageCompiler

julia> build_executable("d:/philip/source/script/julia/jsource/TestBuildExecutable.jl",
                       "testexecutable",
                       builddir = "d:/temp/builddir15",
                       snoopfile = "d:/philip/source/script/julia/jsource/SnoopFile.jl",
                       verbose = false)
Julia program file:
  "d:\philip\source\script\julia\jsource\TestBuildExecutable.jl"
C program file:
  "C:\Users\Philip\.julia\packages\PackageCompiler\CJQcs\examples\program.c"
Build directory:
  "d:\temp\builddir15"
Start of snoop file execution!
sum(myarray()) = 10000
End of snoop file execution!
[ Info: used 79 out of 79 precompile statements
All done
```

Finally, in a Windows Command Prompt:
```
D:\temp\builddir15>testexecutable
sum(myarray()) = 1000

D:\temp\builddir15>
```
which took (by my stopwatch) 8 seconds to run, and it takes 8 seconds to run every time it's executed, not just the first time. This is consistent with the executable doing a JIT compile every time it's run, but the snoop file is designed to avoid that!

Version information:
```
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
  JULIA_EDITOR = "C:\Users\Philip\AppData\Local\Programs\Microsoft VS Code\Code.exe"
```

**Comment by PGS62** [comment]
Unfortunately, my guess that this problem is restricted to Windows is not correct. I have now run the MWE on MacOS and on Linux, with the same result: The generated executable is slow, consistent with it carrying out JIT compilation every time it's run.

`versioninfo()` for linux was:

```
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by KristofferC** [comment]
Please try again with the new API. If it still doesn't work, it would be useful to get a reproduces so I can figure out what is happening.

**Comment by MasonProtter** [comment]
I've got a very simple reproducer (I think) on the current master:
```
Masons-MacBook-Pro:Foo mason$ ls
Manifest.toml	Project.toml	build		build.jl	precompile.jl	src

Masons-MacBook-Pro:Foo mason$ cat src/Foo.jl
```
```julia
module Foo

fib(n::Int) = n < 2 ? n : fib(n-1) + fib(n-2)

function julia_main()::Cint
    n = isempty(ARGS) ? 30 : parse(Int, ARGS[1])
    @time @show fib(n)
    @time @show fib(n)
    return 0
end

end # module
```
```
Masons-MacBook-Pro:Foo mason$ cat precompile.jl
```
```julia
using Foo

Foo.fib(10)
Foo.fib(20)
Foo.fib(30)

Foo.julia_main()
```
```
Masons-MacBook-Pro:Foo mason$ cat build.jl
```
```julia
using PackageCompiler
create_app(".", "build", precompile_execution_file="precompile.jl", force=true)
```
```
Masons-MacBook-Pro:Foo mason$ julia --project=. build.jl
┌ Warning: it is not recommended to create an app without a preexisting manifest
└ @ PackageCompiler ~/.julia/dev/PackageCompiler/src/PackageCompiler.jl:581
[ Info: PackageCompiler: creating base system image (incremental=false)...
[ Info: PackageCompiler: creating system image object file, this might take a while...
[ Info: PackageCompiler: creating system image object file, this might take a while...

Masons-MacBook-Pro:Foo mason$ build/bin/Foo
fib(n) = 832040
  0.069413 seconds (90.83 k allocations: 4.465 MiB)
fib(n) = 832040
  0.004003 seconds (12 allocations: 384 bytes)

Masons-MacBook-Pro:Foo mason$ time build/bin/Foo
fib(n) = 832040
  0.063622 seconds (90.83 k allocations: 4.465 MiB)
fib(n) = 832040
  0.004409 seconds (12 allocations: 384 bytes)

real	0m0.315s
user	0m0.275s
sys	0m0.086s

**Comment by MasonProtter** [comment]
Here's my version info:
```julia
julia> versioninfo()
Julia Version 1.4.0-rc1.0
Commit b0c33b0cf5 (2020-01-23 17:23 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.2.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 2
```

**Comment by KristofferC** [comment]
I don't really think that is the same issue. The issue in OP was about something taking 8 seconds the first time and then being instant.

Here we are talking about something that takes 0.02 seconds the first time. I think the reason for the short first delay is that when we precompile stuff, `stdout` is not a TTY, so our statements look like

```
precompile(Tuple{typeof(Base.Printf.print_fixed), Base.PipeEndpoint, Int64, Int32, Int32, Bool, Array{UInt8, 1}})
```

When we then run the executable, we do output to a TTY so what actually ends up getting compiled is:

```
precompile(Tuple{typeof(Base.Printf.print_fixed), Base.TTY, Int64, Int32, Int32, Bool, Array{UInt8, 1}})
```

**Comment by KristofferC** [comment]
Also, a majority of startup time is spent from OpenBLAS being really slow to start up...

![Screenshot 2020-02-26 at 09 19 34](https://user-images.githubusercontent.com/1282691/75326223-86db6100-587a-11ea-9de6-cf35d77d2284.png)

You can run with `filter_stdlibs=true` to remove e.g. LinearAlgebra and stuff from the sysimage.

**Comment by KristofferC** [comment]
If I change the `read` call to `run` in 

https://github.com/JuliaLang/PackageCompiler.jl/blob/68530ef96327bd9cfb3d6ff89d7d7c63ac9ae5cc/src/PackageCompiler.jl#L170

I get the correct `IO`output and the first call is fast:

```
❯ time ./Foo
fib(n) = 832040
  0.005339 seconds (67 allocations: 4.266 KiB)
fib(n) = 832040
  0.003579 seconds (15 allocations: 432 bytes)
./Foo  0.11s user 0.05s system 81% cpu 0.193 total
```

That would print all the output from the precompiling though. I could also use the same was a Base does by creating a fake TTY (https://github.com/JuliaLang/julia/blob/0fe45ef7349b6ad25fdba7dce169f9b9efa48620/contrib/generate_precompile.jl#L82) and use that. Or I could just try to compile all methods for `PipeEndPoint` also for `TTY`. Not sure which is best...

**Comment by MasonProtter** [comment]
>If I change the `read call` to `run` in Line 170 in 68530ef PackageCompiler.jl/src/PackageCompiler.jl
> I get the correct IOtype and the first call is fast. That would print all the output from the precompiling though.

I just tried did that and indeed it's fast! No output was printed from the precompiling though. The output looked the same as before I changed `read` to `run` but I got the improved timings.

**Comment by MasonProtter** [comment]
> I don't really think that is the same issue. The issue in OP was about something taking 8 seconds the first time and then being instant.

The OP said:
> which took (by my stopwatch) 8 seconds to run, and it takes 8 seconds to run every time it's executed, not just the first time. This is consistent with the executable doing a JIT compile every time it's run, but the snoop file is designed to avoid that!

So I suspected that it was something similar where there was a precompile statement that wasn't doing what the OP intended it to do. In this case, I thought it might have to do with the machinery to parse the array, but I'm out of my depth.

**Comment by KristofferC** [comment]
Yeah, I understand it is easy to think they are related but your case is more of a small inaccuracy while the case in OP seems to be a complete absence of precompilation.

>  but maybe there's a way to filter them out?

Well, the tricky part is that e.g. using `read` is exactly filtering them out but then they are no longer printed to a TTY so the type of the `IO` is no longer representative for normal use. I'm pretty sure I could get the Fake TTY thing we use in Base to work bt it will be a bit of code and I am wondering if the code complexity is worth it.

**Comment by MasonProtter** [comment]
If we use `run`, things only get printed if the actual functions getting precompiled print, right? I think that's more or less acceptable. If someone wants to run `create_app` or whatever on a package that does a lot of printing they can alway just quiet the output. 

Maybe I should open a PR with that `read` changed to `run` and see if anyone else has feelings or suggestions?

**Comment by PGS62** [comment]
> Please try again with the new API. If it still doesn't work, it would be useful to get a reproduces so I can figure out what is happening.

I've done that and I'm happy to report that the new API works correctly against my MWE (mutated as necessary).  So I've closed this issue (since I see that @MasonProtter has opened a separate one).

**Comment by KristofferC** [comment]
Tha ks for the update!
