### ISSUE TITLE
PackageCompiler fails building MKL on Windows

### ISSUE THREAD

**Issue by aminya** [JuliaLang/PackageCompiler.jl#299]
https://github.com/JuliaComputing/MKL.jl/issues/24

CI on my V0.1 branch: 
https://travis-ci.com/aminya/MKL.jl/builds/142809478
https://ci.appveyor.com/project/andreasnoack/mkl-jl/builds/29837534

Travis on my patch-3 branch (before REPL-Startup fix) https://travis-ci.com/aminya/MKL.jl/builds/142824221

**Comment by KristofferC** [comment]
This is https://github.com/JuliaLang/julia/issues/34680 and got introduced in 1.3.1.

**Comment by KristofferC** [comment]
Going to close this since it is fixed in Julia and will be available in 1.4.
