### ISSUE TITLE
Enormous shared library

### ISSUE THREAD

**Issue by gpgjoe** [JuliaLang/PackageCompiler.jl#301]
Hi,

I've tried compiling the code below in two machines. Iin one of them the executable runs correctly and in the other it seg faults, but in both the compilation takes about 5 minutes and generates an .so file that is 150MB in size.

`libjlcompile.jl`:

    import Base
    Base.@ccallable foo()::Cint = 3

Compile with:

    $ julia $JULIA_DIR/packages/PackageCompiler/4yNnV/juliac.jl -vas libjlcompile.jl

`cpp_calling_julia.cpp`:

    #include <stdio.h>
    #include <stdlib.h>
    #include <dlfcn.h>
    int main(int argc, char **argv) {
        void *handle;
        int (*func)();
        char *error;
        handle = dlopen ("builddir/libjlcompile.so", RTLD_LAZY);
        if (!handle) {
            fprintf (stderr, "%s\n", dlerror());
            exit(1);
        }
        dlerror();    /* Clear any existing error */
        func = (int (*)()) dlsym(handle, "foo");
        if ((error = dlerror()) != NULL)  {
            fprintf (stderr, "%s\n", error);
            exit(1);
        }
        printf ("%d\n", (*func)());
        dlclose(handle);
    
        return 0;
    }

Below versioninfo() of the machine where the executable segfaults.

    julia> versioninfo()
    Julia Version 1.3.1
    Commit 2d5741174c (2019-12-30 21:36 UTC)
    Platform Info:
      OS: Linux (x86_64-pc-linux-gnu)
      CPU: Intel(R) Pentium(R) 3558U @ 1.70GHz
      WORD_SIZE: 64
      LIBM: libopenlibm
      LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

**Comment by KristofferC** [comment]
This is expected. The shared library contains all of Julia (Base, standard libraries etc).
