### ISSUE TITLE
docs link is broken

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/PackageCompiler.jl#308]
points to juliacomputing.github.io which doesn't exist.

**Comment by DilumAluthge** [comment]
The README currently links to https://juliacomputing.github.io/PackageCompiler.jl/dev, which does not exist.

However, it is worth nothing that https://julialang.github.io/PackageCompiler.jl/dev also does not exist.

**Comment by DilumAluthge** [comment]
Looking at https://github.com/JuliaLang/PackageCompiler.jl/actions, it looks like the `Documentation` workflow has been run on pull requests and on pushes to branches like `fe/no-pkgs` and `kc/packagecompilerx`, but never on pushes to the `master` branch.

**Comment by KristofferC** [comment]
Should be fixed
