### ISSUE TITLE
How to compile a driver program or a single executable with Julia 0.7

### ISSUE THREAD

**Issue by lucatrv** [JuliaLang/PackageCompiler.jl#31]
Question: I thought that `program.c` and `program2.c` in [static-julia](https://github.com/JuliaComputing/static-julia) were intended to build respectively a driver program or a single executable with Julia 0.7 (see `README.md`). I have not been able to build a single executable successfully so far, so I could not test this though. Now that the old `program.c` is gone, I wonder how it will be possible to select either one of the two outputs with Julia 0.7.

**Comment by SimonDanisch** [comment]
I did this after @vtjnash comment:

>example2.c is a better example file. I think we should just delete this [program.c] one.

I modified example2.c to work on windows with mingw and be a bit more barebone and it also works on 0.6, so I thought it's all good now... Not sure if I deleted something important in this process.

**Comment by SimonDanisch** [comment]
I removed the `#ifndef _OS_WINDOWS_` in https://github.com/JuliaLang/PackageCompiler.jl/pull/20/files after writing tests for it which failed on my windows machine and passed without it ;) I was assuming that this is what happens if you compile it with gcc installed via WinRPM, instead of compiling e.g. with visual studio. Might be, that it was actually needed for 0.7 support?

**Comment by lucatrv** [comment]
@ViralBShah @vtjnash can you please explain how creating a single large binary with Julia 0.7 works?

From [static-julia](https://github.com/JuliaComputing/static-julia) `README.md`:

> With Julia 0.7, a single large binary can be created, which does not require the driver program to load the shared library. An example of that is in program2.c, where the image file is the binary itself.

Which one of the following is true:

1. With Julia 0.7 both `program.c` and `program2.c` are needed, the former to compile a small driver program, the latter to compile a single large binary.
2. Only `program2.c` is needed, and either a small driver program or a single large binary can be compiled.
3. Only `program2.c` is needed, and Julia 0.7 always compiles to a single large binary.

**Comment by ViralBShah** [comment]
IIRC, 3. is true, or used to be true.

**Comment by lucatrv** [comment]
OK, so for now we'll move in that direction, thanks!
