### ISSUE TITLE
Travis badge is broken

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/PackageCompiler.jl#310]
Both the image and the link are broken.

**Comment by DilumAluthge** [comment]
It looks like somehow Travis got disabled on this repository?

https://travis-ci.com/JuliaLang/PackageCompiler.jl - "We couldn't find the repository
JuliaLang/PackageCompiler.jl "

https://travis-ci.org/JuliaLang/PackageCompiler.jl - The last build on the `master` branch was when #303 was merged two days ago

**Comment by DilumAluthge** [comment]
This is actually very confusing. It seems that Travis is running on PRs. For example, here is a Travis job that ran two hours ago on PR #309: https://travis-ci.org/JuliaLang/PackageCompiler.jl/builds/648695894

So why is Travis not running on `master`? https://travis-ci.org/JuliaLang/PackageCompiler.jl/branches

Can an admin go into https://travis-ci.org/JuliaLang/PackageCompiler.jl/settings and make sure that the `Build pushed branches` option is enabled?

**Comment by KristofferC** [comment]
Should be fixed, https://travis-ci.org/JuliaLang/PackageCompiler.jl show my latest commit running
