### ISSUE TITLE
ARGS type in new PackageCompilerX

### ISSUE THREAD

**Issue by prakhar2b** [JuliaLang/PackageCompiler.jl#327]
In the [toy application here](https://github.com/JuliaLang/PackageCompiler.jl/blob/master/docs/src/devdocs/binaries_part_2.md#a-toy-application), we created an app to parse CSV files.

```julia
module MyApp

using CSV

Base.@ccallable function julia_main()::Cint
    try
        real_main()
    catch
        Base.invokelatest(Base.display_error, Base.catch_stack())
        return 1
    end
    return 0
end

function real_main()
    for file in ARGS
        if !isfile(file)
            error("could not find file $file")
        end
        df = CSV.read(file)
        println(file, ": ", size(df, 1), "x", size(df, 2))
    end
end

if abspath(PROGRAM_FILE) == @__FILE__
    real_main()
end

end # module
```

Can we directly pass a DataFrame as an argument here from other languages like Python using `ctypes (with .so file)` or `PyJulia`? Also, can we use a different return type that Cint? What if I want to return a DataFrame?

What is the correct way to implement this cross-language type conversion?

**Comment by KristofferC** [comment]
> Can we directly pass a DataFrame as an argument here from other languages like Python using ctypes (with .so file) or PyJulia?

No, you can only pass C types since that is the ABI that is used. To pass arguments like DataFrames you need to convert them to something that Python understand which is a complicated process (but maybe PyCall can do it).
