### ISSUE TITLE
Travis build config is erroring

### ISSUE THREAD

**Issue by asinghvi17** [JuliaLang/PackageCompiler.jl#332]
https://travis-ci.org/JuliaLang/PackageCompiler.jl/builds/650089217/config

Looks like the `exclude:arch` section.

**Comment by KristofferC** [comment]
Well, it is running an `x86` build because I put it in `arch` and at the same time it complains about not knowing what `x86` is in `arch`... Seems like a Travis problem. Everything runs as it should on Travis at least.
