### ISSUE TITLE
compiling a new sysimg should use vanilla sysimg as base 

### ISSUE THREAD

**Issue by TsurHerman** [JuliaLang/PackageCompiler.jl#34]
If I am not wrong, from the look of the precompile lists , it seems to me that
if I build a package into the sysimg and then at a later date update that package and therefore would like to build the package again into the sysimg.. well since the previous sysimg gets loaded into the new snooping process , the end result is a kind of cumulative compilation .. which is not what I intended

**Comment by SimonDanisch** [comment]
I think you're right... I'll take a look at it!

**Comment by TsurHerman** [comment]
I am sorry for the waterfall of issues, I find this package extremely important , but I cannot propagate it to my colleagues if it does not work out of the box
