### ISSUE TITLE
djuliac error while creating executable with PackageCompilerX

### ISSUE THREAD

**Issue by prakhar2b** [JuliaLang/PackageCompiler.jl#348]
```bash
 gcc -DJULIAC_PROGRAM_LIBNAME=\"sys.so\" -o MyApp MyApp.c sys.so -O2 -fPIE \
    -I'/home/kc/julia/include/julia' \
    -L'/home/kc/julia/lib' \
    -ljulia \
    -Wl,-rpath,'/home/kc/julia/lib:$ORIGIN'
```
Error -

```
fatal error: uv.h: No such file or directory
 #include "uv.h"
          ^~~~~~
compilation terminated.
```

In the older version, we would use `juliac.c` to create executable. 

Please clarify this line - `DJULIAC_PROGRAM_LIBNAME=\"sys.so\"`
Are we supposed to provide location of PackageCompilerX as we would do for juliac.c earlier?

**Comment by KristofferC** [comment]
I guess you are using the manual method as shown in https://julialang.github.io/PackageCompiler.jl/dev/devdocs/binaries_part_2/? This is to get an understanding of how PackageCompiler.jl works under the hood but if you just want to create a binary, read https://julialang.github.io/PackageCompiler.jl/dev/apps/.

What is the actual command you use and how did you install Julia? `uv.h` should come included with `julia` and be in the `include/julia` directory.

> Please clarify this line - DJULIAC_PROGRAM_LIBNAME=\"sys.so\"
> Are we supposed to provide location of PackageCompilerX as we would do for juliac.c earlier?

It is just a path to the sysimage, in this case `sys.so`.

**Comment by prakhar2b** [comment]
Thanks. It worked.

I have another question regarding return type and arguments -
```Julia
Base.@ccallable function julia_main()::Cint
    try
        real_main()
    catch
        Base.invokelatest(Base.display_error, Base.catch_stack())
        return 1
    end
    return 0
end
```
1. Can we have another return type than `Cint`? What if I want to call a function using shared library and return a `dataframe`? Can we do that?

2. for a `ccallable` function, what should be the argument datatype for a dataframe if we want to call that function using shared library from Python? Do we need type conversion using ctypes or can we do it without that (maybe using PyJulia)?

Thank you.

**Comment by KristofferC** [comment]
The `julia_main` is what the executable returns to the C `main` function and needs to be an Int. For passing things like dataframe you need to use something like PyCall.
