### ISSUE TITLE
package compiler ,should it compile functions involving Anonymous functions?

### ISSUE THREAD

**Issue by TsurHerman** [JuliaLang/PackageCompiler.jl#35]
I see many lines in precompile.jl containing Symbols for example:
`precompile(Tuple{getfield(Main, Symbol("##1#2"))})`

Do they need to be included? since they represent compilation of something that is only relevant for
the current session.

**Comment by SimonDanisch** [comment]
The names should be stable... I only found one occurance, where the names we'rent stable, due to a macro that basically used random strings for the function names. That's why I wrap the precompile statements into a try catch - maybe I should also add some code that warns you about errors...

**Comment by TsurHerman** [comment]
Thanks for clarifying
