### ISSUE TITLE
Dynamic Linking for shared library in PackageCompilerX

### ISSUE THREAD

**Issue by prakhar2b** [JuliaLang/PackageCompiler.jl#350]
In the new PackageCompilerX, we build a relocatable executable by copying julia library files in the same folder as executable and dynamically link it with that using `rpath` and  `$ORIGIN`

```Bash
gcc -DJULIAC_PROGRAM_LIBNAME=\"sys.so\" -o MyApp MyApp.c sys.so -O2 -I'/home/kc/julia/include/julia' -L'/home/kc/julia/lib' -fpie -Wl,-rpath,'$ORIGIN:$ORIGIN/../lib' -ljulia
```

However, the shared library `sys.so` that we created is still linked with local julia installation, and can't be loaded (using `ctypes.CDLL` in Python).

We can solve that by using same workaround for sysimage linking that we did for executable.

```Bash
gcc -shared -o sys.so -Wl,--whole-archive sys.o -Wl,--no-whole-archive -L"/home/kc/julia/lib" -fpie -Wl,-rpath,'$ORIGIN:$ORIGIN/../lib'  -ljulia
```

However, we still can't use it until we initialize the julia runtime  before calling any ccallable function. In earlier version of PackageCompiler, we would have `lib_init.c`for that. Should we not have something like that here as well?

**Comment by KristofferC** [comment]
Yes, we should probably add an argument to `create_sysimage` that adds these init and exit runtime functions to it.

**Comment by KristofferC** [comment]
I tried with the old packagecompiler with `ctypes.CDLL` and it didn't really work:

```
❯ python 

Python 2.7.16 (default, Dec 13 2019, 18:00:32) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import *

>>> lib = CDLL("Users/kc/PackageCompiler.jl/builddir/foo.dylib")

>>> lib.init_jl_runtime()
ERROR: could not load library "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/foo.dylib"
dlopen(/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/foo.dylib, 6): image not found
```

Does it need a full path?

**Comment by prakhar2b** [comment]
```Python
dll = ctypes.CDLL("builddir/test.so", ctypes.RTLD_GLOBAL)

jl_init = dll.init_jl_runtime
```

This would work with old package compiler

**Comment by prakhar2b** [comment]
Is there any update on it?

**Comment by kmsquire** [comment]
Bumping this, as this is something we would like to explore.  I assume no on has worked on this recently.  I'll try to explore with the information above, but are there any pull requests or other modifications that have already been attempted?  Any hints on necessary changes, beyond what is written above?

**Comment by KristofferC** [comment]
https://github.com/simonbyrne/libcg is a pretty nice example.

**Comment by kmsquire** [comment]
That's perfect--thank you!

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/PackageCompiler.jl/pull/490
