### ISSUE TITLE
using custom sysimage with PyJulia

### ISSUE THREAD

**Issue by prakhar2b** [JuliaLang/PackageCompiler.jl#351]
Can we use PackageCompilerX to create sysimage that we can use as a runtime for PyJulia.

Reference - https://pyjulia.readthedocs.io/en/latest/sysimage.html

It would be great if someone could get this to work.

**Comment by KristofferC** [comment]
That seems up to the PyJulia project if they want to change to using the new version of PackageCompiler (AFAIU they are using 0.6.5 now). If the API from PackageCompiler is lacking, we can add to it.
