### ISSUE TITLE
create_app() Not Defined.

### ISSUE THREAD

**Issue by ChandlerKilpatrick1** [JuliaLang/PackageCompiler.jl#355]
Hey there,
Heres the issue I'm running into:
```jl
julia> PackageCompiler.create_app("name", "name_compiled")
ERROR: UndefVarError: create_app not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:13
 [2] top-level scope at none:0

julia> create_app("name", "name_compiled")
ERROR: UndefVarError: create_app not defined
Stacktrace:
 [1] top-level scope at none:0

julia> create_app()
ERROR: UndefVarError: create_app not defined
Stacktrace:
 [1] top-level scope at none:0
```
What am I missing here?

Version info:
```jl
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.0.0)
  CPU: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 2

```

**Comment by KristofferC** [comment]
I'm guessing you don'thave version 1.0 of the package.

**Comment by ChandlerKilpatrick1** [comment]
Hey, originally I added PackageCompiler using the package manager. When that didn't work, I removed it and re-added it with PackageCompiler#master but that did not fix the error. 

[9b87118b] PackageCompiler v1.0.1 #master (https://github.com/JuliaLang/PackageCompiler.jl.git)

**Comment by KristofferC** [comment]
You might have the old package manager in y our sysimage or something then. Try reinstall Julia. The function really does exist heh.

**Comment by logankilpatrick** [comment]
Hey @KristofferC what does the "old package manager" mean? I am running 1.3.1 and this is the first time I have ever heard that there's a different package manager I need to be on.

**Comment by KristofferC** [comment]
I meant old PackageCompiler.

**Comment by logankilpatrick** [comment]
I just did a fresh install of Julia 1.3.1 and got: 

```
julia> using PackageCompiler
[ Info: Precompiling PackageCompiler [9b87118b-4619-50d2-8e1e-99f35a4d4d9d]

julia> create_app("name", "name_compiled")
ERROR: UndefVarError: create_app not defined
Stacktrace:
 [1] top-level scope at REPL[6]:1

julia> PackageCompiler.create_app("name", "name_compiled")
ERROR: UndefVarError: create_app not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:13
 [2] top-level scope at REPL[7]:1
```

**Comment by logankilpatrick** [comment]
However, it is working with my 1.4 rc1 install.

**Comment by KristofferC** [comment]
Here is the package being tested on 1.3.1: https://travis-ci.org/github/JuliaLang/PackageCompiler.jl/jobs/659647637.

Here is the function:

https://github.com/JuliaLang/PackageCompiler.jl/blob/aa58b9977b96aad7df6b971a51370713e1887fb4/src/PackageCompiler.jl#L577

This shouldn't be too hard to debug, what does

```
 names(PackageCompiler)
```

say?

**Comment by logankilpatrick** [comment]
It figured it out, Thanks for the tips!

**Comment by KristofferC** [comment]
So what was it?

**Comment by daniel-beard** [comment]
I also have this issue, @logankilpatrick how did you fix this?

**Comment by logankilpatrick** [comment]
First thing is you have to be on Julia 1.3.1, and then after I installed 1.3.1 is auto used my 1.3.0 environment so it still had the old version of Package Compiler (0.6.4). 

I just removed package compiler and then re-added it. It added versions 1.1.0 and then “create_app” was defined.

**Comment by daniel-beard** [comment]
Thanks, this worked for me.
