### ISSUE TITLE
Relocatability warnings on dependent packages

### ISSUE THREAD

**Issue by jipq6175** [JuliaLang/PackageCompiler.jl#357]
Hi, I am trying to building an app using PackageCompiler. 

I have a package that depends on a few other packages, including Plots and PyCall. I encountered the following warnings when `create_app`
```
julia> @time create_app("MyPackage", "MyPackageCompiled"; force=true)
┌ Warning: Project has a dependency on Requires.jl, code in `@require` will not be run
└ @ PackageCompiler C:\Users\x\.julia\packages\PackageCompiler\fZ95H\src\PackageCompiler.jl:498
┌ Warning: Plots has a dependency on Requires.jl, code in `@require` will not be run
└ @ PackageCompiler C:\Users\x\.julia\packages\PackageCompiler\fZ95H\src\PackageCompiler.jl:502
┌ Warning: PlotThemes has a dependency on Requires.jl, code in `@require` will not be run
└ @ PackageCompiler C:\Users\x\.julia\packages\PackageCompiler\fZ95H\src\PackageCompiler.jl:502
┌ Warning: Package Plots has a build script, this might indicate that it is not relocatable
└ @ PackageCompiler C:\Users\x\.julia\packages\PackageCompiler\fZ95H\src\PackageCompiler.jl:515
┌ Warning: Package GR has a build script, this might indicate that it is not relocatable
└ @ PackageCompiler C:\Users\x\.julia\packages\PackageCompiler\fZ95H\src\PackageCompiler.jl:515
┌ Warning: Package PyCall has a build script, this might indicate that it is not relocatable
└ @ PackageCompiler C:\Users\x\.julia\packages\PackageCompiler\fZ95H\src\PackageCompiler.jl:515
┌ Warning: Package Conda has a build script, this might indicate that it is not relocatable
└ @ PackageCompiler C:\Users\x\.julia\packages\PackageCompiler\fZ95H\src\PackageCompiler.jl:515
...
```

The executable was built successfully and can be run on my Windows machine. But it failed to run on the other Windows machine. It's the package relocatability issue. After some googling, I think I have to use Artifacts.toml to work around this issue. I read through the Pkg.jl manual and the blog post (https://julialang.org/blog/2019/11/artifacts/) but still have no idea how to do this exactly. Is there an example for dealing with those "un-relocatable" packages? Or am I missing anything? Thanks

Here is the julia `versioninfo()` 
```
Julia Version 1.5.0-DEV.270
Commit 66ecd90bd6 (2020-02-13 21:49 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by KristofferC** [comment]
The packages themselves have to be "fixed". They are simply incompatible with being compiled since they assume source files are available at runtime.

**Comment by jipq6175** [comment]
Thank you

**Comment by nbakas** [comment]
Hello, I have the same problem.

when you say _have to be "fixed"_ what do you mean?

thanks in advance.

**Comment by KristofferC** [comment]
I mean that they, for example, have to use the artifact system instead of downloading files in their build script.

**Comment by nbakas** [comment]
KristofferC, thank you very much for your prompt reply.

Indeed, I see that the packages I use, does not have a file Artifacts.toml in C:\Users\~\.juliapro\JuliaPro_v1.4.1-1\packages\~\

an example is with Plots package.

If you could indicate a URL with more info or some instructions on how practically I could do this (e.g. with Plots) it would be nice.

Thanks a lot!
