### ISSUE TITLE
Moving the compiled App to a different computer, got an error trying to run artifact

### ISSUE THREAD

**Issue by dylimennew** [JuliaLang/PackageCompiler.jl#362]
Hi, I compiled the MyApp successfully (by calling create_app("MyApp", "MyAppCompiled")), but when moving the compiled app (the entire MyAppCompiled directory) to a different computer and trying to run MyApp.exe, I got an error at the running artifact step:

Running the artifact
ERROR: IOError: could not spawn `'C:\users\books\.julia\artifacts\d61f806c76b57e54f343634c5219d00d4c81b077\bin\fooifier.exe' 5 10`: no such file or directory (ENOENT)

The directory cited above is the one I have on the original machine where the compilation was done. I believe it should have referenced the MyAppCompiled\artifact\ directory instead.

I went ahead and created the same directory with the fooifier artifact, and it worked. 

Can you please check to see if this is a bug?

Thanks,
D

**Comment by KristofferC** [comment]
What is the output until it crashes?

Do you have any environment variables set at the other machine?

**Comment by dylimennew** [comment]
The output before is:

`C:\Users\ENNew\Desktop\MyAppCompiled\bin>myapp
ARGS = String[]
Base.PROGRAM_FILE = "myapp"
DEPOT_PATH = ["C:\\Users\\ENNew\\Desktop\\MyAppCompiled\\bin\\MyApp.exe/../../"]
LOAD_PATH = ["@"]
pwd() = "C:\\Users\\ENNew\\Desktop\\MyAppCompiled\\bin"
Base.active_project() = nothing
Threads.nthreads() = 1
Sys.BINDIR = "C:\\Users\\ENNew\\Desktop\\MyAppCompiled\\bin"
Dict{Base.PkgId,Module} with 35 entries:
  Logging [56ddb016-857b-54e1-b83d-db4d58db5568] => Logging
  InteractiveUtils [b77e0a4c-d291-57a0-90e8-8db25a27a240] => InteractiveUtils
  Base64 [2a0f44e3-6c83-55bd-87e4-b1978d98bd5f] => Base64
  Statistics [10745b16-79ce-11e8-11f9-7d13ad32a3b2] => Statistics
  Test [8dfed614-e22c-5e08-85e1-65c5234f0b40] => Test
  HelloWorldC_jll [dca1746e-5efc-54fc-8249-22745bc95a49] => HelloWorldC_jll
  SHA [ea8e919c-243c-51af-8825-aaa63cd721ce] => SHA
  Profile [9abbd945-dff8-562f-b5e8-e1ebf5ef1b79] => Profile
  Example [7876af07-990d-54b4-ab0e-23690620f79a] => Example
  Base [top-level] => Base
  SharedArrays [1a1011a3-84de-559e-8e89-a11a2f7dc383] => SharedArrays
  Markdown [d6f4376e-aef5-505a-96c1-9c027394607a] => Markdown
  LibGit2 [76f85450-5226-5b5a-8eaa-529ad045b433] => LibGit2
  Core [top-level] => Core
  SparseArrays [2f01184e-e22b-5df5-ae63-d93ebab69eaf] => SparseArrays
  Dates [ade2ca70-3891-5945-98fb-dc099432e06a] => Dates
  Unicode [4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5] => Unicode
  UUIDs [cf7118a7-6976-5b1a-9a39-7adc72f591a4] => UUIDs
  FileWatching [7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee] => FileWatching
  SuiteSparse [4607b0f0-06f3-5cda-b6b1-a6196a1729e9] => SuiteSparse
  Main [top-level] => Main
  Sockets [6462fe0b-24de-5631-8697-dd941f90decc] => Sockets
  LinearAlgebra [37e2e46d-f89d-539d-b4ee-838fcccc9c8e] => LinearAlgebra
  Pkg [44cfe95a-1eb2-52ea-b672-e2afdf69b78f] => Pkg
  CRC32c [8bf52ea8-c179-5cab-976a-9e18b702a9bc] => CRC32c
  Serialization [9e88b42a-f829-5b0c-bbe9-9e923198166b] => Serialization
  Libdl [8f399da3-3557-5675-b5ff-fb832c97cbdb] => Libdl
  REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb] => REPL
  Mmap [a63ad114-7e13-5084-954f-fe012c677804] => Mmap
  DelimitedFiles [8bb1440f-4735-579b-a4ab-409b98df4dab] => DelimitedFiles
  MyApp [f943f3d7-887a-4ed5-b0c0-a1d6899aa8f5] => MyApp
  Random [9a3f8284-a2c9-5f02-9a11-845980a1fd5c] => Random
  Future [9fa8497b-333b-5362-9e8d-4d0656e87820] => Future
  Printf [de0858da-6303-5e67-8744-51eddeeeb8d7] => Printf
  Distributed [8ba89e20-285c-5b6f-9357-94700520ee1b] => DistributedRunning a jll package:
HelloWorld artifact at C:\Users\ENNew\Desktop\MyAppCompiled\artifacts\c61e806c76b57e54f343634c5219d00d4c81b077\bin\hello_world.exe
Hello, World!

Running the artifact`

The cmd line was started using admin privileges, and the path is:

`C:\Users\ENNew\Desktop\MyAppCompiled\bin>path
PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\IBM\ILOG\CPLEX_Studio1210\opl\bin\x64_win64;C:\Program Files\IBM\ILOG\CPLEX_Studio1210\opl\oplide\;C:\Program Files\IBM\ILOG\CPLEX_Studio1210\cplex\bin\x64_win64;C:\Program Files\IBM\ILOG\CPLEX_Studio1210\cpoptimizer\bin\x64_win64;C:\Users\ENNew\AppData\Local\Julia-1.3.1\bin;C:\Users\ENNew\AppData\Local\Microsoft\WindowsApps
`

**Comment by KristofferC** [comment]
Thanks, it is not a bug in PackageCompiler but a bug in the example app. I will update it to make it do things correctly.

**Comment by dylimennew** [comment]
Thanks @KristofferC!!

**Comment by KristofferC** [comment]
Can you try with https://github.com/JuliaLang/PackageCompiler.jl/issues/362?

**Comment by dylimennew** [comment]
Thanks, trying https://github.com/JuliaLang/PackageCompiler.jl/pull/363 now...

**Comment by KristofferC** [comment]
Yeah #363 I meant

**Comment by dylimennew** [comment]
Yes, it works now, thanks @KristofferC! Why isn't the ensure_artifact_installed sufficient? It didn't even give any errors. Is it because the const makes the path fixed at compilation, whereas we need it to load and find the artifact each time?

**Comment by KristofferC** [comment]
> Is it because the const makes the path fixed at compilation, whereas we need it to load and find the artifact each time?

Yes
