### ISSUE TITLE
Cannot build when there are unreadable files in `julia_libdir()`

### ISSUE THREAD

**Issue by alhirzel** [JuliaLang/PackageCompiler.jl#368]
https://github.com/JuliaLang/PackageCompiler.jl/blob/aa58b9977b96aad7df6b971a51370713e1887fb4/src/PackageCompiler.jl#L678

When using the Arch Linux package for Julia, this `cp` operation fails when there are files that are not user-readable within `/usr/lib` (which is the value returned by `julia_libdir()` when using the Arch Linux package for Julia).

Also, it seems like copying all of `/usr/lib` for this case is a bit excessive, though I realize that I should not be using the distro's version of Julia for this.

**Comment by KristofferC** [comment]
Yeah, I didn't realize that's where the libdir is for distros. However, it's unclear to me if the generated app will work well with the libraries provided by the distro.

**Comment by KristofferC** [comment]
Closing because it is documented that the official installation should be used.
