### ISSUE TITLE
julia_main() threw an unhandled exception

### ISSUE THREAD

**Issue by ChandlerKilpatrick1** [JuliaLang/PackageCompiler.jl#371]
Hey everyone,

I'm having issues running the code after it is compiled. I am able to create the compiled file without any error messages but when I try to run the file, it errors: 

`julia_main() threw an unhandled exception`

I tried to do the audit and it gave me a ton of warnings that the packages I'm using as dependancies have build scripts. Is there a way to compile the code into an app even though those packages have warning's associated with them?

Also, side question, will the app work as expected if the code in my "function julia_main()::Cint" depends on some packages which I bring in by doing "using x, y, x" at the top of the file?

Something like: 

```jl
using x
import y, z

function julia_main()::Cint
    y.name_of_func()
    return 0
end
```

**Comment by KristofferC** [comment]
Structure your code as https://github.com/JuliaLang/PackageCompiler.jl/blob/aa58b9977b96aad7df6b971a51370713e1887fb4/examples/MyApp/src/MyApp.jl#L9-L17 to get a backtrace.

>  Is there a way to compile the code into an app even though those packages have warning's associated with them?

It depends what the build script does. In general, no,
