### ISSUE TITLE
Compiling fails on 1.5, while working on 1.4.0 but is very slow

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/PackageCompiler.jl#375]
I'll first start with the error on 1.5, then below for 1.4.0, that proceeded:

```
julia> create_app("fasta", "fastaAppCompiled", force=true)
┌ Warning: it is not recommended to create an app without a preexisting manifest
└ @ PackageCompiler ~/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:592
ERROR: MethodError: no method matching source_path(::Pkg.Types.Context, ::Pkg.Types.PackageSpec)
Stacktrace:
 [1] source_path(::Pkg.Types.Context, ::Pkg.Types.PackageSpec) at /home/pharaldsson_sym/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:49
 [2] bundle_artifacts(::Pkg.Types.Context, ::String) at /home/pharaldsson_sym/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:699
 [3] create_app(::String, ::String; app_name::Nothing, precompile_execution_file::Array{String,1}, precompile_statements_file::Array{String,1}, incremental::Bool, filter_stdlibs::Bool, audit::Bool, force::Bool, cpu_target::String) at /home/pharaldsson_sym/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:615
 [4] top-level scope at REPL[3]:1
```

[EDIT: outdated here below, about failing on 1.4 or earlier, was my mistake i seems, while slowness persists, see other comments below.]

As the benchmark https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/fasta-julia-6.html

ran faster from the REPL, I was trying PackageCompiler for the first time:

```
julia> create_app("fasta", "fastaAppCompiled", force=true)
┌ Warning: it is not recommended to create an app without a preexisting manifest
└ @ PackageCompiler ~/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:592
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Updating `~/fasta/Project.toml`
 [no changes]
   Updating `~/fasta/Manifest.toml`
 [no changes]
[ Info: PackageCompiler: creating base system image (incremental=false)...


[ Info: PackageCompiler: creating system image object file, this might take a while...


WARNING: eval into closed module __toplevel__:
Expr(:function, Expr(:call, :iub, :x), Expr(:block, #= Symbol("/home/pharaldsson_sym/fasta/src/fasta.jl"):45 =#, Expr(:&&, Expr(:call, :<=, :x, 0x0000939f), Expr(:return, 0x61)), Expr(:&&, Expr(:call, :<=, :x, 0x0000d53b), Expr(:return, 0x63)), Expr(:&&, Expr(:call, :<=, :x, 0x000116d7), Expr(:return, 0x67)), Expr(:&&, Expr(:call, :<=, :x, 0x0001aa77), Expr(:return, 0x74)), Expr(:&&, Expr(:call, :<=, :x, 0x0001b566), Expr(:return, 0x42)), Expr(:&&, Expr(:call, :<=, :x, 0x0001c055), Expr(:return, 0x44)), Expr(:&&, Expr(:call, :<=, :x, 0x0001cb45), Expr(:return, 0x48)), Expr(:&&, Expr(:call, :<=, :x, 0x0001d634), Expr(:return, 0x4b)), Expr(:&&, Expr(:call, :<=, :x, 0x0001e123), Expr(:return, 0x4d)), Expr(:&&, Expr(:call, :<=, :x, 0x0001ec13), Expr(:return, 0x4e)), Expr(:&&, Expr(:call, :<=, :x, 0x0001f702), Expr(:return, 0x52)), Expr(:&&, Expr(:call, :<=, :x, 0x000201f1), Expr(:return, 0x53)), Expr(:&&, Expr(:call, :<=, :x, 0x00020ce1), Expr(:return, 0x56)), Expr(:&&, Expr(:call, :<=, :x, 0x000217d0), Expr(:return, 0x57)), Expr(:&&, Expr(:call, :<=, :x, 0x000222c0), Expr(:return, 0x59)), #= Symbol("/home/pharaldsson_sym/fasta/src/fasta.jl"):46 =#, Expr(:call, :%, Char(0x61000000), :UInt8)))
  ** incremental compilation may be fatally broken for this module **

WARNING: eval into closed module __toplevel__:
Expr(:function, Expr(:call, :homosapiens, :x), Expr(:block, #= Symbol("/home/pharaldsson_sym/fasta/src/fasta.jl"):45 =#, Expr(:&&, Expr(:call, :<=, :x, 0x0000a5a3), Expr(:return, 0x61)), Expr(:&&, Expr(:call, :<=, :x, 0x000111e4), Expr(:return, 0x63)), Expr(:&&, Expr(:call, :<=, :x, 0x00017de6), Expr(:return, 0x67)), Expr(:&&, Expr(:call, :<=, :x, 0x000222c0), Expr(:return, 0x74)), #= Symbol("/home/pharaldsson_sym/fasta/src/fasta.jl"):46 =#, Expr(:call, :%, Char(0x61000000), :UInt8)))
  ** incremental compilation may be fatally broken for this module **

WARNING: --output requested, but no modules defined during run
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for fasta [abf3cb15-679c-451d-9bf6-3b22b2182c4b]
│   exception = ArgumentError: Invalid header in cache file /home/pharaldsson_sym/.julia/compiled/v1.4/fasta/wIPkC_VJQou.ji.
└ @ Base loading.jl:1041
ERROR: KeyError: key fasta [abf3cb15-679c-451d-9bf6-3b22b2182c4b] not found
Stacktrace:
 [1] getindex at ./dict.jl:477 [inlined]
 [2] root_module at ./loading.jl:967 [inlined]
 [3] require(::Base.PkgId) at ./loading.jl:933
 [4] require(::Module, ::Symbol) at ./loading.jl:922
ERROR: failed process: Process(`/home/pharaldsson_sym/julia-1.4.0/bin/julia --color=yes --startup-file=no --sysimage=/tmp/jl_WMPEK2/tmp_sys.so --project=/home/pharaldsson_sym/fasta -e 'using fasta'`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error at ./process.jl:525 [inlined]
 [2] read(::Cmd) at ./process.jl:412
 [3] read(::Cmd, ::Type{String}) at ./process.jl:421
 [4] do_ensurecompiled(::String, ::Array{String,1}, ::String) at /home/pharaldsson_sym/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:186
 [5] create_sysimg_object_file(::String, ::Array{String,1}; project::String, base_sysimage::String, precompile_execution_file::Array{String,1}, precompile_statements_file::Array{String,1}, cpu_target::String, script::Nothing, isapp::Bool) at /home/pharaldsson_sym/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:246
 [6] create_sysimage(::Symbol; sysimage_path::String, project::String, precompile_execution_file::Array{String,1}, precompile_statements_file::Array{String,1}, incremental::Bool, filter_stdlibs::Bool, replace_default::Bool, cpu_target::String, script::Nothing, base_sysimage::String, isapp::Bool) at /home/pharaldsson_sym/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:423
 [7] (::PackageCompiler.var"#7#8"{Bool,Bool,String,String,String})() at /home/pharaldsson_sym/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:631
 [8] cd(::PackageCompiler.var"#7#8"{Bool,Bool,String,String,String}, ::String) at ./file.jl:104
 [9] create_app(::String, ::String; app_name::Nothing, precompile_execution_file::Array{String,1}, precompile_statements_file::Array{String,1}, incremental::Bool, filter_stdlibs::Bool, audit::Bool, force::Bool, cpu_target::String) at /home/pharaldsson_sym/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:620
 [10] top-level scope at REPL[5]:1
```

I ran strace on a julia process, and I'm sure if was related to above, then in exited and the next one got me (at first only the "x32" line that was surprising to me):

strace: [ Process PID=19893 runs in x32 mode. ]
strace: [ Process PID=19893 runs in 64 bit mode. ]
brk(0x295cf000)                         = 0x295cf000
brk(0x295f0000)                         = 0x295f0000
brk(0x29611000)                         = 0x29611000
brk(0x29634000)                         = 0x29634000

..

brk(0x61e5c000)                         = 0x61e5c000
brk(0x6365c000)                         = 0x6365c000
brk(0x64e5c000)                         = 0x64e5c000
mmap(NULL, 33820672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efe9c734000
mremap(0x7efe9c734000, 33820672, 67637248, MREMAP_MAYMOVE) = 0x7efe8ab79000
brk(0x61610000)                         = 0x61610000
mmap(NULL, 59133952, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efe77a87000
mmap(NULL, 89333760, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efe72555000
mremap(0x7efe8ab79000, 67637248, 135270400, MREMAP_MAYMOVE) = 0x7efe6a454000
munmap(0x7efe72555000, 89333760)        = 0
mmap(NULL, 89333760, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efe896c8000
openat(AT_FDCWD, "/dev/urandom", O_RDONLY) = 17
read(17, "\301\215.P", 4)               = 4
close(17)                               = 0
openat(AT_FDCWD, "/tmp/jl_PaNWnd.o.temp-archive-98c6b29.a", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0666) = 17
sigaltstack(NULL, {ss_sp=0x7efebba18000, ss_flags=0, ss_size=8388592}) = 0
rt_sigaction(SIGHUP, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=0x7efec1b95ae0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7efec1471890}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=SIG_IGN, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7efec10acf20}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGUSR1, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=0x7efec1b95cb0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7efec1471890}, 8) = 0
rt_sigaction(SIGUSR2, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=0x7efec1b95f10, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x7efec1471890}, 8) = 0
rt_sigaction(SIGILL, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=0x7efec1b95cb0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7efec1471890}, 8) = 0
rt_sigaction(SIGTRAP, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=SIG_IGN, sa_mask=[TRAP], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7efec10acf20}, 8) = 0
rt_sigaction(SIGABRT, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=0x7efec1b95cb0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7efec1471890}, 8) = 0
rt_sigaction(SIGFPE, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=0x7efec1b95be0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7efec1471890}, 8) = 0
rt_sigaction(SIGBUS, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=0x7efec1b962a0, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_SIGINFO, sa_restorer=0x7efec1471890}, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=0x7efec1b962a0, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_SIGINFO, sa_restorer=0x7efec1471890}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGSYS, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=0x7efec1b95cb0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7efec1471890}, 8) = 0
rt_sigaction(SIGXCPU, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGXFSZ, {sa_handler=0x7efebe5b3e90, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_NODEFER|SA_RESETHAND, sa_restorer=0x7efec1471890}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
lseek(17, 0, SEEK_CUR)                  = 0
fstat(17, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(17, "!<arch>\n/               0       "..., 4096) = 4096
write(17, "_CLK_TCK_4601\0ccall_jl_alignment"..., 16384) = 16384
write(17, "got\0jlplt_jl_uv_req_data_3857_go"..., 4096) = 4096
write(17, "\211\6H\213\r\0\0\0\0H\211\1H\211\337H\203\304\10[A^\377\340f.\17\37\204\0\0\0"..., 59125760) = 59125760
write(17, "2300\0+Main.Core.Tuple12300\0jfptr"..., 4096) = 4096
write(17, "\260\1\0\0\0\0\0\0\20\0\0\0\0\0\0\0\260:\0\0\0\0\0\0\360\235@\3\0\0\0\0"..., 89329664) = 89329664
write(17, "\360\266\37\3\1\0\0\0\260\276\37\3\1\0\0\0\220\304\37\3\1\0\0\0\20\316\37\3\1\0\0\0"..., 1024) = 1024
rename("/tmp/jl_PaNWnd.o.temp-archive-98c6b29.a", "/tmp/jl_PaNWnd.o") = 0
close(17)                               = 0
munmap(0x7efe77a87000, 59133952)        = 0
munmap(0x7efe896c8000, 89333760)        = 0
munmap(0x7efe6a454000, 135270400)       = 0
brk(0x54a4e000)                         = 0x54a4e000
futex(0x1cfbbd18, FUTEX_WAKE_PRIVATE, 2147483647) = 0
pwrite64(16, "\24\0\0\0\0\0\0\0\1zR\0\1x\20\1\34\f\7\10\220\1\0\0004\0\0\0\34\0\0\0"..., 116, 139632353211200) = 116
pwrite64(16, "UH\211\345AWAVAUATSH\201\354H\1\0\0\17W\300\17)E\240\17)E\220H"..., 732, 139632049712064) = 732
futex(0x1f22c68, FUTEX_WAKE_PRIVATE, 2147483647) = 0
pwrite64(16, "\350\3\0\0\350\3\0\0", 8, 139632353211316) = 8
pwrite64(16, "\24\0\0\0\0\0\0\0\1zR\0\1x\20\1\34\f\7\10\220\1\0\0\34\0\0\0\34\0\0\0"..., 548, 139632353211328) = 548
pwrite64(16, "PH\270\360\363\270\236\376~\0\0\277\1\0\0\0\377\320X\303f.\17\37\204\0\0\0\0\0f\220"..., 4450, 139632049712800) = 4450
futex(0x3a326f8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
pwrite64(16, "\24\0\0\0\0\0\0\0\1zR\0\1x\20\1\34\f\7\10\220\1\0\0004\0\0\0\34\0\0\0"..., 516, 139632353211880) = 516
pwrite64(16, "SH\203\354\20H\211t$\10H\213\36H\203;\0t>H\270H:\356\260\376~\0\0\377\20H"..., 2743, 139632049717264) = 2743
epoll_ctl(3, EPOLL_CTL_DEL, 15, 0x7ffd90e3c560) = -1 ENOENT (No such file or directory)
close(15)                               = 0
epoll_ctl(3, EPOLL_CTL_DEL, 13, 0x7ffd90e3c560) = -1 ENOENT (No such file or directory)
close(13)                               = 0
epoll_ctl(3, EPOLL_CTL_DEL, 10, 0x7ffd90e3c560) = -1 ENOENT (No such file or directory)
close(10)                               = 0
epoll_ctl(3, EPOLL_CTL_ADD, 6, {EPOLLIN, {u32=6, u64=6}}) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 8, {EPOLLIN, {u32=8, u64=8}}) = 0
epoll_pwait(3, [{EPOLLIN, {u32=8, u64=8}}], 1024, 0, NULL, 8) = 1
read(8, "\1\0\0\0\0\0\0\0", 1024)       = 8
close(4)                                = 0
close(5)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

**Comment by PallHaraldsson** [comment]
The program I'm compiling is slightly changed, Int32 -> UInt32, something that shouldn't matter, and then to get the compiler to work.

I should try next, had ARGS in, but doubt that was causing the error:

```
#isinteractive() || fasta(parse(Int,ARGS[1]))

function julia_main()::Cint
  fasta(parse(Int, 2000) # ARGS[1]))
  return 0 # if things finished successfully
end
```

**Comment by KristofferC** [comment]
You need to provide enough information for the error to be reproduced. The crucial missing part here is how the `fasta` directory looks.

Did you read through https://julialang.github.io/PackageCompiler.jl/dev/apps/#Creating-an-app-1 first?

**Comment by PallHaraldsson** [comment]
Yes, read the docs, and while I had success now with a minimal test file, it still take a really long time, like I guess 10 minutes (is that normal for such a small file?):

[I used also Julia 1.3.1 just in case, seems not to be about later versions not working worse (except for 1.5).]

```
module Fasta

greet() = print("Hello World!")

function julia_main()::Cint
  # do something based on ARGS?
  greet()
  return 0 # if things finished successfully
end

end # module
```

I notice strace of three Julia processes, I guess corresponding to the comments below I added:

```
julia> using PackageCompiler

julia> create_app("Fasta", "FastaAppCompiled", force=true)
┌ Warning: it is not recommended to create an app without a preexisting manifest
└ @ PackageCompiler ~/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:592
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/Fasta/Project.toml`
 [no changes]
[ Info: PackageCompiler: creating base system image (incremental=false)...

[wait minutes, I guess, after here.]

[ Info: PackageCompiler: creating system image object file, this might take a while...

[wait again minutes, I guess, after here.]

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/Fasta/Project.toml`
 [no changes]
[ Info: PackageCompiler: creating system image object file, this might take a while...

[and wait again minutes, I guess, after here.]

julia> 
pharaldsson_sym@SYMLINUX011:~$ ./FastaAppCompiled/bin/Fasta
Hello World!pharaldsson_sym@SYMLINUX011:~$



ERROR: LoadError: BoundsError: attempt to access 0-element Array{String,1} at index [1]
Stacktrace:
 [1] getindex(::Array{String,1}, ::Int64) at ./array.jl:787
 [2] top-level scope at /home/pharaldsson_sym/fasta/src/fasta.jl:136
 [3] include(::Module, ::String) at ./Base.jl:377
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:331 [inlined]
 [6] eval(::Expr) at ./client.jl:449
 [7] top-level scope at ./none:3
in expression starting at /home/pharaldsson_sym/fasta/src/fasta.jl:136
ERROR: Failed to precompile fasta [abf3cb15-679c-451d-9bf6-3b22b2182c4b] to /home/pharaldsson_sym/.julia/compiled/v1.4/fasta/wIPkC_UFDxj.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1272
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
ERROR: failed process: Process(`/home/pharaldsson_sym/julia-1.4.0/bin/julia --color=yes --startup-file=no --sysimage=/tmp/jl_YY6Nwu/tmp_sys.so --project=/home/pharaldsson_sym/fasta -e 'using fasta'`, ProcessExited(1)) [1]

**Comment by KristofferC** [comment]
Could you put up your Fasta app somewhere so I can look? The fact that it is trying to precompile some `fasta` package is really weird. Are you doing `using fasta` somewhere?

**Comment by PallHaraldsson** [comment]
I can copy the Fasta.jl file in here (or (eventually) at the Benchmark Game), but I had success compiling now.

It's minimally changed to compile from: https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/fasta-julia-6.html

Compiling is still slow (but resulting binary code a little faster).

Now compiling is only 160 sec (w/incremental) vs 502 secbefore. You may keep this issue open if that is surprising.

You could close the issue, as compiling no longer fails for me (I still need to confirm with the full program with non-incremental). I was learning the compiler, and making a package for the first time. Thanks for making it (and implementing the fasta program).

My mistake was I guess missing out on wrapping the code in a module or having the wrong case for it (as explained in the previous comment here, that I edited).


Speed(up) results:

pharaldsson_sym@SYMLINUX011:~$ export JULIA_NUM_THREADS=4
pharaldsson_sym@SYMLINUX011:~$ time FastaAppCompiled/bin/Fasta 25000000 >/dev/null

real	0m1.730s
user	0m5.651s
sys	0m0.589s

[My 16 (virtual) core is a little loaded, about 1.38-1.9, because of Firefox.]

Compared to (the C code I compiled):

pharaldsson_sym@SYMLINUX011:~$ time ./fasta.gcc-7.gcc_run 25000000 >/dev/null

real	0m1.177s
user	0m4.539s
sys	0m0.008s

pharaldsson_sym@SYMLINUX011:~$ export JULIA_NUM_THREADS=1
pharaldsson_sym@SYMLINUX011:~$ time FastaAppCompiled/bin/Fasta 25000000 >/dev/null

real	0m3.918s
user	0m4.207s
sys	0m0.588s

It scales up to 4 threads, with 4 only a little slower, have not seen 5 give any speedup, while I do recll if being once a bit faster in the REPL version, vs. 4, meaning both slower than above.

In the REPL:

pharaldsson_sym@SYMLINUX011:~$ export JULIA_NUM_THREADS=4
pharaldsson_sym@SYMLINUX011:~$ time ~/julia-1.3.1/bin/julia fasta.jl 25000000 >/dev/null

real	0m2.074s
user	0m5.877s
sys	0m0.722s

Julia 1.4 is a least not faster:
pharaldsson_sym@SYMLINUX011:~$ time ~/julia-1.4.0/bin/julia fasta.jl 25000000 >/dev/null

real	0m2.096s
user	0m5.953s
sys	0m0.673s

pharaldsson_sym@SYMLINUX011:~$ export JULIA_NUM_THREADS=1
pharaldsson_sym@SYMLINUX011:~$ time ~/julia-1.3.1/bin/julia fasta.jl 25000000 >/dev/null

real	0m4.382s
user	0m4.638s
sys	0m0.620s

**Comment by PallHaraldsson** [comment]
Non-incremental works too (I however had filter_stdlibs=true), and seems a tiny bit faster:

pharaldsson_sym@SYMLINUX011:~$ time FastaAppCompiled_works/bin/Fasta 25000000 >/dev/null

real	0m1.721s
user	0m5.781s
sys	0m0.544s

I would suggest changing "creating base system image (incremental=false)..."
to something like:
"creating base system image (incremental=false), this might take a while, a few minutes..., that can be skipped with an incremental build, but will reduce runtime speed"

Done with:
julia> @time create_app("Fasta", "FastaAppCompiled", filter_stdlibs=true, force=true);
┌ Warning: it is not recommended to create an app without a preexisting manifest
└ @ PackageCompiler ~/.julia/packages/PackageCompiler/D8oaG/src/PackageCompiler.jl:592
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/Fasta/Project.toml`
 [no changes]
[ Info: PackageCompiler: creating base system image (incremental=false)...

22:56
22:57

[ Info: PackageCompiler: creating system image object file, this might take a while...

23:00

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/Fasta/Project.toml`
 [no changes]
[ Info: PackageCompiler: creating system image object file, this might take a while...
23:02

378.763215 seconds (871.68 k allocations: 43.803 MiB, 0.00% gc time)

**Comment by KristofferC** [comment]
The time taken to generate an app is expected.
