### ISSUE TITLE
Regression: Fails in Julia 1.5, but worked with PC v1.0.1

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/PackageCompiler.jl#376]
Works here:

$ ~/julia-1.5-012b270df6/bin/julia -O3 -q --project
┌ Warning: Could not load Revise.
└ @ Main ~/.julia/config/startup.jl:7

julia> @time create_app("Fasta", "FastaAppCompiled", incremental=true, force=true);

173.923591 seconds (515.34 k allocations: 25.134 MiB)

julia> versioninfo()
Julia Version 1.5.0-DEV.360
Commit 012b270df6 (2020-02-28 07:57 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU D-1541 @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 4

**Comment by PallHaraldsson** [comment]
I just wanted to make sure you knew that some Julia 1.5 version worked, and PG fails because of a change in it, not because of a change on Julia master.

However, In case you're wandering, the times I get are jus slightly better than in older Julia (likely random factor?), whlie again still beating C (from the REPL, the latter):

$ time FastaAppCompiled/bin/Fasta 25000000 >/dev/null

real	0m1.718s (compared to 1.730s in non-Julia 1.5)
user	0m5.634s
sys	0m0.591s


julia> @time Fasta.fasta(25000000, devnull)
  1.075872 seconds (41.69 k allocations: 956.913 MiB, 1.59% gc time)

compared to 1.177s with the C code. The REPL numbers vary, up to e.g. 1.138698 sec.

**Comment by KristofferC** [comment]
This is https://github.com/JuliaLang/julia/issues/35014.

**Comment by KristofferC** [comment]
Tracking the upstream issue in https://github.com/JuliaLang/PackageCompiler.jl/issues/376 instead since that issue has less "noise".
