### ISSUE TITLE
PackageCompiler tries to copy all system shared libs into package

### ISSUE THREAD

**Issue by seregaxvm** [JuliaLang/PackageCompiler.jl#385]
I've tried to build MyAppCompiled package from examples folder, but `create_app` call failed with *Permission denied* error. Investigating this issue I discovered that problem is with `bundle_julia_libraries` function. It contains line
```julia
cp(julia_libdir(), app_libdir; force=true)
```
In my case `julia_libdir()` value is `/usr/lib/x86_64-linux-gnu` so it actually tries to copy all system shared libraries into `lib` directory.

---
Linux 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
julia version 1.3.1

**Comment by KristofferC** [comment]
Did you see https://julialang.github.io/PackageCompiler.jl/dev/#Installation-instructions-1?

**Comment by seregaxvm** [comment]
Ok, I'll redirect problem to Debian maintainer.

**Comment by KristofferC** [comment]
Please don't, I don't think they can do anything about this. Right now, PackageCompiler only works with the official binaries.

**Comment by untoreh** [comment]
I experienced the same issue, on arch using official binaries from the [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=julia-bin), which are however installed system wide
