### ISSUE TITLE
Travis is failing on master

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/PackageCompiler.jl#388]
Travis CI is currently failing on PackageCompiler master.

See for example:
- https://travis-ci.org/github/JuliaLang/PackageCompiler.jl/builds/675675359
- https://travis-ci.org/github/JuliaLang/PackageCompiler.jl/builds/675029398
- https://travis-ci.org/github/JuliaLang/PackageCompiler.jl/builds/674919308

cc: @KristofferC

**Comment by DilumAluthge** [comment]
Are these test failures known and expected to fail consistently? If so, we should mark them as broken with `Test.@test_broken`. That way, CI will pass.

**Comment by KristofferC** [comment]
This is https://github.com/JuliaLang/julia/issues/35014.

**Comment by DilumAluthge** [comment]
The old 35014
