### ISSUE TITLE
Avoid calling `julia-config.jl` from `static_julia.jl`

### ISSUE THREAD

**Issue by lucatrv** [JuliaLang/PackageCompiler.jl#39]
I think we should avoid calling `julia-config.jl` with `Base.shell_split(read(etc etc))` in `static_julia.jl`. I have discussed [this](https://github.com/JuliaLang/julia/pull/24427#issuecomment-362945068) in the past. Of course we should also avoid code duplication in `julia-config.jl` and `PackageCompiler.jl`. We could however for now copy functions `cflags`, `ldflags`, `ldlibs`, `allflags` into `PackageCompiler.jl`, if we knew that `PackageCompiler.jl` is going to be added to Julia `stdlib`, so that `julia-config.jl` could be modified to use it at a later stage.
What do you think?

**Comment by SimonDanisch** [comment]
Sounds good to me!

**Comment by lucatrv** [comment]
Ok, I am now working on a PR to add new flags and refine default arguments, then I will work on this!

**Comment by lucatrv** [comment]
Implemented with PR #94
