### ISSUE TITLE
creating *.dll from Julia code

### ISSUE THREAD

**Issue by OndWolf** [JuliaLang/PackageCompiler.jl#392]
Dear contributors,
Package version 0.6.4 have function build_shared_lib(...). The goal for me is to create some code in Julia (I really like the syntax) and then have a possibility of calling this in C++ for example. One of wish for future was to try it in Matlab/Simulink (call from s-function). Unfortunately build_shared_lib(...) function is not include in last version 1.1.1. Is there chance that this could be in PackageCompiler in future again? Or maybe there is another possibility of having Julia code available in another enviroment?

Here is example of how I use it:
Julia code:

```
Base.@ccallable function test()::Cint
    return(2)
end
```

then create dll as:

build_shared_lib("C:/Users/Documents/Julia/test.jl", "test")

and call it as:
```
#include <Windows.h>

typedef int(*fcnptr)();
fcnptr myFnc;

int main()
{
	HMODULE handle = LoadLibrary(L"test.dll");
	if (handle != NULL)
	{
		myFnc = (fcnptr)GetProcAddress(handle, "test");
		std::cout << myFnc() << std::endl;
	}
	else
	{	
		std::cout << "Failed!\n";
	}
}
```

Thank you for answer.

**Comment by LeonardJohard** [comment]
I have the same request for interoperability with Modelica. In principle a dynamic library solution is much more useful than compiling into executables in our use cases. Any rough estimations or roadmaps for this functionality?

**Comment by KristofferC** [comment]
> Package version 0.6.4 have function build_shared_lib(...). The goal for me is to create some code in Julia (I really like the syntax) and then have a possibility of calling this in C++ for example. One of wish for future was to try it in Matlab/Simulink (call from s-function). Unfortunately build_shared_lib(...) function is not include in last version 1.1.1.

A sysimage is already a shared library. So try something like

```
build_sysimage(; sysimage_path="test.so", script="test.jl")
```

(the `script` arguments inserts that code into the sysimage).

You can see that the symbol is in there:

```
~/julia kc/devdocs*
❯ nm sys.so | grep test
...
0000000000135ca0 T test
```

Note that you will also in general need to initialize the Julia runtime.

**Comment by simonbyrne** [comment]
Here is an example of using PackageCompiler to build a shared library:
https://github.com/simonbyrne/cg/

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/PackageCompiler.jl/pull/490

**Comment by KristofferC** [comment]
You call the `init_julia` function: https://github.com/JuliaLang/PackageCompiler.jl/blob/459cefc0f156c48ea3ecee99c6adf257e9d1e9b5/src/julia_init.c#L64
