### ISSUE TITLE
Documentation for using in Julia 1.1.0

### ISSUE THREAD

**Issue by massimilianocomin** [JuliaLang/PackageCompiler.jl#394]
Hello,

I installed PackageCompiler with Julia v1.1.0 and I don't get the same functions as in the current version of the package e.g. there is no `create_sysimage` function. 
I guess this is because of compatibility ?

I couldn't find any docs for the version I have, any help would be appreciated!

I'd like to simply create an image for Plots.jl, Revise.jl, Atom.jl and possibly OhMyREPL.jl !

Thanks

**Comment by KristofferC** [comment]
You need to use at least Julia 1.3.1.

**Comment by terasakisatoshi** [comment]
> I'd like to simply create an image for Plots.jl, Revise.jl, Atom.jl and possibly OhMyREPL.jl !

Also checkout this issue https://github.com/JuliaLang/PackageCompiler.jl/issues/352 (you'll need julia >=1.3.1 of course)

**Comment by massimilianocomin** [comment]
Ok, I think it could be nice to write this requirement somewhere.

**Comment by DilumAluthge** [comment]
https://julialang.github.io/PackageCompiler.jl/dev/upgrade/#General-notes-1

https://github.com/JuliaLang/PackageCompiler.jl/blob/master/Project.toml

**Comment by massimilianocomin** [comment]
Ah sorry, didn't see it in the docs. It installed without problems with my version!
