### ISSUE TITLE
Consider renaming to AppCompiler.jl

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/PackageCompiler.jl#396]
I feel that this package is capable of doing more than its name suggests. One suggestion is to consider the name AppCompiler.jl. 

Would a rename be too invasive? Very few packages depend on it, but people probably have installed it and are using it.

https://juliahub.com/ui/Packages/PackageCompiler/MMV8C/1.1.1

**Comment by ararslan** [comment]
See also https://github.com/JuliaLang/PackageCompiler.jl/issues/160, where AppCompiler was suggested.

**Comment by DilumAluthge** [comment]
> Would a rename be too invasive? Very few packages depend on it, but people probably have installed it and are using it.

Keep in mind that we don't actually rename. We make a new package with the new name, but we keep the old package with the old name, so we will not break any existing workflows.

**Comment by KristofferC** [comment]
To me, this discussion was already had at least twice.

Anyway, breakage isn't really the point but first having PackageCompilerX, then PackageCompiler, then AppCompiler.jl is becoming a bit comical. I feel there is enough "marketing" in the sense of announcements, tutorials, tweets, repo stars, webinar etc doe this name that changing the name doesn't seem like a good idea.

**Comment by ViralBShah** [comment]
I didn't realize we had already had the discussion earlier.
