### ISSUE TITLE
Better Documentation for first time users

### ISSUE THREAD

**Issue by rezaeir** [JuliaLang/PackageCompiler.jl#404]
I'm not reporting a bug, maybe it can be assumed as requesting a feature. I wanted to use PackageCompiler to make a standalone app. However, the documentation was really confusing and I couldn't understand how I should proceed and there is no step by step example. For example, I tried to copy the basic structure and call create_app() and it gives me the error that there is no project. I asked a question in SO and someone told me to use Pkg.generate to make a project. I believe there should be a step by step tutorial in the documentation for people who are not advanced users.

**Comment by KristofferC** [comment]
It would be helpful if you listed step by step how you followed the tutorial and where things started going wrong. Then we can improve that part.

**Comment by rezaeir** [comment]
1. When I went to App manual page in the documentation of the PackageCompiler, it first talks about relocatability problems, however, as a user, my first concern was to see how to package works not what could be a potential problem. Hence, I believe it is better to start with an example and then talk about potential problems.
2. At the start of the 'Creating An App' section it talks about 'an app is a package with a project and manifest file'. However, it doesn't say what each one of these files should include, how we should place these files in a project folder, and maybe introducing Pkg.generate for this purpose.

**Comment by terasakisatoshi** [comment]
@rezaeir If you want to try this PackageCompiler.jl, 
My Project https://github.com/terasakisatoshi/HelloX.jl may help you. It will create a simple standalone application with a little operation.

> However, it doesn't say what each one of these files should include, how we should place these files in a project folder, and maybe introducing Pkg.generate for this purpose.

- I think we are supposed to read the official document related to Pkg https://julialang.github.io/Pkg.jl/v1/ before trying to read the documentation of  PackageCompiler.jl.

Therefore  

> how we should place these files in a project folder, and maybe introducing Pkg.generate for this purpose.

is not scope in this package. See https://julialang.github.io/Pkg.jl/v1/creating-packages/

**Comment by ianshmean** [comment]
Related to this. With the current docs menu structure, it's very easy to land in the "Create a sysimage" section that's actually under the "PackageCompiler - the manual way" section.

Perhaps
"PackageCompiler - the manual way" => "The manual way"
"Create a sysimage" => "Create a sysimage manually"

The "Manual"."Sysimages" sections could also change to "Manual"."Create a sysimage", to attract more attention

**Comment by KristofferC** [comment]
Yeah, sounds like a good idea
