### ISSUE TITLE
Compatibility with Julia 1.0

### ISSUE THREAD

**Issue by travigd** [JuliaLang/PackageCompiler.jl#410]
It would be nice™ if this project was compatible with Julia 1.0.

I'm not sure if there are big internal changes that make it hard to keep compatibility with Julia 1.0, but it looks to me like the big thing that's not supported is just `Artifacts.toml` (which is only used for downloading GCC on Windows and compiling packages that have artifacts in them - which wouldn't be an issue if running Julia < 1.3 anyway).

**Comment by KristofferC** [comment]
The package itself uses Artifacts so this is pretty hard. I think this will just not happen.
