### ISSUE TITLE
Error in devdocs/relocatable_part_3

### ISSUE THREAD

**Issue by zot** [JuliaLang/PackageCompiler.jl#411]
The cmdline example to create the .o file at https://github.com/JuliaLang/PackageCompiler.jl/blame/master/docs/src/devdocs/relocatable_part_3.md#L137 is actually a paste of the example after it. I'm looking through the docs right now for how to create the .o file. I'll paste the cmdline in when I find out what it is :).

**Comment by zot** [comment]
Looks like maybe the example should be this?

```
julia --project=. --startup-file=no --output-o=sys.o -J"/home/kc/julia/lib/julia/sys.so" -- custom_sysimage.jl
```

**Comment by zot** [comment]
Also, the doc says it uses the same `generate_sysimage.jl` file as the referenced text but I think it should contain `using Crayons` instead of `using CSV` and that should be noted in the doc.

**Comment by KristofferC** [comment]
This part of the docs has been removed.
