### ISSUE TITLE
Documentation: One too many sys.so

### ISSUE THREAD

**Issue by gsal** [JuliaLang/PackageCompiler.jl#418]
Regarding section:  https://julialang.github.io/PackageCompiler.jl/dev/devdocs/sysimages_part_1/#.-Creating-the-object-file-1

Regarding command:
julia --startup-file=no --output-o **sys.o** -J"/home/kc/julia/lib/julia/sys.so" custom_sysimage.jl
(And later: gcc -shared -o **sys.so** ...)

At the very end, I don't particularly like the fact that the new sysimage object is named **sys.o,** because later, it going to yield a **sys.so...but** there is already one, julia's own **sys.so.**  So, whenever I see **sys.so** in subsequent commands, I am not sure which one the author is referring to...julia's or mine.  

So, maybe, when it comes to creating an app specific sysimage object (and shared library), it should be referred to as **myapp.o** (and **myapp.so**)?

Thanks.

**Comment by KristofferC** [comment]
This part of the docs has been removed.
