### ISSUE TITLE
Documentation error: identical command to compile *.o and *.so 

### ISSUE THREAD

**Issue by gsal** [JuliaLang/PackageCompiler.jl#419]
Regarding section: https://julialang.github.io/PackageCompiler.jl/dev/devdocs/relocatable_part_3/#Precompilation-and-sysimage-1

This section show 3 commands to produce precompilation statements, sysimage *.o and sysimage *.so; but, the commands for *.o and *.so are identical!

Thanks.

**Comment by KristofferC** [comment]
This part of the documentation has been removed.
