### ISSUE TITLE
Still some problem with force=true

### ISSUE THREAD

**Issue by TsurHerman** [JuliaLang/PackageCompiler.jl#42]
it still doesn't work on windows or mac.
Last I tried it complained about missing sys.o and reverted to some state which I suspect is
not the one I started with.

However PackageCompiler.revert() seems to work and doesn't have any problems copying the files
or locating them

**Comment by SimonDanisch** [comment]
Sorry, took a while to confirm that the fix is working ;) But master should work now! :)

**Comment by SimonDanisch** [comment]
Let me know if it works for you, then we can tag!

**Comment by TsurHerman** [comment]
It seems to work on osx , I still haven't tested it on windows.
Just to let you know I am using a "patched" version of packagecompiler which passes
precompile=no compilecache=no to both the snooper and the compiler, the only problem is that
I need to add
Sys.__init__()
Base.early_init()
to the beginning of precompile.jl so that JULIA_HOME will be defined. I later get complains about redefining JULIA_HOME but that is the only hiccup I encounter. overall the process with precompile=no and compilecache=no seems the right one , I am quite sure that tests that failed before for GLVisulaize 
will pass with these flags always on.

**Comment by SimonDanisch** [comment]
The old GLVisualize?

**Comment by SimonDanisch** [comment]
@vtjnash is this the right approach?

**Comment by vtjnash** [comment]
Look good to me!

**Comment by SimonDanisch** [comment]
@TsurHerman looks like you have this ready locally already. Mind to open a PR?

**Comment by TsurHerman** [comment]
The only issue is the
“Redefining JULIA_HOME״ warnings on Julia 0.6 ..
If that is acceptable for now then I’ll issue a PR

**Comment by SimonDanisch** [comment]
yes, please!
