### ISSUE TITLE
Compilation of indirect dependencies

### ISSUE THREAD

**Issue by kcajf** [JuliaLang/PackageCompiler.jl#423]
PackageCompiler doesn't like the fact that I'm trying to compile packages that are indirect dependencies of my project. It errors here:
```
function check_packages_in_project(ctx, packages)
    packages_in_project = collect(keys(ctx.env.project.deps))
    if ctx.env.pkg !== nothing
        push!(packages_in_project, ctx.env.pkg.name)
    end
    packages_not_in_project = setdiff(string.(packages), packages_in_project)
    if !isempty(packages_not_in_project)
        error("package(s) $(join(packages_not_in_project, ", ")) not in project")
    end
end
```
Is there a good reason for this check? Will indirect dependencies get compiled anyway if they are needed?

**Comment by KristofferC** [comment]
> Will indirect dependencies get compiled anyway if they are needed?

Yes, since they are loaded by direct dependencies.

**Comment by kcajf** [comment]
Thanks!
