### ISSUE TITLE
compiled sysimg is extremely slower when using --project

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/PackageCompiler.jl#427]
Hi, I'm using PackageCompiler to compile this CLI: https://github.com/Roger-luo/IonCLI.jl/blob/master/deps/build.jl

The build script can be found here, which is just a standard `create_sysimg` call: https://github.com/Roger-luo/Comonicon.jl/blob/master/src/build.jl#L77

this works perfectly under MacOS currently, however, when I tried to install the CLI and build the sysimg on Linux I found that the generated CLI

```julia
#!/home/roger/packages/julias/julia-1.4/bin/julia --project=/home/roger/.julia/dev/IonCLI -J/home/roger/.julia/dev/IonCLI/deps/lib/libion.so
using IonCLI; IonCLI.command_main()
```

is way slower than using without `--project`, which I thought was supposed to be the same

```julia
#!/home/roger/packages/julias/julia-1.4/bin/julia -J/home/roger/.julia/dev/IonCLI/deps/lib/libion.so
using IonCLI; IonCLI.command_main()
```

meanwhile I notice if I use `--compile=min -O2` after the `-J` command, the sysimage path is parsed correctly by Julia's own CLI. this made me think maybe there
is something wrong with the CLI, so I use the environment variable instead, and now it works fine!

```
!/bin/sh
JULIA_PROJECT=/home/roger/.julia/dev/IonCLI /home/roger/packages/julias/julia-1.5/bin/julia \
    --sysimage=/home/roger/.julia/dev/IonCLI/deps/lib/libion.so \
    -e "using IonCLI; IonCLI.command_main()" $@
```

I also checked the precompiled method instances using SnoopCompile, it seems the methods should be compiled stays the same as MacOS, so I'm not sure what is causing this.

I tested the problem I described above on both Julia-1.5.0-rc1 and Julia-1.4.2

```
julia> versioninfo()
Julia Version 1.5.0-rc1.0
Commit 24f033c951 (2020-06-26 20:13 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
```

```
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, znver1)
```

and benchmark result on julia-1.5

using `--project`

```sh
Benchmark #1: ion add -h
  Time (mean ± σ):     825.4 ms ±   5.7 ms    [User: 931.4 ms, System: 387.4 ms]
  Range (min … max):   815.4 ms … 832.0 ms    10 runs
```

using `JULIA_PROJECT`

```sh
Benchmark #1: ion add -h
  Time (mean ± σ):     109.8 ms ±   4.4 ms    [User: 91.7 ms, System: 47.9 ms]
  Range (min … max):   105.6 ms … 128.9 ms    23 runs
```

I feel there might be something went wrong in the `option.c` or `getopt.c`, but I'm not sure...

**Comment by KristofferC** [comment]
I've tried repro this but https://github.com/Roger-luo/Comonicon.jl/blob/master/src/build.jl#L77 no longer exists and trying to build `IonCLI` I get:

```
[ Info: ===== Start precompile execution =====
ERROR: LoadError: failed process: Process(`/home/kc/Applications/julia-1.6.2/bin/julia --color=yes --startup-file=no --sysimage=/home/kc/Applications/julia-1.6.2/lib/julia/sys.so --project=/home/kc/JuliaPkgs/IonCLI.jl --compile=all --trace-compile=/tmp/jl_aIbnKi /home/kc/JuliaPkgs/IonCLI.jl/deps/precompile.jl`, ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:525 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base ./process.jl:440
  [3] run
    @ ./process.jl:438 [inlined]
  [4] run_precompilation_script(project::String, sysimg::String, precompile_file::String)
    @ PackageCompiler ~/.julia/packages/PackageCompiler/r8Xcy/src/PackageCompiler.jl:246
```

Feel free to update + comment or make a new issue with further information.
