### ISSUE TITLE
Plots stops working in REPL on julia 1.5, macos

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaLang/PackageCompiler.jl#428]
`create_sysimage([:Plots],replace_default=true)` causes e.g. `plot(sin)` to no longer create an image in the REPL. Works fine in vscode though.

```julia 
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by pfitzseb** [comment]
Don't you need a `pushdisplay(Plots.PlotsDisplay())` on startup? That should've been necessary prior to 1.5 as well.

**Comment by AshtonSBradley** [comment]
no, didn't need it on 1.4

**Comment by pfitzseb** [comment]
Does it fix the issue?

**Comment by AshtonSBradley** [comment]
I can't tell, I had to `rm -Rf .julia` as when I tried reverting the sysimage a bunch of stuff broke (Plots in particular)

**Comment by KristofferC** [comment]
If you could show the output of

```
julia> typeof.(Base.Multimedia.displays)
3-element Array{DataType,1}:
 TextDisplay
 REPL.REPLDisplay{REPL.LineEditREPL}
 Plots.PlotsDisplay
```

that would be useful.

**Comment by AshtonSBradley** [comment]
Ok, I installed a completely fresh julia 1.5 on my laptop. Checked that Plots works fine in the REPL before building the system image. 

After 
`create_sysimage([:Plots,:IJulia],replace_default=true)`, again I get no plot in the REPL. The output of the command is
```julia
julia> typeof.(Base.Multimedia.displays)
3-element Array{DataType,1}:
 TextDisplay
 REPL.REPLDisplay{REPL.LineEditREPL}
 Plots.PlotsDisplay
```

Also
```julia
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by KristofferC** [comment]
And this is with default GR backend?

**Comment by AshtonSBradley** [comment]
yes, GR

**Comment by KristofferC** [comment]
My guess is that this has something to do with https://github.com/JuliaLang/julia/issues/42425. If it is not that specific issue it is likely to be something similar and unlikely something that requires any changes to PackageCompiler. The fact that no one seems to be able to reproduce it makes it hard.
