### ISSUE TITLE
PackageCompiler turns keyword-argument function into positional arguments

### ISSUE THREAD

**Issue by dalum** [JuliaLang/PackageCompiler.jl#431]
I haven't been able to produce an MWE for this, so I realise this isn't a super helpful issue. :facepalm: But I still wanted to flag it here.

I have a rather long function definition, as part of a large private package ecosystem, in which a function is defined with the following signature:
```julia
function fit_some_parameters(
    database, id;
    fit_symbols = (:x, :y,),
    model_type = :my_model,
    δ1 = nothing,
    δ2 = nothing,
    x = nothing,
    y = nothing,
    z = nothing,
    optim_options::Optim.Options = Optim.Options(),
    strategies = [
        Fminbox(BFGS()),
        Fminbox(length(fit_symbols) > 1 ? GradientDescent() : NelderMead()),
    ],
)
```
After compiling this into the sysimg with a test of:
```
@test fit_some_parameters("database_file.db", 12345)
```
(I have also tried adding tests which calls the function with various keyword arguments provided, but it leads to the same result) loading the sysimg gives the following methods:
```
julia> methods(MyModule.fit_some_parameters)
# 10 methods for generic function "fit_some_parameters":
[1] fit_pure_compound_parameters(db, compound) ...
[2] fit_pure_compound_parameters(db, compound, fit_symbols) ...
[3] fit_pure_compound_parameters(db, compound, fit_symbols, model_type) ...
...
[10] fit_pure_compound_parameters(db, compound, fit_symbols, model_type,  δ1, δ2, x, y, z, optim_options, strategies) ...
```
that is, there is no method that accepts keyword arguments.  Changing the default parameter for `strategies` to
```julia
    ...
    strategies = (
        Fminbox(BFGS()),
        Fminbox(length(fit_symbols) > 1 ? GradientDescent() : NelderMead()),
    ),
)
```
i.e., a tuple, resolves it, and now the only method is the keyword argument one.  So it seems to be related to having a keyword argument with a default value set to a vector (or possibly any heap allocated object?).

However, as I said, I don't have an MWE since simply making a function with the signature above isn't sufficient to reproduce the bug. So there is something more going on that *just* that.

Note: This happens on Julia 1.5.  I have not been able to test it on earlier versions, since the function depends on features introduced in 1.5.

**Comment by KristofferC** [comment]
This seems very odd. I feel an MWE would be needed to diagnose this further though...

**Comment by KristofferC** [comment]
I'll close this since it is not really actionable with the current information. If you provide more (does not have to be an MWE, just something) we can reopen and look at it.
