### ISSUE TITLE
Missing website

### ISSUE THREAD

**Issue by zdroid** [JuliaLang/PackageCompiler.jl#432]
This repository is missing a website link in its description. Reasons to do this are listed in [this Discourse thread](https://discourse.julialang.org/t/a-suggestion-for-package-maintainers/44111).

https://julialang.github.io/PackageCompiler.jl/dev/ is an example of a good link for this purpose.

**Comment by DilumAluthge** [comment]
@ViralBShah Can you add the PackageCompiler docs as the website for this repo?
