### ISSUE TITLE
Docker image with Julia Sysimage built on Windows does not run on Linux / MacOS

### ISSUE THREAD

**Issue by lungben** [JuliaLang/PackageCompiler.jl#441]
Hi,

I tried to create a Docker image with a sysimage including Pluto.jl for faster startup times, see
https://github.com/fonsp/PlutoUtils.jl/pull/13

I built this image on Windows 10 (based on the latest official Julia 1.5.1 Docker image, using recent version of PackageCompiler) and the Docker image is working fine on Windows, but not on Linux (and reportedly also not on MacOS). When starting the container, I get the error message `ERROR: Unable to find compatible target in system image.`.

I tried building the image both with gcc and clang compilers.

I thought when building / running a sysimage in Docker, only the OS of the Docker container should matter, not the OS of the host system. Or am I doing something wrong here?

Thanks and Best Regards
Benjamin

Edit:
the Docker image built under Windows can be obtained here:
`docker pull plutojl/pluto:precompiled`

**Comment by KristofferC** [comment]
Try to give the `cpu_target="generic"` keyword argument. Or if you want to use the same one as the standard Julia you can use `cpu_target = PackageCompiler.default_app_cpu_target()`

**Comment by lungben** [comment]
With `cpu_target = PackageCompiler.default_app_cpu_target()` it works fine (image built on Dockerhub runs on Linux and Windows machines).

Thank you very much!
