### ISSUE TITLE
"undefined symbol" error with Julia 1.6-DEV when loading system image

### ISSUE THREAD

**Issue by tkf** [JuliaLang/PackageCompiler.jl#445]
Using https://github.com/JuliaLang/PackageCompiler.jl/commit/cb994c72e2087c57ffa4727ef93589e1b98d8a32 (#443) and `julia` 1.6.0-DEV.991, I get

```console
$ cd ~/.julia/dev/PyCall

$ git log -n1 --oneline
c411ea0 (HEAD -> master, tkf/master) Emit more accurate error message (#760)

$ julia-dev --startup-file=no -e 'using Pkg; pkg"st PyCall"'
Status `~/.julia/environments/v1.6/Project.toml`
  [438e738f] PyCall v1.91.4 `~/.julia/dev/PyCall`

$ julia-dev --startup-file=no -e 'using InteractiveUtils; versioninfo()'
Julia Version 1.6.0-DEV.991
Commit 9ffc7036ff* (2020-09-21 13:10 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

$ julia-dev --startup-file=no aot/compile.jl
 Activating environment at `~/.julia/dev/PyCall/aot/Project.toml`
Path `/home/takafumi/.julia/dev/PyCall` exists and looks like the correct package. Using existing path.
  Resolving package versions...
No Changes to `~/.julia/dev/PyCall/aot/Project.toml`
Updating `~/.julia/dev/PyCall/aot/Manifest.toml`
  [56f22d72] + Artifacts
   Building Conda ─→ `~/.julia/packages/Conda/3rPhK/deps/build.log`
   Building PyCall → `~/.julia/dev/PyCall/deps/build.log`
 Activating environment at `~/.julia/environments/v1.6/Project.toml`
[ Info: PackageCompiler: creating system image object file, this might take a while...
[ Info: System image: /home/takafumi/.julia/dev/PyCall/aot/sys.so

$ julia-dev --startup-file=no --sysimage=$PWD/aot/sys.so
ERROR: could not load library "/home/takafumi/.julia/dev/PyCall/aot/sys.so"
/home/takafumi/.julia/dev/PyCall/aot/sys.so: undefined symbol: jfptr_allbindings_6986
```

where `aot/compile.jl` is a simple invocation of `create_sysimage([:PyCall], ...)` with some options: https://github.com/JuliaPy/PyCall.jl/blob/c411ea065a6d422d0e52430a08f1b988b86b87dd/aot/compile.jl

**Comment by tkf** [comment]
Here is a repro on GitHub Actions

> ```
> ERROR: could not load library "/home/runner/work/PyCall.jl/PyCall.jl/aot/sys.so"
> /home/runner/work/PyCall.jl/PyCall.jl/aot/sys.so: undefined symbol: jsysw_allbindings_0
> ```
>
> https://github.com/JuliaPy/PyCall.jl/pull/825/checks?check_run_id=1147241179#step:9:1 (https://github.com/JuliaPy/PyCall.jl/pull/825)

**Comment by tkf** [comment]
Hmm... I can't reproduce this if I build `julia` in GitHub Actions:
https://github.com/tkf/julia/runs/1147911963?check_suite_focus=true#step:6:2551 (https://github.com/tkf/julia/commit/8c786540abd9491953319c26343a4ed2342c5317)

I also can't reproduce this locally anymore (maybe after running `make clean`).

**Comment by KristofferC** [comment]
Seems to work locally here as well so closing this.
