### ISSUE TITLE
Symbol not found ccalllib_libquadmath

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/PackageCompiler.jl#449]
When building a sysimage that touches a lot of packages and quite a bit of code, I get a

    FATAL ERROR: Symbol "ccalllib_libquadmath.so.039718"not found

I'm not quite sure how to diagnose this - is this a known problem?

**Comment by oschulz** [comment]
This is with Julia v1.5.1

**Comment by KristofferC** [comment]
Is this still a problem in 1.6?

**Comment by oschulz** [comment]
Nope, haven't seen this for a while now, let's close this.
