### ISSUE TITLE
Seeing "Cannot locate artifact 'x86_64-w64-mingw32'" on Julia nightly

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/PackageCompiler.jl#455]
This is with Julia nightly and PackageCompiler 1.2.1.

It's on Linux, so presumably I don't need the artifact.

Link to the log: https://github.com/bcbi/SimpleContainerGenerator.jl/pull/93/checks?check_run_id=1230454453

**Comment by DilumAluthge** [comment]
Let me know if you need more information.

**Comment by DilumAluthge** [comment]
Has there been some change on nightly as far as loading artifacts lazily? @staticfloat @KristofferC

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/PackageCompiler.jl/pull/443

**Comment by DilumAluthge** [comment]
Duplicate of #443
