### ISSUE TITLE
Crashed precompile damages default system image

### ISSUE THREAD

**Issue by DeanLym** [JuliaLang/PackageCompiler.jl#465]
I ran into this problem when a precompiling process crashed, the default system image will be damaged. There is no sys.dll.backup file available. It seems to me that the backup default system image is generated in the last step. In this case if the precompiling crashed, there will be no default system image.

![image](https://user-images.githubusercontent.com/14900929/98209690-35e53780-1ef4-11eb-9efe-980b5f61a9c1.png)

**Comment by KristofferC** [comment]
Hm, that's not intended. The intention is to create the sysimage in a temporary location:

https://github.com/JuliaLang/PackageCompiler.jl/blob/69f556a6d6d1abb3f9f9d1bb46edfe4df5c66d25/src/PackageCompiler.jl#L392-L393

and only in the end move it to the correct location:

https://github.com/JuliaLang/PackageCompiler.jl/blob/69f556a6d6d1abb3f9f9d1bb46edfe4df5c66d25/src/PackageCompiler.jl#L441-L445

The replacement of the old sysimage should only be done after the backup is created. Not sure what is going wrong.

**Comment by KristofferC** [comment]
replace_default is not recommended and will probably get removed (#546). Since issues with it are known, I'll close this.
