### ISSUE TITLE
Clear the docstrings

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/PackageCompiler.jl#467]
The docstrings are part of the sysimage. It'd be nice if they could be optionally stripped out.

**Comment by KristofferC** [comment]
This is an upstream feature that I have heard will be worked on soon (the ability to strip out metadata).

**Comment by cstjean** [comment]
Seems to be https://github.com/JuliaLang/julia/pull/42925 and https://github.com/JuliaLang/julia/issues/42513
