### ISSUE TITLE
Problem loading sysimage including RoMEPlotting

### ISSUE THREAD

**Issue by lemauee** [JuliaLang/PackageCompiler.jl#478]
Hi, 

I have problems loading a sysimage including RoMEPlotting as described in https://github.com/JuliaRobotics/RoMEPlotting.jl/issues/140

`versioninfo()`:
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by KristofferC** [comment]
This seems to work fine now:

```
❯ julia --sysimage="sysimageRoMEPlotting.so" --project
[ Info: Including InteractiveUtils related functions in IncrementalInference.
[ Info: Defining spyCliqMat(..) for visualizing association matrix of a clique in the Bayes (Junction) tree
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
```
