### ISSUE TITLE
Package Statistics not found in current path

### ISSUE THREAD

**Issue by ayman-albaz** [JuliaLang/PackageCompiler.jl#480]
Hey all, I've been following the PackageCompiler tutorial on the documentation website and I noticed that using any installed package (e.g. CSV, DataFrames, etc..) successfully compiles while using default packages (e.g. Statistics, Random, Pkg, etc...) doesn't work. 

How do I fix this or get around this? Thanks.

```julia
Base.reinit_stdio()
Base.init_depot_path()
Base.init_load_path()

using Statistics
@time X = ones((1000, 1000)) .|> Int8
@time mean(X)

empty!(LOAD_PATH)
empty!(DEPOT_PATH)
```
```shell
julia --startup-file=no --output-o sys3.o -J "/Applications/Julia-1.5.app/Contents/Resources/julia/lib/julia/sys.dylib" myscript.jl
ERROR: LoadError: ArgumentError: Package Statistics not found in current path:
- Run `import Pkg; Pkg.add("Statistics")` to install the Statistics package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:893
 [2] include(::Function, ::Module, ::String) at ./Base.jl:380
 [3] include(::Module, ::String) at ./Base.jl:368
 [4] exec_options(::Base.JLOptions) at ./client.jl:296
 [5] _start() at ./client.jl:506
```

**Comment by KristofferC** [comment]
Do you have `Statistics` in your project file? Why do you execute all these `init` functions, where does it say to do that?

**Comment by ayman-albaz** [comment]
Thanks for the link. Precompiling works using it.

I was following this tutorial originally: https://julialang.github.io/PackageCompiler.jl/dev/devdocs/sysimages_part_1/#man-tutorial-sysimage-1
