### ISSUE TITLE
Multi-stage incremental builds

### ISSUE THREAD

**Issue by Byrth** [JuliaLang/PackageCompiler.jl#488]
https://discourse.julialang.org/t/unable-to-find-compatible-target-in-system-image/52879

The idea here is that I'm trying to build a Julia sysimage in multiple stages so the code I am developing can be quickly deployed to staging / built for release. I have one fairly static stage that contains my dependencies and then have another stage that contains the application that I am developing.

Both stages are built on the same machine in the same multi-stage dockerfile (using `DOCKER_BUILDKIT=1`)
~~~
#23 347.7 [ Info: PackageCompiler: creating system image object file, this might take a while...
#23 347.7 ERROR: Unable to find compatible target in system image.
#23 348.8 ERROR: LoadError: failed process: Process(`/root/julia/bin/julia --color=yes --startup-file=no '--cpu-target=generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)' --sysimage=/root/julia/lib/julia/sys.so --project=/root/myproj.jl/inner.jl --output-o=/tmp/jl_UGJKKB.o -e '...'`, ProcessSignaled(11))
~~~

As you can see, it is using the default cpu-target for x86-64, which is appropriate for the VM it is building on. When I force that as was recommended on discourse, I correspondingly get the same result. When I try to force `generic,-cx16`, I get a different error about my VM not supporting cx16 which is unexpected because I excluded it.

Julia 1.5.3
PackageCompiler 1.2.4
CentOS 7 docker file using devtoolkit-9 to get a modern gcc version.

**Comment by Byrth** [comment]
To add more information, I have problems when I build a sysimage on a [Cascade Lake Xeon processor](https://ark.intel.com/content/www/us/en/ark/products/192437/intel-xeon-gold-6230-processor-27-5m-cache-2-10-ghz.html) using `default_app_cpu_target()` (`generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1)`) and then try to use it on a [Broadwell Xeon processor](https://ark.intel.com/content/www/us/en/ark/products/93796/intel-xeon-processor-e5-4660-v4-40m-cache-2-20-ghz.html).

Looking at the different flags available on each processor (from `less /proc/cpuinfo`):
Cascade Lake only - invpcid_single, ibrs_enhanced, avx512f, avx512dq, clflushopt, clwb, avx512bw, avx512vl, xsavec, pku, ospke
Broadwell only - hle, rtm

Based on [some docs](https://www.bookstack.cn/read/julialang-1.1/431943206e754e9d.md), I take it that the default is building for:
* generic for no AVX
* sandybridge (without xsaveopt and explicitly enforcing the default non-cloning behavior) for functions that benefit from AVX
* haswell (without rdrand and based on the sandybridge image rather than generic) for functions that benefit from AVX2
* No support in the default for AVX512

I am guessing that the `-feature` options are provided to prevent excessive duplication for minor operational benefit. Regardless, the Broadwell processor should be using the Haswell version of the functions (falling back to the other two). The fact that it fails to load with "Unable to find compatible target in system image" means that it does not recognize Haswell as applicable when it is compiled on my Cascade Lake VM. If I wanted to add explicit support for Broadwell to the `x86_64` default compiled on cascade lake, perhaps I could use `cpu_target="generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1);broadwell,-rtm,base(2)"`?

Reading all this documentation, I am only increasingly convinced that the host architecture for compilation should not matter (in theory) for relocatability because we are defining the targets. Perhaps this is a julia issue rather than a PackageCompiler one?

**Comment by KristofferC** [comment]
>  Perhaps this is a julia issue rather than a PackageCompiler one?

I think so. The only thing `PackageCompiler` does is to pass along the `cpu_target` to Julia:

https://github.com/JuliaLang/PackageCompiler.jl/blob/49656680111472d60ecef4d90f801e8ed051fc90/src/PackageCompiler.jl#L226-L228

So you should get the same error in case you try to build Julia itself with this `cpu_target`. I would try that and open an issue on Julia.

**Comment by Byrth** [comment]
I changed jobs and no longer have access to those servers, but good to know anyway.
