### ISSUE TITLE
core dumped on Julia v1.6 Beta 1

### ISSUE THREAD

**Issue by felipenoris** [JuliaLang/PackageCompiler.jl#494]
This is somewhat similar to #466 , but using Julia v1.6 Beta 1 and combining with a different package. Also, the system image builds successfully, and the error occurs when loading a julia session using the new sysimage.

After using this `precompile_execution_file` script to build a system image, Julia v1.6 Beta 1 core dumps when loading the sysimage:

```julia
import InterestRates
include(joinpath(pkgdir(InterestRates), "test", "runtests.jl"))
```

The script in the repo https://github.com/felipenoris/package-compiler-issue demonstrates this issue.

**Comment by oschulz** [comment]
I also had trouble with PackageCompiler on v1.6.0-beta1. Just run @felipenoris 's test case on v1.6.0-rc1 and it seems to work.

**Comment by Sacha0** [comment]
Likewise on this end, rc1 fixed a core dump we were encountering on beta1. Perhaps good enough to close? :)

**Comment by KristofferC** [comment]
Closing for now

**Comment by oschulz** [comment]
Just to confirm, I used PackageCompiler and the generated sysimages with two quite monstrous use cases (dependency-wise) today on Julia v1.6.0-rc1, worked flawlessly.
