### ISSUE TITLE
Support APE: "αcτµαlly pδrταblε εxεcµταblε" binaries

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/PackageCompiler.jl#495]
https://justine.storage.googleapis.com/ape.html

Hi, I'm not pushing for you doing this, think of it as a FYI, and the thread here could be about what's needed. Seems we would first need the Julia runtime itself to be compiled this way. I had a similar thought way back but couldn't figure out polymorphic Unix shell and say Windows Powershell script in one, but at least the above way is known to work.

>Please note that this emulator isn't a requirement. αcτµαlly pδrταblε εxεcµταblεs work fine if you just run them on the shell, the NT command prompt, or boot them from the BIOS. [..]
It'll be nice to know that any normal PC program we write will "just work" on Raspberry Pi and Apple ARM.

**Comment by KristofferC** [comment]
Thanks for the link. This is, however, a bit too speculative to have as an open issue so I will close this.
