### ISSUE TITLE
Easier Plots tutorial for beginners?

### ISSUE THREAD

**Issue by drozzy** [JuliaLang/PackageCompiler.jl#496]
Currently the tutorial showing how to use Plots.jl makes use of external file.
https://julialang.github.io/PackageCompiler.jl/dev/examples/plots/

However, it's not clear where `precompile_plots.jl` should be located. Perhaps a recommendation like that in Gadfly documentation should be given, where no external file is needed, only a custom command (http://gadflyjl.org/stable/):

> At the end of the resulting copius output will be the command to launch this custom version of julia: something like julia -J $HOME/.julia/dev/PackageCompiler/sysimg/sys.dylib. Make it convenient by putting an alias in your .bashrc: alias julia-gadfly="julia -J ...".

and:
 
> Now that using Gadfly takes just a split second, there's no reason not to do so automatically in your $HOME/.julia/config/startup.jl file.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/PackageCompiler.jl/commit/811e1e7110490eb510d8c1a918755111911e5980
