### ISSUE TITLE
Doesn't seem to work with local modules

### ISSUE THREAD

**Issue by wmanning-cra** [JuliaLang/PackageCompiler.jl#499]
I'm trying to use PackageCompiler in Julia v1.5.2. I have a local module that I want to include in the sysimage. My "precompile_execution_file" looks something like this:

```
Base.reinit_stdio()
Base.init_depot_path()
Base.init_load_path()

# Import my local module
include("../../MyModule/MyModule.jl")

# Pre-compile important stuff from my module
MyModule.function1()
MyModule.function2()

empty!(LOAD_PATH)
empty!(DEPOT_PATH)
```

Then to create the sysimage, I run:
```
create_sysimage(:MyModule,
            precompile_execution_file="precompile-environment-impl.jl",
            sysimage_path="build/MyImage.dll")
```

But I get the error **_package(s) MyModule not in project_**. I'm no julia expert, but looking at the source, it seems like the named packages have to come from the package manager, i.e. from the internet? And if I just remove the package name from the call to `create_sysimage`, then the resulting sysimage doesn't seem to contain my module.

**Comment by seiji-engelkemier** [comment]
Did you figure out a solution for this? I'm trying to do something similar of having a local module being used when creating an app.
```
module MyApp
using myModule
function julia_main()
     try
          real_main()
     ...
end
function real_main()
        myModuleFunction( )
end
end # module
```
I get the following when I run create_app("MyApp","MyAppCompiled")
`ERROR: LoadError: ArgumentError: Package MyApp does not have myModule in its dependencies`

**Comment by KristofferC** [comment]
> I get the error package(s) MyModule not in project. I'm no julia expert, but looking at the source, it seems like the named packages have to come from the package manager, i.e. from the internet? 

No, not from the internet. Just do e.g. `pkg> generate MyModule`. PackageCompiler expects to put packages inside sysimages.

>  ERROR: LoadError: ArgumentError: Package MyApp does not have myModule in its dependencies

If you want to use `using myModule` then `myModule` should be a package. https://pkgdocs.julialang.org/v1/creating-packages/#Adding-dependencies-to-the-project might help.
