### ISSUE TITLE
linker crashs on >2GB library on MacOS

### ISSUE THREAD

**Issue by rssdev10** [JuliaLang/PackageCompiler.jl#500]
[2gb_issue.tgz.zip](https://github.com/JuliaLang/PackageCompiler.jl/files/6162023/2gb_issue.tgz.zip)

```
[ Info: PackageCompiler: creating system image object file, this might take a while...
final section layout:
    __TEXT/__text addr=0x00002770, size=0x0075A2C0, fileOffset=0x00002770, type=1
    __TEXT/__stubs addr=0x0075CA30, size=0x00000234, fileOffset=0x0075CA30, type=29
    __TEXT/__stub_helper addr=0x0075CC64, size=0x000003BC, fileOffset=0x0075CC64, type=33
    __TEXT/__const addr=0x0075D020, size=0x0000ABB8, fileOffset=0x0075D020, type=0
    __TEXT/__cstring addr=0x00767BE0, size=0x00002E1F, fileOffset=0x00767BE0, type=13
    __TEXT/__unwind_info addr=0x0076AA00, size=0x00014910, fileOffset=0x0076AA00, type=22
    __TEXT/__eh_frame addr=0x0077F310, size=0x000E4CE0, fileOffset=0x0077F310, type=19
    __DATA_CONST/__got addr=0x00864000, size=0x00000048, fileOffset=0x00864000, type=30
    __DATA_CONST/__mod_init_func addr=0x00864048, size=0x00000008, fileOffset=0x00864048, type=34
    __DATA_CONST/__const addr=0x00864050, size=0x00024924, fileOffset=0x00864050, type=0
    __DATA/__la_symbol_ptr addr=0x0088C000, size=0x000002F0, fileOffset=0x0088C000, type=28
    __DATA/__data addr=0x0088C300, size=0xA233FDD0, fileOffset=0x0088C300, type=0
    __DATA/__bss addr=0xA2BCC0D0, size=0x0001EB20, fileOffset=0x00000000, type=26
    __DATA/__common addr=0xA2BEABF0, size=0x00000014, fileOffset=0x00000000, type=26
    __DATA/__huge addr=0xA2BEAC04, size=0x00000000, fileOffset=0x00000000, type=26
ld: 32-bit RIP relative reference out of range (2730268982 max is +/-2GB): from _jlplt_jl_array_grow_end_22 (0x00002770) to _ccall_jl_array_grow_end_21 (0xA2BCC0D8) in '_jlplt_jl_array_grow_end_22' from /var/folders/n_/h8tm56xd4q9_41rd7knts2r80000gn/T/jl_JlohZB.o(text.o) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: failed process: Process(`gcc -m64 -march=x86-64 -shared -L/Applications/Julia-1.5.app/Contents/Resources/julia/lib -o sysimage/TwoGbCompilerIssue.so -Wl,-all_load /var/folders/n_/h8tm56xd4q9_41rd7knts2r80000gn/T/jl_JlohZB.o -ljulia`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error at ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool) at ./process.jl:440
 [3] run at ./process.jl:438 [inlined]
 [4] run_with_env at /Users/rss/.julia/packages/PackageCompiler/AerNj/src/PackageCompiler.jl:93 [inlined]
 [5] create_sysimg_from_object_file(::String, ::String) at /Users/rss/.julia/packages/PackageCompiler/AerNj/src/PackageCompiler.jl:465
 [6] create_sysimage(::Symbol; sysimage_path::String, project::String, precompile_execution_file::Array{String,1}, precompile_statements_file::String, incremental::Bool, filter_stdlibs::Bool, replace_default::Bool, cpu_target::String, script::Nothing, base_sysimage::Nothing, isapp::Bool) at /Users/rss/.julia/packages/PackageCompiler/AerNj/src/PackageCompiler.jl:434
 [7] top-level scope at none:1
```

```

# ls -l /var/folders/n_/h8tm56xd4q9_41rd7knts2r80000gn/T/jl_JlohZB.o
-rw-r--r--  1 rss  staff  2758949944 Mar 18 09:54 /var/folders/n_/h8tm56xd4q9_41rd7knts2r80000gn/T/jl_JlohZB.o

```

```
Julia Version 1.5.4
Commit 69fcb5745b (2021-03-11 19:13 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_COPY_STACKS = 1


gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
```

There are two issues here:

1. Why julia collected .so is so huge?
2. What is to do to link it on MacOS. That part is related to gcc.

To reproduce it just unpack the archive and run ./precompile.sh

sorry for double pack but it is github restriction for zip only.

**Comment by rssdev10** [comment]
```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, broadwell)
```

updated Julia. The issue is still there.

**Comment by StefanKarpinski** [comment]
The 2GB limit suggests this might be an issue with a 32-bit `int` in C or `Int32` in Julia overflowing. My suspicion is the former since we're fairly careful to use `Int` rather than `Int32` in Base Julia. Might not even be Julia-specific — there's probably a lot of C/C++ tooling involved that isn't well-tested on huge shared libraries.

**Comment by Keno** [comment]
Looks more like a code model issue. IIRC we select the small code model (jumps are within 2GB) when generating the sysimage under the assumption that it won't be this large. (https://github.com/JuliaLang/julia/blob/83f3be9891fcdc356c765280140cd4348e79b49c/src/aotcompile.cpp#L495)

**Comment by rssdev10** [comment]
Any ideas why the sysimage is so huge? The precomple.jl is not so terrible. There are multiple methods of the `language_files` function but the function is simple - https://github.com/JuliaText/Embeddings.jl/blob/306c04bead62b32873dedbc2609c74c4ca34306b/src/Embeddings.jl#L37

[occ_precompile.jl.txt](https://github.com/JuliaLang/PackageCompiler.jl/files/6235536/occ_precompile.jl.txt)

**Comment by KristofferC** [comment]
You are saving some huge data inside the package. Just precompiling the package creates a 2.5GB ji file. Load the data at runtime, not at precompile time.

**Comment by rssdev10** [comment]
Do you mean, the place for temporary data storing is inside the package directory? Or is it because of size of data loaded into RAM? FastText takes almost 4GB....

**Comment by KristofferC** [comment]
What PackageCompiler roughly does is serialize the state of the package as it is when it is loaded. If you read in and save a huge data file to a local variable, then that will have to go into the .ji file or the sysimage.

**Comment by rssdev10** [comment]
The issue, to run the tests properly and have all the methods trace, I need to load some data.... In that specific case I can try to load some other dateset which is less, but anyway it is big. It is pretty typical for language models.... The method `cache_data` in the sample is just a wrapper implemented with `JLD2` over Julia data structures generated by `load_embeddings`.

Is anyway to markup a variable for PackageCompiler to don't put it inside the binary?

**Comment by KristofferC** [comment]
It is fine to load data. Just load it in your test code for example. But don't load it into your package (at precompile time).

**Comment by rssdev10** [comment]
Sounds like something I'm doing wrong... I thought that all the tests with all the methods must be ran in the process of the package compiling while jl-precompile file is generated... In the stage:
```
julia --project=@. --trace-compile=sysimage/occ_precompile.jl test/runtests.jl
```

And again, if I'm not loading the models, I cannot be sure that all the code is executed due to hidden zero checks.

**Comment by KristofferC** [comment]
Do you specifically want to precompile these methods:

```
get_embedding(word)
vectorize(str::String)
calc_distance(strings::Vector{String}, point::String)
```

or just what they call?

To me it looks like you should pretty much put everything inside `TwoGbCompilerIssue.jl` into the `runtests.jl` file.

**Comment by rssdev10** [comment]
See, the basic sample is from here - https://github.com/JuliaText/Embeddings.jl#basic-example

`calc_distance(strings::Vector{String}, point::String)` is the only what I need outside the package. And, actually, this is the only method which I call from runtests.jl

**Comment by rssdev10** [comment]
Talking about another dataset, I meant I can replace the current load of FastText by some simplified dataset. Definitely with some rewriting of the code. But again, I'm not getting how to separate the part which is just processing the data and anothe one which is loading the data. If `load_embeddings(FastText_Text)` call must be outside the package, technically I can do it too. As a method which is initializing the `embtable`. Does it work?

Like here:
```julia
using TwoGbCompilerIssue
using Test

TwoGbCompilerIssue.init_embtable(
  cache_data(joinpath(tmp, "fasttext.jld2"), "embeddings") do
    load_embeddings(FastText_Text)
  end
)

@testset "TwoGbCompilerIssue.jl" begin
  strings = [
    "Java", "Java programmer", "Julia language", "Julia programmer",
    "cpp", "programming", "Ruby", "Ada",
    "carrot", "beet", "cucumber", "Cucumber"
  ];

  res = TwoGbCompilerIssue.calc_distance(strings, strings[1])

  @assert !isempty(res)

  @show res
end

```

**Comment by rssdev10** [comment]
BTW, if the sysimage is something like a full memory dump, how is about adding some mechanism to exclude values from binaries? E.g. some method like `data_transient(embtable)` for registering transient objects inside the package. Or, maybe, some keyword for these variables.

**Comment by KristofferC** [comment]
What the sysimage basically is is a dump of the state of Julia after the package has been loaded. You can set variables to e.g. `nothing` in the end if you don't want them to get serialized but the code you have posted is a bit unusual because it loads these data files *at compile time*.

**Comment by rssdev10** [comment]
Ok, thanks. Now, I got it. I didn't actually distinguish "compile time" and run with all the tests for tracing calls. The term 'compile time' is confusing here comparing with other languages. Will try to do some code refactoring.

Also, it would be really good to have some set of sample projects with binary compiling and use it for tutorials including samples of bad practices. For that sample code, I can add a web service wrapper if it is interesting for somebody. Actually it was the primary purpose of compiling - build a standalone service that might be activated from binaries from a Docker-container.

**Comment by rssdev10** [comment]
Sharing some thoughts about the issue.

1) Regarding the 2GB restriction. When we are talking about a service in Kubernetes with elastic scalability, we are interested in the minimal activation time. In that case, all the memory dump is better than loading data from any other caches. NLP projects based on NN are always memory consumptive due to language models. I don't think that is it possible to have NN-based project with less than 2 GB RAM. So, for that use case, it would be good to have the ability to build huge binaries.
The simplest way how to allow programmers to build huge binaries is just to add a key `mcmodel` to Julia CLI and propagate it to gcc - https://gcc.gnu.org/onlinedocs/gcc-10.2.0/gcc/x86-Options.html#x86-Options . Or use default values as now if the option is absent. Another way is to select the value on the package compiling stage accordingly to real memory consumption.

2) Regarding the size of sysimage and my misunderstanding. `PackageCompiler` refers by the name to a process of code compiling. So, I expected that it is a dump of generated code but not a full memory dump. Just checked in the documentation - https://julialang.github.io/PackageCompiler.jl/dev/ - the fact of data dumping is not clear mention.
I don't know how hard is it, but if the final statistic is shown, that might be really good to catch what exactly was dumped. E.g.:
```
Package compiling statistic:
Code dumped:
  xxx methods
  xxx binary code size
 
Data dumped:
  yyy variables
  yyy data memory size
  
Final library size - zzz
```
After that, it is hard to don't understand the dump contains all the data too.

3) Regarding the removing of unnecessary values from the dump on the package compiling. One way is to add a callback method that is activated if exists, before starting memory dumping. Like:
```julia
module Abc
#...
function __package_compiler_before_data_dumping__()
  # embtable = nothing
end
#...
end
```

**Comment by KristofferC** [comment]
> I don't think that is it possible to have NN-based project with less than 2 GB RAM. So, for that use case, it would be good to have the ability to build huge binaries.

The point is that you shouldn't store this inside compiled package itself. It is like having an executable that is 2 GB big. Instead you store your data inside data files (e.g. artifacts).

I think there isn't really much to do here.
