### ISSUE TITLE
Show progress during creating system image object file

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/PackageCompiler.jl#504]
Is there anything that can be hooked into to get some sense of progress during
```
[ Info: PackageCompiler: creating system image object file, this might take a while...
```

Even if it was a counter, it'd be nice to have some feedback

**Comment by KristofferC** [comment]
I guess a spinner could be added.

**Comment by junglegobs** [comment]
I'm not sure how much useful information you could give on progress, but at least it could be written which package is being compiled if there is more than one?

**Comment by KristofferC** [comment]
Folding this into https://github.com/JuliaLang/PackageCompiler.jl/issues/318 since we don't really have a way to get proper progress right now.
