### ISSUE TITLE
Allow setting minimum opt level with new `--min-optlevel` flag

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/PackageCompiler.jl#506]
Given sysimage generation isn't as time sensitive, the user may wish to make compilation try harder to optimize than the package allows due to module-specific max opt levels.

The new flag `--min-optlevel` added in https://github.com/JuliaLang/julia/pull/39536 allows setting a minimum opt level to override these.

Perhaps a kwarg could be provided to set this, if the user desires?

**Comment by bcmichael** [comment]
I've been poking around in the internals trying to understand how system images are generated. I'm a little out of my depth here, so I may have this wrong, but my understanding is that when generating the object code output for the sysimg all of the method specializations are bundled up into an LLVM module and then the native code generation happens all together in jl_dump_native. jl_dump_native has a hardcoded setting for aggressive optimization aka O3. Are you sure that compilation for a system image actual obeys module specific optimization levels?

**Comment by IanButterworth** [comment]
I'm actually not sure. I had assumed that if a julia user can't override the `@optlevel` then PackageCompiler can't

**Comment by bcmichael** [comment]
I just tested this, which I probably should have done before my previous comment. I put together a very simple module:

```
module TestOpt
Base.Experimental.@optlevel 0 

function test(x)
    y=0
    for n=1:1000
        y+=x
    end
    return y
end

end
```

If I make a system image with that and an appropriate precompile statement for the test function on an Int then when I load up julia with that sysimg code_native shows that the compiler has optimized out the loop. If you just load up that module without compiling it into a sysimg then the O1 means that the loop does not get compiled out.

**Comment by IanButterworth** [comment]
Ok.. That seems to settle it. Thanks for checking. 

I'll close this issue and ask on the julia PR whether it should be reverted given this was the only use-case I had in mind.
