### ISSUE TITLE
Cant use PyPlot in Julia - LLVM ERROR: Symbols not found: { ccalllib_python38.dll2050 }

### ISSUE THREAD

**Issue by Roy3885** [JuliaLang/PackageCompiler.jl#507]
I'm new to Julia and I tried to add PyPlot for a script.jl I'm writing.
So I added Matplotlib to python and used Pkg.add("PyPlot") in Julia.

If I now use the command
using PyPlot
in my script.jl and compile it, I get this error: 

LLVM ERROR: Symbols not found: { ccalllib_python38.dll2050 }

And also Julia exits.
My OS is Windows.

Help would be gladly appriciated! ;)

**Comment by KristofferC** [comment]
What Julia version are you using?

**Comment by KristofferC** [comment]
I think this is a dup of https://github.com/JuliaLang/PackageCompiler.jl/issues/468
