### ISSUE TITLE
Error in create_app

### ISSUE THREAD

**Issue by gitjulspat** [JuliaLang/PackageCompiler.jl#510]
Getting error while trying to run create_app as 
ERROR: IOError: open: no such file or directory (ENOENT)
 ..
   bundle_artifacts(::Pkg.Types.Context, ::String) at PackageCompiler.jl:784
 

Using Windows 10 Julia Version 15.4

**Comment by KristofferC** [comment]
Please provide enough information so that the issue can be reproduced.
