### ISSUE TITLE
Vararg representation change interaction with Vararg{?, N} workaround

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/PackageCompiler.jl#514]
It seems that the workaround in
 https://github.com/JuliaLang/PackageCompiler.jl/blob/bb934d131a9c5d8f7e288d78bc48e928345034dd/src/PackageCompiler.jl#L241-L243

depends upon the pre-1.7 representation of Vararg, e.g.
```
julia> foo = Tuple{typeof(+), Int, Int, Vararg{Int}}
Tuple{typeof(+), Int64, Int64, Vararg{Int64, N} where N}
```
whereas in 1.7 and on
```
julia> foo = Tuple{typeof(+), Int, Int, Vararg{Int}}
Tuple{typeof(+), Int64, Int64, Vararg{Int64}}
```
I think upstream is alright as the relevant code works over a parsed rather than textual form (https://github.com/JuliaLang/julia/blob/94b9d66b10e8e3ebdb268e4be5f7e1f43079ad4e/contrib/generate_precompile.jl#L366-L392).

**Comment by KristofferC** [comment]
Perhaps that piece of code should be extracted into a utility function into Julia Base and then PackageCompiler can re-use the same as Julia uses?
