### ISSUE TITLE
New inactive precompile statement warnings on 1.7+ (unexpectedly?) surfacing

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/PackageCompiler.jl#515]
Due to https://github.com/JuliaLang/julia/commit/93b89b9486c2f5b6f780d59405b26e810412308f, each inactive precompile statement now surfaces a warning, e.g.
```
┌ Warning: Inactive precompile statement
│   form = Tuple{typeof(+), Any, Any, Any, Vararg{Any}}
└ @ nothing nothing:0
```
where IIUC previously the code in
 https://github.com/JuliaLang/PackageCompiler.jl/blob/bb934d131a9c5d8f7e288d78bc48e928345034dd/src/PackageCompiler.jl#L244-L249

would have surfaced as debug info. Given the construction of the preceding try-catch-atdebug, I'm guessing that these warnings surfacing as such is not the expected/desired behavior?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/39905/files#diff-ec80afe9f8ff182765c73ed3fc35a103b561f873a52b1dfe1ce135e4e5f9a2cfR1822 is pretty annoying...

**Comment by Sacha0** [comment]
Ref. https://github.com/JuliaLang/julia/pull/41447#pullrequestreview-698212342. Thanks for picking this up Kristoffer! :)

**Comment by KristofferC** [comment]
Upstream should be fixed to not emit these now.

**Comment by Sacha0** [comment]
🎉 🙏
