### ISSUE TITLE
Creating a shared library for a module defined at runtime

### ISSUE THREAD

**Issue by dannys4** [JuliaLang/PackageCompiler.jl#518]
I'm attempting to develop a Julia package that takes a pure Julia object then compiles it, adds C bindings to it, and (ideally) creates a  `.so` object with those bindings. I've gone through the canonical example of [LibCG](https://github.com/simonbyrne/libcg), but the major difference is that I don't know which object the user would want to compile until Julia's runtime, so something like #490 probably doesn't *quite* fit the usecase. PackageCompiler seems to be the way to go, but this runtime issue presents a few major problems. Would I be able to perform this? Here are some major issues I've run into--
1. Incorporating a runtime object into what I want to compile (I have a stopgap measure and some ideas that are equivalent to copy/pasting into a temporary module)
2. Ensuring that my object doesn't get gc'd while C is using it (I'm not sure whether this would actually happen since I'm not familiar with the mechanics of PackageCompiler and what it makes into a `.so`, but it's easily foreseeable so I'm using `global`s now)
3. Making the module that holds the runtime object into a format that PackageCompiler accepts (it seems like just a module isn't quite enough, I need to have it be a fully fledged package or else I get that `ERROR: package(s) temporaryModule not in project`)

I believe this is a feature request because I can't find any examples to do this out there, but if the functionality exists to solve problem 3 at the very least, I'd be more than happy.

**Comment by KristofferC** [comment]
>  that takes a pure Julia object then compiles it

It is unclear to me what this means. What does "compiling a pure Julia object" mean?

>  but the major difference is that I don't know which object the user would want to compile until Julia's runtime, so something like #490 probably doesn't quite fit the use-case.

You can still do JIT, so that shouldn't be too big of a problem.

Some things that would allow for further assistance:

- Could you show the desired code that the julia object would be called with from C? That would show what `@ccallable` functions you would need to implement.
- Could you get some minimum working example of the juila code you want to compile?

**Comment by dannys4** [comment]
Sure! Below, I have a minimal (nonworking) example of what I'm trying to do that shows the issues I mention.

```julia
using PackageCompiler

module Foo

arr = Vector{Cfloat}(undef, 1)

function def_arr(new_arr::Vector{Cfloat})::Cint
    global arr = new_arr
    0
end

Base.@ccallable function get_idx_foo_arr(i::Cint)::Cfloat
    return arr[i]
end

end

function precompileModule(arr::Vector{Cfloat})
    Foo.def_arr(arr)
    PackageCompiler.create_sysimage(Symbol[:Foo], sysimage_path = "tmp.so")
end

vec = Vector{Cfloat}(undef, 10)
vec .= 2.5
precompileModule(vec)
```

I believe issues 1 & 2 from my original post are currently fixed by me just using a global `arr` in the `Foo` module, but I'd prefer avoiding the globals if possible. Issue 3 is still very prominent here-- obviously `Foo` is not a package, it's just a module. So, I get the error `ERROR: package(s) Foo not in project`. I can't find any resources on whether I can make a package on-the-fly either, but I also don't have the experience/knowledge necessary to know why I would need a full package instead of just a module here. This is close to creating an app, but I'm constrained to creating a shared object instead of an executable.

**Comment by dannys4** [comment]
Just want to bump this post-juliacon.

Is there any way to do this using the tools PackageCompiler is currently equipped with?

**Comment by KristofferC** [comment]
It is important to be clear about what PackageCompiler does. It takes a package and compiles the source code within that package (together with its dependencies) into a sysimage. So if you have dynamic code that you want to put into a sysimage you would need to go via writing that out to a temporary Julia package and create a sysimage based on that.

PackageCompiler is not a compiler in the sense that you can give it individual snippets of Julia code and create small shared libraries based on that

**Comment by dannys4** [comment]
I think that could work! So in this example, I'd need to do something like put `Foo.jl` in a subdirectory (say `FooDir`) with a sample `Project.toml` and do `Pkg.add("FooDir")`. Then have a secondary file that's basically what I put in my previous example and `include` it within the function. I'll try and post a MWE when I figure this out technically

**Comment by dannys4** [comment]
I've decided that a "MWE" isn't very minimal and is redundant with the new update to LibCG. When this was posted, LibCG was not using `create_library`, but `create_library` was more-or-less exactly what I was looking for, which allows for compiling a module at a specific directory.
