### ISSUE TITLE
Error on windows Julia 1.7 beta3

### ISSUE THREAD

**Issue by gitboy16** [JuliaLang/PackageCompiler.jl#521]
1/ I have been trying to follow the instructions here:
https://julialang.github.io/PackageCompiler.jl/dev/examples/plots/

It returns errors on windows with julia 1.7 beta3.
```julia
Cxx
LocalCoverage
0 dependencies succesfully precompiled in 10 seconds (265 already precompiled)

ERROR: the following 2 dependencies failed to precompile
```
The above 2 packages crash when I try to use them.

2/ I tried to follow the instruction there:
https://julialang.github.io/PackageCompiler.jl/dev/devdocs/sysimages_part_1/

I had errors at the steps: 2. Creating the sysimage shared library from the object file
Again under windows,  after running in Cygwin:
`x86_64-w64-mingw32-gcc -shared -o sys.dll -Wl,--whole-archive sys.o -Wl,--no-whole-archive -L"/cygdrive/d/julia-e76c9dad42/bin" -ljulia`

I have tried with `lib` instead of `bin`. I get a lot of errors that I cannot copy all here but here is an example:
```
/usr/lib/gcc/x86_64-w64-mingw32/10/../../../../x86_64-w64-mingw32/bin/ld: sys.o(text.o):./C:\buildbot\worker\package_win64\build\usr\share\julia\v1.7\Pkg\src/utils.jl:27: undefined reference to 'jl_f_expr'
```
Thank you

**Comment by gitboy16** [comment]
Similar issues as above on macos with julia 1.6 (including issues on Cxx and LocalCoverage)

**Comment by KristofferC** [comment]
Could you be a bit clearer on:

- What packages are you trying to put into the sysimage?
- Do you get the same error no matter what packages you true to put in the sysimage. Even with e.g. Example.jl?

Regarding 2) you are reading the developer documentation there which might be a bit out of date.

**Comment by gitboy16** [comment]
I was trying to put Plots into the sysimage. I was just following the example you have in your doc. I manage to do it after removing package Cxx and LocalCoverage which fail under 1.7 and 1.6. Not sure to understand why a failing installed package has a impact on building the sysimage. Maybe it is precompiling package before creating the sysimage. Anyway I manage to do it. Might be worth adding a warning in the doc regarding that point.

Regarding 2/ is the a non dev doc? Because I only see yhe dev one...

**Comment by KristofferC** [comment]
I think the precompilation error should be fixed now. Please try with `PackageCompiler#master` and report back.
