### ISSUE TITLE
sysimage compilation has started to error if precompilation fails

### ISSUE THREAD

**Issue by baggepinnen** [JuliaLang/PackageCompiler.jl#522]
Plotly.jl has long failed precompilation (for as long as I can remember), but nevertheless works without issues. I used to be able to compile a system image (without Plotly.jl), but after a recent `pkg> up` it not longer works since `PackageCompiler.create_sysimage` has started to error if precompilation errors. I assume that this means that as long as Plotly.jl is present in the emvironment, `create_sysimage` will fail.

Is this change intentional? If so, is there perhaps a way to work around the problem?

```julia
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4

(@v1.6) pkg> st PackageCompiler
      Status `~/.julia/environments/v1.6/Project.toml`
  [9b87118b] PackageCompiler v1.3.0
```

---

Edit: Pinning PackageCompiler to v1.2.5 let's me compile the sysimage as before.

**Comment by KristofferC** [comment]
This should be fixed now, please comment if it is still an issue (with the master branch of PackageCompiler).
