### ISSUE TITLE
Invalid CPU name "x86_64" in docker on M1

### ISSUE THREAD

**Issue by mmiller-max** [JuliaLang/PackageCompiler.jl#528]
The build process shown in the MWE below has been working fine for me for a while, but I've just started working on an M1 MacBook and it's now erroring for me with
```
#9 11.34 [ Info: ===== Start precompile execution =====
#9 11.54 [ Info: ===== End precompile execution =====
#9 12.33 [ Info: PackageCompiler: creating system image object file, this might take a while...
#9 12.40 fatal: error thrown and no exception handler available.
#9 12.40 ErrorException("Invalid CPU name "x86_64".")
```

If I run the script not in docker (`$ julia deploy/packagecompile.jl`) it works fine. I need the `cpu_target` setting for compatibility with other systems.

### Versions

Unfortunately `versioninfo` didn't work at build time (got a not defined error) but if I remove the `cpu_target` and let it build, inside the image I get
```Julia
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (aarch64-unknown-linux-gnu)
  CPU: unknown
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, generic)
Environment:
  JULIA_GPG = 3673DF529D9049477F76B37566E3C7DC03D6E495
  JULIA_PATH = /usr/local/julia
  JULIA_PROJECT = @.
  JULIA_VERSION = 1.6.2
```

Docker Desktop: Version 3.5.2 (3.5.2.18) for M1

### MWE

```Julia
pkg> dev Example
```

In Example, add the following files/folder

```
Example.jl
- deploy
  - Project.toml
  - precompile.jl
  - packagecompile.jl
-Dockerfile 
```
Example.jl/deploy/Project.toml
```toml
[deps]
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
```
precompile.jl
```Julia
import Example
include(joinpath(dirname(pathof(Example)), "../test", "runtests.jl"))
```
packagecompile.jl
```Julia
using Pkg

Pkg.activate(@__DIR__) # Use the Project.toml in this folder
Pkg.develop(path=dirname(@__DIR__)) # Develop the local version of the package we are including in the sysimage
Pkg.instantiate()
versioninfo()

using PackageCompiler

create_sysimage([:Example];
    sysimage_path="Example.so",
    precompile_execution_file="deploy/precompile.jl",
    cpu_target="x86_64",
)
```
Dockerfile

```dockerfile
FROM julia:1.6.2

RUN apt-get update && apt-get install -y gcc

WORKDIR /app

COPY . .

ENV JULIA_PROJECT @.
RUN julia deploy/packagecompile.jl
```
Run this command
```
$ docker build .
```

**Comment by yuyichao** [comment]
Use generic instead.

**Comment by yuyichao** [comment]
X86 cpu will not work on non x86 architecture so no it’s impossible to make it work as your version string clearly shows aarch64.

if you want to compile a x86 image using an aarch64 Julia, no that will not work.

if you want to compile an image for aarch64 or x86 (or anything else) then using generic as the target as I said should work. It basically never make sense to hard code x86 there anyway….

**Comment by mmiller-max** [comment]
I've just test it and building with generic does not seem to work, which is why I previously had it set to x86.

When built with generic on an x86 ec2 worker, when I try to load it on M1 MacBook I get this error:

```
% julia -JImage.so            
ERROR: could not load library "/Users/.../Image.so"
dlopen(/Users/.../Image.so.dylib, 6): image not found
```

**Comment by mmiller-max** [comment]
@yuyichao just bumping the above error, anything I can do to enable an image built on ec2 linux to work in an M1 MacBook given that generic doesn't seem to work?

**Comment by yuyichao** [comment]
It’s unclear what you want. The error message above shows macOS path and the original post shows aarch64 linux. Whatever you build on a x86 Linux will not work on either of these no matter what you set and I never said generic will work for this. Generic would only work when you are on the same platform (including architecture).

**Comment by mmiller-max** [comment]
>  I never said generic will work for this

I'm not trying to accuse you of anything, I'm just trying to understand system images more as I'm clearly not an expert user of them

> Generic would only work when you are on the same platform (including architecture)

This is what I didn't understand, I didn't appreciate the limits of generic/how exactly system architectures restricted things. It would be useful for the docs to include this (I tried looking but couldn't find it).

To be clear, I want to build Julia sysimages in docker in a CICD pipeline (x86). I want the images to run both on a Linux cloud worker and on my M1 Mac (both in a container and not), which replicates the workflow that I used to do with my Intel Mac (for which the target being set to `x86_64` seemed to be the key to get working). For the "not in the container" use case, I thought Rosetta would be able to emulate the x86 architecture and enable the use of the sysimage, but I get the error above (missing dylib). For the "in a container" use case, I think I will need some form of emulation to run a x86 docker image on the M1.



In this case I think the solution is to use dockers emulation capabilities

**Comment by yuyichao** [comment]
> I'm not trying to accuse you of anything

I wasn’t trying to imply that you did either. But I believe that’s where the misunderstanding is so I think it was worth pointing out.

> This is what I didn't understand, I didn't appreciate the limits of generic/how exactly system architectures restricted things. It would be useful for the docs to include this (I tried looking but couldn't find it).

this is essentially the same limitation when compiling anything. (Or it’ll be cross compilation). Nothing too much to document here but having some short note is certainly fine.

**Comment by mmiller-max** [comment]
Thanks for your help with this!
