### ISSUE TITLE
using shared libraries from other languages

### ISSUE THREAD

**Issue by visr** [JuliaLang/PackageCompiler.jl#53]
I'm interested in using this package for creating shared libraries that can be used from Fortran (or any other language that supports calling C-exported shared libraries).

Currently the shared libraries created here do contain the `@ccallable` functions given in the julia script. But if I'm correct these cannot be used directly because you need to call `jl_init` first, and anything else mentioned in the embedding docs. This is done in `program.c`, which is compiled to executable.

If I want to be able to call simple julia functions like `Base.@ccallable f(x::Float64)::Float64 = 2.0 * x` from a shared library, how would I go about that? Modify the `program.c` to compile as shared library and provide the initialization functions from `libjulia` there as well? If anyone could provide a minimal example that would be great.

I tried things like:
```c
extern double f(double a);

#ifdef _OS_WINDOWS_
__declspec(dllexport) __cdecl
#endif
void my_jl_init(void)
{
    jl_init();
}

#ifdef _OS_WINDOWS_
__declspec(dllexport) __cdecl
#endif
double my_f(double a)
{
    return f(a);
}
```

But while `my_jl_init` seemed to work, if I do `my_f` after, it segfaults. Is this more or less the right approach however?

**Comment by NHDaly** [comment]
Is this related to the work done here?:
https://github.com/JuliaLang/PackageCompiler.jl/issues/25

I agree, this would be very cool.

**Comment by visr** [comment]
Yeah it is related, especially the [`emit_shared_julia`](https://github.com/JuliaLang/PackageCompiler.jl/pull/26/commits/7dbf616ecfe78b1075dea5815e8493db67b2679d#diff-0aa9ae275a6a8eefc56754c9d8755ef4R71), maybe I should try to adapt #26 (ignoring the Python specific parts).

If that would work it is probably worth it in itself, even if the python-c extensions aren't working yet.

**Comment by SimonDanisch** [comment]
That sounds like a good idea! Let me know if you have any questions or need help to get that PR running for e.g. C!

**Comment by visr** [comment]
To be honest I'm struggling with getting a simple example shared library to work manually. If I can get that to run, I agree it would be nice to automate in a PR.

Is my first post more or less along the right lines? Maybe I should not try first on Windows haha.

**Comment by phlavenk** [comment]
See if #122 fulfils your needs - is already part of the 0.5.0 release for 0.7/1.0. In that case, the issue can be closed.

**Comment by visr** [comment]
Ah great, looks like it does! Thanks for letting me know.
