### ISSUE TITLE
MyLib example doesn't work

### ISSUE THREAD

**Issue by kyak** [JuliaLang/PackageCompiler.jl#534]
When trying to run `make` in `examples/MyLib`, the following error is thrown:

```
$ make
julia --startup-file=no --project=. -e 'using Pkg; Pkg.instantiate()'
julia --startup-file=no --project=build -e 'using Pkg; Pkg.instantiate(); include("build/build.jl")'
Creating library in /tmp/jl/PackageCompiler.jl/examples/MyLib/build/../../MyLibCompiled
┌ Warning: it is not recommended to create an app without a preexisting manifest
└ @ PackageCompiler ~/.julia/packages/PackageCompiler/drmGx/src/PackageCompiler.jl:919
ERROR: LoadError: IOError: open("/usr/lib/cups/backend/cups-brf", 0, 0): permission denied (EACCES)
Stacktrace:
 [1] bundle_julia_libraries(dest_dir::String, library_only::Bool)
   @ PackageCompiler ~/.julia/packages/PackageCompiler/drmGx/src/PackageCompiler.jl:1027
 [2] _create_app(package_dir::String, dest_dir::String, name::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, audit::Bool, force::Bool, cpu_target::String; library_only::Bool, c_driver_program::String, julia_init_c_file::String, header_files::Vector{String}, version::Nothing, compat_level::String)
   @ PackageCompiler ~/.julia/packages/PackageCompiler/drmGx/src/PackageCompiler.jl:947
 [3] create_library(package_dir::String, dest_dir::String; lib_name::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, audit::Bool, force::Bool, header_files::Vector{String}, julia_init_c_file::String, version::Nothing, compat_level::String, cpu_target::String)
   @ PackageCompiler ~/.julia/packages/PackageCompiler/drmGx/src/PackageCompiler.jl:883
 [4] top-level scope
   @ /tmp/jl/PackageCompiler.jl/examples/MyLib/build/build.jl:9
 [5] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [6] top-level scope
   @ none:1
in expression starting at /tmp/jl/PackageCompiler.jl/examples/MyLib/build/build.jl:9
make: *** [Makefile:13: "../MyLibCompiled"/lib/libmylib.so] Error 1
```

I can confirm that `/usr/lib/cups/backend/cups-brf` is not world-readable. But I'm pretty sure that this is how it should be.

**Comment by KristofferC** [comment]
Note the installation instructions: https://julialang.github.io/PackageCompiler.jl/dev/#Installation-instructions-1

> It is strongly recommended to use the official binaries that are downloaded from https://julialang.org/downloads/. Distribution-provided Julia installations are unlikely to work properly with this package.

Is that the case for you?

**Comment by kyak** [comment]
Yes, this is the case for me. Nevertheless, I'm reluctant to installing packages not from my distribution's package manager. I don't think this is a good advice from your side either.

Is there any reason why my distribution provided Julia v1.6.2 (on Arch Linux) should be different from what you package and distribute?

**Comment by KristofferC** [comment]
> I'm reluctant to installing packages not from my distribution's package manager.

Ok, that's up to you.

> I don't think this is a good advice from your side either.

What do you mean by good advice? I am saying that the package doesn't work properly on non-official Julia installations. That is not an advice, that is just a fact.

> Is there any reason why my distribution provided Julia v1.6.2 (on Arch Linux) should be different from what you package and distribute?

Clearly there is some difference, otherwise, there would be no point to the distribution provided installation. It is probably different in how the libraries that Julia depends on are structured. The point of PackageCompiler's `create_app` and `create_library` is to get something that works on other machines without requiring a Julia installation on those machines. This requires bundling a bunch of libraries Julia depends on. The official Julia installation has been set up so that if we use the bundled libraries in it, things work. That is unlikely the case for distribution installations.

**Comment by kyak** [comment]
Thanks!
