### ISSUE TITLE
InitError and artifact folder

### ISSUE THREAD

**Issue by bradcarman** [JuliaLang/PackageCompiler.jl#544]
I'm attempting to create an app that has FFTW.jl as a dependency (I'm using the latest version v1.4.5). I can see that the app folder contains a folder `artifacts\b7dd1809d0626eac3bf6f97ba8ccfbb6cc63c509\bin\libfftw3-3.dll`.  But this file is not included in the `bin` folder.  I'm assuming that `libfftw3-3.dll` should be placed in the `bin` folder.  Is that correct?  Or should the app be distributed with both the `bin` and `artifacts` folders?  

Additionally, if I copy the `libfftw3-3.dll` file from the artifacts folder to the bin folder, I still end up getting an 

`InitError(mod=:FFTW_jll, error=ErrorException("Artifact "FFWT" wsa not installed correctly...`

I'm assuming this is a bug with PackageCompiler, but maybe something is not correct with the FFTW.jl use of the Artifact system.

**Comment by KristofferC** [comment]
> I'm assuming that libfftw3-3.dll should be placed in the bin folder. Is that correct?

No, artifacts should not be in the `bin` folder, they should come shipped in the `artifacts` folder.

Can you provide the precise commands you are running and what error you hit?

**Comment by bradcarman** [comment]
OK, I think I see the problem.  What I am trying to do is create a "Portable System Image".  I thought I could use the `create_app()` function for this.  So for example I am using:

`create_app("FFTWPackage", "FFTWPackageCompiled"; force=true, cpu_target="core2")`

Where `FFTWPackage` is

```julia
module FFTWPackage
using FFTW

function julia_main()::Cint
    println("Hello World!")
    y = fft(rand(100))
    println(y)
    return 0
end

end # module
```

When I create this app, it runs fine, so I can do:

```shell
bin> FFTWPackage.exe
Hello World!
ComplexF64[48.29591202577243 + 0.0im, 2.6175125666243817 + 0.6061253972272942im, -3.056669141453041 ....
```

But, what I thought I could do, but doesn't work is:

```shell
bin> julia -JFFTWPackage.dll
```

Which gives the error:

```shell
fatal: error thrown and no exception handler available.
InitError(mod=:FFTW_jll, error=ErrorException("Artifact "FFTW" was not installed correctly. Try `using Pkg; Pkg.instantiate()` to re-install all missing resources."))
error at .\error.jl:33
...
```

Is there anyway I can launch the app version of Julia with the created system image which can load the portable assets?

**Comment by bradcarman** [comment]
OK, I sorted it out.  I need to set the `JULIA_DEPOT_PATH` before launching julia with the app system image.  On Windows (starting from the app output directory) I did...

```shell
Compiled>set JULIA_DEPOT_PATH=.&& bin\julia -J bin\FFTWPackage.dll
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.1 (2021-04-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> FFTWPackage.julia_main()
Hello World!
ComplexF64[48.90104886444801 + 0.0im, 0.04000811104311941 - 0.834988070796802im, ....
```

**Comment by KristofferC** [comment]
Yes, one of the things the executable does is to set up the depot path.
