### ISSUE TITLE
Rebuild docs

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/PackageCompiler.jl#562]
I think the docs haven't been rebuilt recently. Currently, I see this 
![image](https://user-images.githubusercontent.com/29157027/134968352-d41be09f-ed42-42b2-9f67-b95896c0929f.png)
in the SysImage docs which is now a MethodError, but when I went to edit the `.md` file and make a PR, I saw it had already been updated in https://github.com/JuliaLang/PackageCompiler.jl/commit/8bdcc8540d7cb7634a63317261a80b738e8211ee

**Comment by fredrikekre** [comment]
That's the docs for the master branch I believe.

**Comment by KristofferC** [comment]
Yeah, should probably start versioning docs...

**Comment by IanButterworth** [comment]
I was just burned by this. The badge on the readme is `docs: stable` but the docs are master only

**Comment by KristofferC** [comment]
🔥 OK let's try fix it.

**Comment by KristofferC** [comment]
I pushed a new tag, the action ran: https://github.com/JuliaLang/PackageCompiler.jl/runs/3737361588?check_suite_focus=true things seem to have deployed but yet only `dev` in the version selector (https://github.com/JuliaLang/PackageCompiler.jl/blob/gh-pages/versions.js)...

**Comment by KristofferC** [comment]
Fixed
