### ISSUE TITLE
The change of compiler in 1.7.4 is breaking situations where one of g++/clang++ isn't installed

### ISSUE THREAD

**Issue by mmiller-max** [JuliaLang/PackageCompiler.jl#606]
Hi, in our pipelines we install `gcc` and use PackageCompiler to build sysimages. [This change](https://github.com/JuliaLang/PackageCompiler.jl/commit/b000c9e701210deb517885a3fe61e7d299e8ff14#diff-ec15186e80d0dd77de7[…]1df407b96f680c11cf847R682) with 1.7.4 makes it look for `g++` rather than `gcc` which has now broken all of our pipelines.

Should this have been a breaking version change?

**Comment by mmiller-max** [comment]
> Well, it is a bugfix since using gcc was a bug and caused linking error in certain cases 

This makes sense, but for it not to be breaking it assumes that the system on which people are compiling packages has `g++` installed. E.g. [this template](https://github.com/quinnj/MusicAlbums.jl/blob/master/Dockerfile) which is commonly used for microservices won't work now without changing the compiler being installed in the dockerfile.

Clearly switching to `g++` is better as it solves some issues, but perhaps letting it fall back to the old compilers when `g++`/`clang++` are not installed along with a warning could stop it breaking?

> Is it difficult for you to also get `g++`?

No, I just need to update several dockerfiles accordingly

> Also, for work that is very important to be reproducible, I would check in a `Manifest.toml `

We are careful to use `compat` entries so that (in theory) no breaking changes can be introduced. Yes checking in the `Manifest.toml` would ensure this completely, but feels like with semantic versioning this is overkill. I guess its a trade-off between stability and maintenance overhead

**Comment by KristofferC** [comment]
@mmiller-max, can you try out https://github.com/JuliaLang/PackageCompiler.jl/pull/608?
