### ISSUE TITLE
Allow `create_pkg_context` with only a Manifest.toml

### ISSUE THREAD

**Issue by oscardssmith** [JuliaLang/PackageCompiler.jl#629]
For machine interaction with PackageCompiler it would be nice to be able to only specify a Manifest.toml. This isn't a major problem, but should be pretty easy to do given that the manifest contains all the deps and versions needed to know how to make a sysimage.

**Comment by KristofferC** [comment]
You can just use the package manger to instantiate out the project from it.

```jl
~/JuliaTests/OnlyManifest
❯ ls
Manifest.toml

~/JuliaTests/OnlyManifest
❯ julia --project -q
(JuliaTests) pkg> activate .
  Activating new environment at `~/JuliaTests/OnlyManifest/Project.toml`

(OnlyManifest) pkg> instantiate

~/JuliaTests/OnlyManifest
❯ ls
Manifest.toml  Project.toml

~/JuliaTests/OnlyManifest
❯ cat Project.toml 
[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
```

**Comment by oscardssmith** [comment]
Fair enough.
