### ISSUE TITLE
relative path

### ISSUE THREAD

**Issue by liushang0322** [JuliaLang/PackageCompiler.jl#630]
how can i use this package to create relative path sysimage

**Comment by KristofferC** [comment]
I don't know what this means.

**Comment by liushang0322** [comment]
I need to use an absolute path when creating sysimage, but I want to be able to use it on other computers after creating sysimage, so I want to create sysimage in a relative path, can it be done？ thank you

**Comment by KristofferC** [comment]
Just send the sysimage over ti the other computer and use it? You need to better describe what your end goal is, what you have tried so far, and what problems you encounted.

**Comment by liushang0322** [comment]
As you said, I want to be able to create a sysimage, and then package it with the library I developed, so that others can quickly use the package when using the libraries included in these sysimages. My purpose is to create a universal sysimage to speed up the loading of the package when used by others, not just when I use the package myself.

**Comment by adigitoleo** [comment]
It should be possible:

1. Create the sysimage locally using an absolute path.
2. Ship the sysimage with your package.
3. Tell your users to load it from the installed path (`julia -J` accepts relative paths, if that was your concern).

You could provide a shell script to do (3) automatically if you really want.

Alternatively you could just include some instructions in your documentation on how to create a sysimage for your package. Then users who want to have faster load times can compile the sysimage themselves, however they will need to keep it up to date.

**Comment by liushang0322** [comment]
thank you so much!!!!!!!
