### ISSUE TITLE
Error when using standard library: "ArgumentError: Package ReSolver does not have Dates in its dependencies"

### ISSUE THREAD

**Issue by jonbarkerlondon** [JuliaLang/PackageCompiler.jl#648]
Hi,

When attempting to `create_app` where the module has a `using Dates` statement, I get the following on compile:

![image](https://user-images.githubusercontent.com/7076476/145266587-e21b82f2-b6fd-4b6f-815e-647bf61f4f5e.png)

Am I doing something stupid?

Jon

**Comment by jonbarkerlondon** [comment]
Reproduction sample:

`
module ReSolverTest
	using Dates

    function julia_main()::Cint  
		println("test")
		println(now())
    end

end # module

`

Err: 
`PackageCompiler: compiling incremental system imageArgumentError: Package ReSolverTest does not have Dates in its dependencies`

**Comment by KristofferC** [comment]
Do you have Dates in your project file?

**Comment by jonbarkerlondon** [comment]
> Do you have Dates in your project file?

Weird. I thought that since Dates is STDLIB then you can't add it to the project file. Obviously I'm wrong. Thanks for your help!
