### ISSUE TITLE
SysImage output gets stuck in recursive stack trace on 1.7.0

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/PackageCompiler.jl#651]
Towards the end of sysimage generation (based on duration, compared to 1.6.4) I'm seeing PackageCompiler get stuck printing this indefinitely
```
isLoadFromConstGV at /buildworker/worker/package_linux64/build/src/llvm-late-gc-lowering.cpp:1153
isLoadFromConstGV at /buildworker/worker/package_linux64/build/src/llvm-late-gc-lowering.cpp:1153
isLoadFromConstGV at /buildworker/worker/package_linux64/build/src/llvm-late-gc-lowering.cpp:1153
isLoadFromConstGV at /buildworker/worker/package_linux64/build/src/llvm-late-gc-lowering.cpp:1153
```

I don't have a public MWE yet

**Comment by IanButterworth** [comment]
Perhaps this should go on JuliaLang/julia ?

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/PackageCompiler.jl/issues/643#issuecomment-985121240 I think. Yeah, we should report something upstream since it is likely there it has to be fixed.
