### ISSUE TITLE
create_library doesn't create mylib.dll for example on windows

### ISSUE THREAD

**Issue by ThummeTo** [JuliaLang/PackageCompiler.jl#653]
Hi,

I tested this with Julia 1.6.1 and 1.6.3 on a fresh Windows 10 (64-bit) and the latest release of PackageCompiler.jl (2.0.4). 

When cloning the repository and executing the `build.jl` inside the mylib-example, no errors are generated and everything runs as to expect. But in the end, there is no `mylib.dll` or `libmylib.dll` inside any location in the `target_dir` after executing the line:

```
PackageCompiler.create_library(".", target_dir;
                                lib_name="mylib",
                                precompile_execution_file=["$(@__DIR__)/generate_precompile.jl"],
                                precompile_statements_file=["$(@__DIR__)/additional_precompile.jl"],
                                incremental=false,
                                filter_stdlibs=true,
                                header_files = ["$(@__DIR__)/mylib.h"],
                            )
```

Can you reproduce this issue?

As far as I understand, this process should generate a `mylib.dll` or `libmylib.dll`.

Thank you & best regards!

**Comment by ThummeTo** [comment]
Content of target directory after command execution:

...\MyLibCompiled\bin
...\MyLibCompiled\include
...\MyLibCompiled\bin\julia.exe
...\MyLibCompiled\bin\libamd.dll
...\MyLibCompiled\bin\libatomic-1.dll
...\MyLibCompiled\bin\libbtf.dll
...\MyLibCompiled\bin\libcamd.dll
...\MyLibCompiled\bin\libccalltest.dll
...\MyLibCompiled\bin\libccolamd.dll
...\MyLibCompiled\bin\libcholmod.dll
...\MyLibCompiled\bin\libcolamd.dll
...\MyLibCompiled\bin\libcurl-4.dll
...\MyLibCompiled\bin\libdSFMT.dll
...\MyLibCompiled\bin\libgcc_s_seh-1.dll
...\MyLibCompiled\bin\libgfortran-5.dll
...\MyLibCompiled\bin\libgit2.dll
...\MyLibCompiled\bin\libgmp.dll
...\MyLibCompiled\bin\libgmp-10.dll
...\MyLibCompiled\bin\libgmpxx.dll
...\MyLibCompiled\bin\libgmpxx-4.dll
...\MyLibCompiled\bin\libgomp-1.dll
...\MyLibCompiled\bin\libjulia.dll
...\MyLibCompiled\bin\libjulia-internal.dll
...\MyLibCompiled\bin\libklu.dll
...\MyLibCompiled\bin\libldl.dll
...\MyLibCompiled\bin\libllvmcalltest.dll
...\MyLibCompiled\bin\libmbedcrypto.dll
...\MyLibCompiled\bin\libmbedtls.dll
...\MyLibCompiled\bin\libmbedx509.dll
...\MyLibCompiled\bin\libmpfr.dll
...\MyLibCompiled\bin\libmpfr-6.dll
...\MyLibCompiled\bin\libnghttp2-14.dll
...\MyLibCompiled\bin\libopenblas64_.dll
...\MyLibCompiled\bin\libopenlibm.dll
...\MyLibCompiled\bin\libpcre2-16.dll
...\MyLibCompiled\bin\libpcre2-16-0.dll
...\MyLibCompiled\bin\libpcre2-32.dll
...\MyLibCompiled\bin\libpcre2-32-0.dll
...\MyLibCompiled\bin\libpcre2-8.dll
...\MyLibCompiled\bin\libpcre2-8-0.dll
...\MyLibCompiled\bin\libpcre2-posix-2.dll
...\MyLibCompiled\bin\libquadmath-0.dll
...\MyLibCompiled\bin\librbio.dll
...\MyLibCompiled\bin\libspqr.dll
...\MyLibCompiled\bin\libssh2.dll
...\MyLibCompiled\bin\libssp-0.dll
...\MyLibCompiled\bin\libstdc++-6.dll
...\MyLibCompiled\bin\libsuitesparse_wrapper.dll
...\MyLibCompiled\bin\libsuitesparseconfig.dll
...\MyLibCompiled\bin\libumfpack.dll
...\MyLibCompiled\bin\libuv-2.dll
...\MyLibCompiled\bin\libwinpthread-1.dll
...\MyLibCompiled\bin\libz.dll
...\MyLibCompiled\bin\LLVM.dll
...\MyLibCompiled\bin\Remarks.dll
...\MyLibCompiled\bin\sys.dll
...\MyLibCompiled\include\julia_init.h
...\MyLibCompiled\include\mylib.h

**Comment by KristofferC** [comment]
It calls it `sys.dll` on Windows. I am not sure why. @kmsquire maybe knows.

**Comment by kmsquire** [comment]
Nope, the intention is for it to produce `my lib.dll`. I’ll take a look in a little while.

**Comment by kmsquire** [comment]
Okay, I see what happened.  There used to be a flag, `library_only`, that was checked when determining the name of the output library.  When the code was refactored to remove that flag, the condition setting the sysimg filename wasn't changed correctly.  I'll push a fix shortly.

**Comment by kmsquire** [comment]
Fix is in #655.

**Comment by ThummeTo** [comment]
I can confirm that #655 fixes the issue. Thank you very much!

Maybe this issues content could serve as future test? Checking that specific files (like `mylib.dll`, `julia.exe`, ...) are present (and maybe `filesize > x`) after the build process?

**Comment by KristofferC** [comment]
I started with some tests in https://github.com/JuliaLang/PackageCompiler.jl/pull/614 but it was quite annoying so I never finished it. It basically used Python to check that you could dlopen the resulting library and call functions within it. Happy if someone else can take it forward.

**Comment by ThummeTo** [comment]
I just had a look on the PR #614 and I was curious why you are using _Python CDLL_ instead of Julia native _Libdl dlopen_?

**Comment by KristofferC** [comment]
Because you are not allowed to load another sysimage in an existing julia session.
