### ISSUE TITLE
Unreasonably large executable size from `create_app`

### ISSUE THREAD

**Issue by AhmedAliStats** [JuliaLang/PackageCompiler.jl#660]
I am on Windows 10.
Julia v1.7.1
PackageCompiler v2.0.4

The code that I am running is
```
Pkg.generate("MyApp")
using PackageCompiler
create_app("MyApp", "MyAppCompiled", filter_stdlibs=true)
```

The contents of the app are
```
module MyApp

function julia_main()::Cint
	return 0
end

end # module
```

I am getting an executable app of approximately 419 MB.

Most of this is because of
![image](https://user-images.githubusercontent.com/51719814/151438041-04c71842-8cb9-46a1-bb85-c6c7c31e99eb.png)

Is this the expected size or something on my end?

Thank you very much.

**Comment by KristofferC** [comment]
This is expected. Julia currently has no good way to run code without these supporting libraries. But there is work in progress of trying to improve this.
