### ISSUE TITLE
package(s) MyPackage not in project

### ISSUE THREAD

**Issue by wly2014** [JuliaLang/PackageCompiler.jl#667]
Does PackageCompiler.jl support to compile my own package?
When I use `create_sysimage([:MyPackage], sysimage_path="sys_simple.so")`, and I get this error `package(s) MyPackage not in project`. I have created the package `MyPackage` and added its path to LOAD_PATH.
Thanks.

**Comment by sjkelly** [comment]
You need to add `MyPackage` to the currently activate project, or specify a new project like so: https://github.com/JuliaLang/PackageCompiler.jl/blob/067b441797cf19cf8eb42c913a1edc2e56fa5ff1/src/PackageCompiler.jl#L488-L489
