### ISSUE TITLE
`create_sysimage` fails on arm64 when using a precompile execution file

### ISSUE THREAD

**Issue by agcmoser** [JuliaLang/PackageCompiler.jl#670]
Hi, 

I want to create s sysimage of my own (private) package and this works fine when doing so using Julia 1.6.5 and macOS 11.6.2 (Big Sur) (Intel Mac). On my Mac I was able to create the sysimage with and without using the `precompile_execution_file` option. I generated the precompile file using the `julia --trace-compile=precompile_instructions.jl` and generating some representative work load on the REPL.

On my raspberry Pi 4 (with 8 GB RAM), however, I can only make a sysimge when not using the `precompile_execution_file` option. I also use Julia 1.6.5. PackageCompiler is the latest version (2.0.5) on both systems.

This is the output I get on the raspi when trying to build the sysimage with the precompile file:

```
[ Info: PackageCompiler: Executing /root/user1/precompile_instructions.jl => /tmp/jl_packagecompiler_ywfDbS/jl_kTPbhe
[ Info: PackageCompiler: Done
- PackageCompiler: compiling incremental system image
ERROR: failed process: Process(`/usr/local/julia/bin/julia --color=auto --startup-file=no --cpu-target=native -O3 --sysimage=/usr/local/julia/lib/julia/sys.so --project=/root/user1 --output-o=/tmp/jl_CGsEcw.o /tmp/jl_6SNuOj`, ProcessSignaled(9)) [0]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:440
 [3] run
   @ ./process.jl:438 [inlined]
 [4] #14
   @ ~/.julia/packages/PackageCompiler/wpsGv/ext/TerminalSpinners.jl:157 [inlined]
 [5] spin(f::PackageCompiler.var"#14#15"{Cmd}, s::PackageCompiler.TerminalSpinners.Spinner{Base.PipeEndpoint})
   @ PackageCompiler.TerminalSpinners ~/.julia/packages/PackageCompiler/wpsGv/ext/TerminalSpinners.jl:164
 [6] macro expansion
   @ ~/.julia/packages/PackageCompiler/wpsGv/ext/TerminalSpinners.jl:157 [inlined]
 [7] create_sysimg_object_file(object_file::String, packages::Vector{String}, packages_sysimg::Set{Base.PkgId}; project::String, base_sysimage::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, extra_precompiles::String)
   @ PackageCompiler ~/.julia/packages/PackageCompiler/wpsGv/src/PackageCompiler.jl:356
 [8] create_sysimage(packages::Vector{String}; sysimage_path::String, project::String, precompile_execution_file::String, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, include_transitive_dependencies::Bool, base_sysimage::Nothing, julia_init_c_file::Nothing, version::Nothing, soname::Nothing, compat_level::String, extra_precompiles::String)
   @ PackageCompiler ~/.julia/packages/PackageCompiler/wpsGv/src/PackageCompiler.jl:507
 [9] top-level scope
   @ none:1

```

The strange thing is that the error occus in the second stage where the sysimage is created and the processing/pre-compiling of the precompile file is processed correctly.... as mentioned above, when not using the precompile file, this stage works correctly.

This is the output of `versioninfo()` on the raspi:
```
Julia Version 1.6.5
Commit 9058264a69 (2021-12-19 12:30 UTC)
Platform Info:
OS: Linux (aarch64-unknown-linux-gnu)
CPU: unknown
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-11.0.1 (ORCJIT, cortex-a72)
Environment:
 JULIA_NUM_THREADS = 3
 JULIA_PATH = /usr/local/julia
 JULIA_GPG = 3673DF529D9049477F76B37566E3C7DC03D6E495
 JULIA_VERSION = 1.6.5
```

**Comment by KristofferC** [comment]
8 GB RAM should be enough, but just to be sure, do you also have a swap file that is used in case the RAM would run out?

**Comment by agcmoser** [comment]
this is the memory situation when only the background stuff is running:

```
~ $ free
              total        used        free      shared  buff/cache   available
Mem:        8003792      363412     5600644        6020     2039736     7531024
Swap:        102396       52764       49632

```

seems there is only a 100MB swap partition and approx 3.5 GB is used by other stuff. If you suggest that it is a memory issue I will try to claose all background tasks and may also try to resize the swap parition

**Comment by agcmoser** [comment]
And btw: the package I want to precompile is quite huge and has a lot of external deps. On the mac i can do the precompilation I have 16 GB of RAM. the precompilation script has approx. 2000 lines!

**Comment by KristofferC** [comment]
It might be a memory issue. That is usually what it has been with random errors like this. I would try with a big swap file and try again.

**Comment by agcmoser** [comment]
I freed some more memory on startup but I could see that that's not enough. I will resize swap to 8 GB and try again

**Comment by agcmoser** [comment]
I re-sized the swap file on my raspberry and .. voila ... PackageCompiler is working like a charm. Just getting the following warning, which hopefully can be safly ignored.
```
/usr/bin/ld: warning: /tmp/jl_5Kt05t.o(data.o): unsupported GNU_PROPERTY_TYPE (5) type: 0xc0000000
```
If anyone stumbles across this issue: On a raspi there is not swap partition. There is a swap file. The size can be changed using `sudo vi /etc/dphys-swapfile`. After a reboot swap space is bigger. I just gave a generous 16GB swap space and everything worked just fine. Thanks @KristofferC for the hint!

**Comment by KristofferC** [comment]
👍
