### ISSUE TITLE
REPL modes do not work after compilation

### ISSUE THREAD

**Issue by diegozea** [JuliaLang/PackageCompiler.jl#68]
REPL modes from `IPython` and `Rcall` don't work after the packages are compiled with the stable version of `PackageCompiler` (0.3.1). For example:
```julia
# compilation
using PackageCompiler
compile_package("RCall", force = false, reuse = false) 
```
```bash
# using the new image
~$ julia -J /home/zea/.julia/v0.6/PackageCompiler/sysimg/sys.so
```
RCall (compiled) REPL mode doesn't work, `$` should show the `R>` prompt:
![image](https://user-images.githubusercontent.com/2822757/40012342-ad64381a-57aa-11e8-8948-6805a5ea7d8b.png)

P.S.: Also, I get a lot of `WARNING: redefining constant JULIA_HOME` messages using the compiled image.

**Comment by SimonDanisch** [comment]
I wonder if that's expected, since they're fairly dynamic. @KristofferC, you should know REPL modes pretty well, any ideas?

**Comment by KristofferC** [comment]
In Pkg3, we set up the REPL as https://github.com/JuliaLang/Pkg3.jl/blob/bd3802f3738c834f44ccb2d354b2befb0cea4234/src/Pkg3.jl#L55-L66 in `__init__`. Not sure how RCall does it.

**Comment by diegozea** [comment]
I think @randy3k will have a better idea of how `RCall` does it.

**Comment by randy3k** [comment]
RCall uses a [different way](https://github.com/JuliaInterop/RCall.jl/blob/47c65bf0d89e805dbcf9da2f5add44f202e545df/src/RPrompt.jl#L213-L234) to setup the REPL, I got the idea from @Keno's [Cxx.jl](https://github.com/Keno/Cxx.jl/blob/master/src/CxxREPL/replpane.jl#L219-L240), so I assume I was correct...

**Comment by randy3k** [comment]
@diegozea how about initialize the REPL manually?

```
RCall.RPrompt.repl_init(Base.active_repl)
```

**Comment by KristofferC** [comment]
I think you need to handle the case when the REPL is not yet inited but the package gets loaded.

**Comment by tkf** [comment]
@diegozea I think I solved it in IPython.jl master.

@KristofferC It would be nice if `Base` has `afterreplinit` (or something) to wrap what Pkg.jl is doing:

```julia
"""
    afterreplinit(f)

Like `atreplinit` but triggers `f` even after REPL is initialized when
it is called.  For `LineEditREPL`, it ensures that `interface` is
initialized.
"""
function afterreplinit(f)
    if isdefined(Base, :active_repl)
        f(Base.active_repl)
    else
        atreplinit() do repl
            if isinteractive() && repl isa REPL.LineEditREPL
                isdefined(repl, :interface) || (repl.interface = REPL.setup_interface(repl))
                f(repl)
            end
        end
    end
end
```

**Comment by KristofferC** [comment]
Not a PackageCompiler bug, the package needs to be more robust in how the REPL is started like described in https://github.com/JuliaLang/PackageCompiler.jl/issues/68#issuecomment-388902941

**Comment by tkf** [comment]
Can `julia` runtime help individual packages to solve this problem? I think the way Pkg "solving" this touches too much implementation details of the `julia` runtime (including the `REPL` stdlib). I think we need an appropriate hook to cleanly solve this: https://github.com/JuliaLang/julia/pull/29896

**Comment by KristofferC** [comment]
Yes, Julia could very well facilitate this. Point here is that it isn't a PackageCompiler issue.

**Comment by tkf** [comment]
I was commenting just because I was worried that https://github.com/JuliaLang/PackageCompiler.jl/issues/68#issuecomment-388902941 would be regarded as the official correct solution.  I am glad that you acknowledge that there can be a better solution.
