### ISSUE TITLE
PackageCompiler should use multiple threads

### ISSUE THREAD

**Issue by ufechner7** [JuliaLang/PackageCompiler.jl#688]
Precompilation, but also C++ compilation by default is using multiple threads. Can this also be enabled in PackageCompiler? That would speed up compilation time a lot. :)

**Comment by ufechner7** [comment]
Is there a related Julia issue?

**Comment by KristofferC** [comment]
Parallel compilation of Julia code is worked on quite a bit (especially recently) so I think there is an issue about it. I'll close this one since there isn't anything concrete that can be done here.
