### ISSUE TITLE
nightly (1.9) tests failing

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/PackageCompiler.jl#708]
https://github.com/JuliaLang/PackageCompiler.jl/runs/7175757050?check_suite_focus=true#step:4:341
```
/home/runner/work/PackageCompiler.jl/PackageCompiler.jl/src/embedding_wrapper.c: In function ‘main’:
/home/runner/work/PackageCompiler.jl/PackageCompiler.jl/src/embedding_wrapper.c:107:5: warning: implicit declaration of function ‘jl_set_global’; did you mean ‘jl_get_global’? [-Wimplicit-function-declaration]
  107 |     jl_set_global(jl_base_module, jl_symbol("PROGRAM_FILE"), firstarg);
      |     ^~~~~~~~~~~~~
      |     jl_get_global
```

It appears `jl_set_global` was removed in https://github.com/JuliaLang/julia/pull/44753: @vtjnash is this considered a breaking API change?

**Comment by vtjnash** [comment]
The C API is not considered part of the stable guarantees, only the Julia API

**Comment by PallHaraldsson** [comment]
>The C API is not considered part of the stable guarantees, only the Julia API

That's surprising, I don't see that documented on its page only: "Julia has a C API to make this possible." So is at least part of the C API stable? Or at least all of it in minor updates, 1.x.y? And everything to call in the other direction, ccall (and its macro), i.e. that is built in (but not Cxx.jl)?

Is Julia (slowly) converging to a fully stable C API?
