### ISSUE TITLE
Function `default_sysimg_path`

### ISSUE THREAD

**Issue by lucatrv** [JuliaLang/PackageCompiler.jl#71]
@SimonDanisch function `default_sysimg_path(true)` does not work on my system, neither on Linux or Windows, Julia v0.6 or v0.7. Moreover I am not sure to understand it. Can I update it as follows?

```
function default_sysimg_path()
        joinpath(dirname(JULIA_BINDIR), "lib", "julia")
end
```

**Comment by lucatrv** [comment]
If you agree I will send a PR. Thanks

**Comment by KristofferC** [comment]
Should be fixed in https://github.com/JuliaLang/PackageCompiler.jl/pull/304
