### ISSUE TITLE
New warning, possible bug

### ISSUE THREAD

**Issue by bclyons12** [JuliaLang/PackageCompiler.jl#713]
I've been compiling an application today and have been getting a new warning:
`Warning: it is not recommended to create an app/library without a preexisting manifest`
It looks like 57102e2eeaa5856583a54e37b6a512c94275d648 is the cause. Is it correct? Should it be `if !isfile(ctx.env.manifest_file)`?

**Comment by KristofferC** [comment]
cc @simonbyrne

**Comment by bclyons12** [comment]
@simonbyrne I just tried, but I got a permissions error when making the new branch for a PR:
```
% git push --set-upstream origin bcl/fix_warning
ERROR: Permission to JuliaLang/PackageCompiler.jl.git denied to bclyons12.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by DilumAluthge** [comment]
If you click the "Fork" button in the right-hand corner of this page, GitHub will fork this repo to your own account.

Then, you can do something similar to this:

```
git remote add myfork git@github.com:bclyons12/PackageCompiler.jl.git
git fetch myfork
git push --set-upstream myfork bcl/fix_warning
```

And then you should be able to go to https://github.com/JuliaLang/PackageCompiler.jl/pulls, click on the "New Pull Request" button, and create a pull request from your fork.

**Comment by bclyons12** [comment]
Good to know. This is literally a one character change, from `isfile(ctx.env.manifest_file)` to `!isfile(ctx.env.manifest_file)`. I don't really intend to develop this package, so perhaps another developer could make this quick fix.
