### ISSUE TITLE
Check packages before compile them

### ISSUE THREAD

**Issue by diegozea** [JuliaLang/PackageCompiler.jl#74]
If you try to compile various packages at the same time or packages with a lot of dependencies, the slow compilation process starts to sometimes fail at some point (after minutes of compilation). 
It would be great if `compile_package` could be able to check the list of packages and their dependencies to see if they can be compiled (to avoid some errors, e.g. packages that cannot be precompiled).
Also, it would be great if that function could catch common problems (e.g. non-const globals).

Best regards,

**Comment by KristofferC** [comment]
This is quite difficult. The easiest way to see if things can be precompiled is pretty much to try it and see what happens. For apps, there are some checks in place now.
