### ISSUE TITLE
`--compile-all` option does not finish

### ISSUE THREAD

**Issue by fduple** [JuliaLang/PackageCompiler.jl#741]
Adding the `--compile-all` option to sysimage_build_args causes PackageCompiler.create_sysimage to get stuck for many hours;  it does not finish. 
Below is a simple demonstration; first without the option (finished in less than 2 min). then with `--compile-all` (not finished after 23 hours):
```
fduple@rek:~/temp$ julia  -q --project
julia> versioninfo()
Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × 12th Gen Intel(R) Core(TM) i5-12600KF
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, goldmont)
  Threads: 1 on 16 virtual cores
Environment:
  LD_PRELOAD = /usr/lib/x86_64-linux-gnu/libstdc++.so.6

(temp) pkg> status
Status `~/temp/Project.toml`
  [9b87118b] PackageCompiler v2.1.0

julia> using PackageCompiler

julia> create_sysimage(sysimage_path="test.so")
✔ [01m:32s] PackageCompiler: compiling incremental system image

shell> ls -la test.so
-rwxrwx--- 1 fduple fduple 170745320 Nov 19 16:50 test.so

julia> create_sysimage(sysimage_path="test_ca.so",sysimage_build_args=`--compile=all`)
⠙ [23h:01m:32s] PackageCompiler: compiling incremental system image
```

**Comment by KristofferC** [comment]
Does it finish if you don't add any packages to the sysimage? What if you only add like one small package?

**Comment by fduple** [comment]
No, it does not finish if I don't add any packages; as in the example above (except PackageCompiler).

I added DataFrames package; without the `--compile-all` option it finishes in < 2 min, with the option again still not finished after 30 min:
```(temp) pkg> status
Status `~/temp/Project.toml`
  [a93c6f00] DataFrames v1.4.3
  [9b87118b] PackageCompiler v2.1.0

julia> create_sysimage([:DataFrames]; sysimage_path="test3.so")
✔ [01m:50s] PackageCompiler: compiling incremental system image

julia> create_sysimage([:DataFrames]; sysimage_path="test4.so", sysimage_build_args=`--compile=all`)
⠋ [30m:59s] PackageCompiler: compiling incremental system image
```
I'm willing to try any other options you need.
In addition if someone can provide any working example I'll try to replicate it.

**Comment by KristofferC** [comment]
1.8.3 should include https://github.com/JuliaLang/julia/pull/47357 so I'm not sure why it wouldn't work. Maybe @JeffBezanson has some idea.

**Comment by fduple** [comment]
The bug is apparently not with PackageCompiler but Julia 1.8.3 itself; opened an issue: https://github.com/JuliaLang/julia/issues/47662

**Comment by KristofferC** [comment]
Thanks!
