### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by mpeters2** [JuliaLang/PackageCompiler.jl#744]
I've been trying to follow the "toy application" tutorial, and I get a segfault when trying to create a sysimage. 

`Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
`

`
Examples/myApp$ julia --startup-file=no -J"/Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/sys.dylib" --output-o sys.o custom_sysimage.jl

signal (11): Segmentation fault: 11
in expression starting at none:0
uv__check_before_write at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
uv_write2 at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
uv_write at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
jl_uv_write at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
unknown function (ip: 0x10ff78597)
uv_write_async at ./stream.jl:1078
uv_write at ./stream.jl:1035
unsafe_write at ./stream.jl:1118
write at ./strings/io.jl:244 [inlined]
print at ./strings/io.jl:246 [inlined]
#with_output_color#916 at ./util.jl:107
with_output_color##kw at ./util.jl:71 [inlined]
#printstyled#917 at ./util.jl:130 [inlined]
printstyled##kw at ./util.jl:130
unknown function (ip: 0x1101040e7)
ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
display_error at ./client.jl:102
unknown function (ip: 0x1100b0257)
ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
display_error at ./client.jl:106
unknown function (ip: 0x10ff000e3)
ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
jl_f__call_latest at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
#invokelatest#2 at ./essentials.jl:729 [inlined]
invokelatest at ./essentials.jl:726 [inlined]
exec_options at ./client.jl:306
_start at ./client.jl:522
unknown function (ip: 0x10d23c58b)
ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
true_main at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
jl_repl_entrypoint at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
Allocations: 2906 (Pool: 2895; Big: 11); GC: 0
`

**Comment by KristofferC** [comment]
> I've been trying to follow the "toy application" tutorial, 

Which one?

**Comment by mpeters2** [comment]
This one: https://github.com/JuliaLang/PackageCompiler.jl/blob/master/docs/src/devdocs/binaries_part_2.md

**Comment by KristofferC** [comment]
You should probably try https://julialang.github.io/PackageCompiler.jl/stable/apps.html. That is some old document that has been removed from the manual (which is hosted at https://julialang.github.io/PackageCompiler.jl/stable/index.html).
