### ISSUE TITLE
Avoid redownloading MKL_jll for each testset

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/PackageCompiler.jl#766]
Because each test starts with a clean depot state, as I think it should, they each download MKL_jll, which can make tests a lot slower (especially on my wifi which is relatively mediocre).

It'd be nice to figure out a way to ensure that MKL_jll is downloaded appropriately for apps, but avoid downloading it each time.

**Comment by DilumAluthge** [comment]
Is there a different JLL that we can use for the tests? One that is not as big?
