### ISSUE TITLE
Precompile stage doesn't support packages with the same names and different uuids

### ISSUE THREAD

**Issue by krynju** [JuliaLang/PackageCompiler.jl#767]
## Setup
In a setup like this:

1. PackageA (depends on PackageC with uuid 1234)
2. PackageB (depends on PackageC with uuid 5678)

The `loaded_modules` will look something like this:
```
julia> Base.loaded_modules
Dict{Base.PkgId, Module} with 48 entries:
  PackageC [1234]           => Package1
  PackageC [5678]           => Package1
```

## Error
This setup fails at this line, because it hits a constant redefinition error 
https://github.com/JuliaLang/PackageCompiler.jl/blob/05f6854fb9147bd0faae7b442555cddc69457f64/src/PackageCompiler.jl#L320

```
⣠ [00m:08s] PackageCompiler: compiling incremental system imageinvalid redefinition of constant Package1
Stacktrace:
 [1] top-level scope
   @ none:1
⡆ [00m:08s] PackageCompiler: compiling incremental system imageModule, e::Any)
   @ Core ./boot.jl:373
 [3] top-level scope
   @ /tmp/jl_CY4U4d:15
 [4] eval(m::Module, e::Any)
   @ Core ./boot.jl:373
 [5] top-level scope
   @ /tmp/jl_CY4U4d:10
in expression starting at /tmp/jl_CY4U4d:10
```

## Solution

I managed to get past this by skipping that part of code (effectively turning off precompilation statements, but I wasn't using them so no problem)
The image built without any issues and I could load it and have access to the both uuid versions of PackageC 

So I think the temporary solution could be to add a "disable precompile files" flag or just skip the code if no precompile files/statements were provided

Precompiling in this setup is problematic, so not sure how we could address this.
We would need to somehow have separate `PrecompileStagingArea`s for precompilation and figure out which statement belongs to which precompile group

**Comment by staticfloat** [comment]
I think this is going to require the precompile statements to emit UUID-specific lines.  E.g. we need to add a `Base.get_module(UUID(...))` and then if we load two packages with the same name, instead of emitting something like `precompile(Tuple{typeof(Foo.fooifier), Int64})` we'd instead emit something like `precompile(Tuple{typeof(Base.get_module(UUID(...)).fooifier), Int64})`.
