### ISSUE TITLE
precompilation is very slow with incremental=false

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/PackageCompiler.jl#783]
`create_fresh_base_sysimage` outputs a .ji file, which is then used to precompile the environment. Because it does not have native code, each precompile process takes a very long time to start so precompiling takes ~forever.

**Comment by IanButterworth** [comment]
See https://github.com/JuliaLang/PackageCompiler.jl/issues/778 it also appears to max-out all available threads, even for precompilation where no multithreading should be happening.

IMO it looks like all threads are needlessly spinning, I guess that could be happening even if 1 thread is given, slowing the process down.

Seems like a bug to me but @vtjnash said (correct me if this is an unfair summary) it was unreasonable to expect julia to behave better that this in that situation.

There was a thread in the #internals slack channel

**Comment by KristofferC** [comment]
Why was this not an issue in 1.8?

**Comment by JeffBezanson** [comment]
I think it was an issue on 1.8, it just got a bit worse.
