### ISSUE TITLE
Example for creating image with Plots.jl not working

### ISSUE THREAD

**Issue by ufechner7** [JuliaLang/PackageCompiler.jl#786]
Output of versioninfo:
```
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```
Installed package versions:
```
(Bug) pkg> st
Status `~/repos/Bug/Project.toml`
  [28b8d3ca] GR v0.71.6
  [9b87118b] PackageCompiler v2.1.5
  [91a5bcdd] Plots v1.38.5
```
I followed the instructions at https://julialang.github.io/PackageCompiler.jl/dev/examples/plots.html

If I now launch julia with:
```
julia -J sys_plots.so --project
```
and then try to create a plot with:
```
using Plots
p = plot(rand(2,2))
display(p)
```
I get the following text output:
```
Plot{Plots.GRBackend() n=2}
```
But no plot window is popping up.

**Comment by ufechner7** [comment]
Related: https://discourse.julialang.org/t/plots-do-not-display-unless-i-call-gui-when-using-custom-sysimage/92207

**Comment by ufechner7** [comment]
Workaround:
```
using Plots
Plots.__init__()

p = plot(rand(2,2))
display(p)
```

**Comment by ufechner7** [comment]
https://github.com/JuliaLang/PackageCompiler.jl/pull/750

**Comment by KristofferC** [comment]
The `__init__` function of Plot is surely getting run though so we need to understand what is going on. Some order dependence of modules getting loaded?

**Comment by ufechner7** [comment]
It seems that the position of PlotsDisplay in Base.Multimedia.displays might be faulty in this case (see https://github.com/JuliaPlots/Plots.jl/blob/master/src/init.jl#L36-L55).

**Comment by ianqsong** [comment]
Just post a question #787 and read this one. I was wondering if both concern that  `REPL.REPLDisplay` always gets to the topmost on the stack of `Base.Multimedia.displays` when starting a REPL.
