### ISSUE TITLE
juliac.jl: command not found

### ISSUE THREAD

**Issue by conradwt** [JuliaLang/PackageCompiler.jl#81]
Hi, I'm attempting to generate an executable file from a Julia source file.  Thus, I completed the following steps:

- From julia REPL, Pkg.add("PackageCompiler")

- From Terminal, juliac.jl -vae fib.j

```
-bash: juliac.jl: command not found
```

As a side note, it seems that the entire option set for `juliac.jl` should be added to `julia`.  I'll speak more on that in another ticket.

**Comment by NHDaly** [comment]
Note that "juliac.jl" isn't *installed*, so you won't find it in bash without specifying the full prefix.

On my Mac, I run it like this:
```bash
$ julia ~/.julia/v0.6/PackageCompiler/juliac.jl <args>
```

On other systems (like windows) it will be wherever Julia installs packages, which you can find from within Julia by running `Pkg.dir()`.

It's probably easier to use the Julia API, though, such as `build_executable()` from within Julia.

**Comment by lucatrv** [comment]
Once issue #78 is fixed you will be able to statically compile the `juliac.jl` script into a standalone executable `juliac`, for the time being you need to run `juliac.jl` through `julia` itself.
