### ISSUE TITLE
two copies of libjulia-codegen and libjulia-internal

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/PackageCompiler.jl#828]
On latest master, with the new library bundling code, I get two copies of these, one in lib/ and one in lib/julia.

**Comment by KristofferC** [comment]
Ah, I think this is due to the mismatch in how the libraries are stored between locally compiled julias (everything in `lib`) and the released binaries (only `libjulia` in `lib` and the rest in `lib/julia`).
