### ISSUE TITLE
High memory usage of compilation (windows)

### ISSUE THREAD

**Issue by korbinian90** [JuliaLang/PackageCompiler.jl#854]
I'm using the GitHub runners to [compile my package for different OS](https://github.com/korbinian90/CompileMRI.jl/blob/master/.github/workflows/compile.yml).

The free Windows GitHub runner has 8GB RAM and crashes during compilation with
```
- PackageCompiler: compiling nonincremental system image
LLVM ERROR: out of memory
```

A current solution is to increase the swap-file on the windows runners via https://github.com/al-cheb/configure-pagefile-action

(I decided to create this issue with having a solution since others might attempt the same or have better solutions)

**Comment by sjkelly** [comment]
Closing, since this is for posterity and not actionable. Thanks!
