### ISSUE TITLE
How to select the GLIBC version for create_app?

### ISSUE THREAD

**Issue by JinyanTeng** [JuliaLang/PackageCompiler.jl#946]
I have the GLIBC v2.34, but I want to compile my Julia app with a lower version of GLIBC (e.g., 2.14).
Can I choose the GLIBC version for create_app?

```
ldd --version
ldd (GNU libc) 2.34
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

```
julia> versioninfo()
Julia Version 1.10.3
Commit 0b4590a5507 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 28 × Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake-avx512)
Threads: 27 default, 0 interactive, 13 GC (on 28 virtual cores)
```

**Comment by DilumAluthge** [comment]
This is probably not something we can address in the PackageCompiler.jl package itself.

---

One thing you could try is to run a Docker container based on e.g. Centos 8. So e.g. put `FROM centos:8` in your Dockerfile. By default, Centos 8 will give you a super old GCC, but you can install a newer GCC inside the Docker container by doing e.g. `dnf -y install gcc-toolset-9-gcc gcc-toolset-9-gcc-c++`, which will give you GCC 9.

Building inside a Docker container based on Centos 8 will give you glibc 2.28, which at least is a little older than 2.34. If you want, you could try Centos 7 (which would give you 2.17).
