### ISSUE TITLE
CI fails for Julia 1.9 on 32 bit Windows

### ISSUE THREAD

**Issue by ufechner7** [JuliaLang/PackageCompiler.jl#957]
See title.

We have two options:

1. drop support for Julia 1.9 on 32 bit Windows
2. fix it

What shall we do?

I would suggest to drop the support, because it works on 1.10 and 1.10 will soon be the long-term stable Julia version.

**Comment by DilumAluthge** [comment]
We also need to see if CI passes for 32-bit Julia 1.11 on Windows (after applying the patch in #954).
