### ISSUE TITLE
AssertionError in 1.11.0-rc2 and rc3

### ISSUE THREAD

**Issue by mojaie** [JuliaLang/PackageCompiler.jl#961]
```
julia> versioninfo()
Julia Version 1.11.0-rc2
Commit 34c3a63147b (2024-07-29 06:24 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 4 × Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
```

The library build below has worked until 1.11.0-rc1, but failed on rc2 and rc3
https://github.com/mojaie/MolecularGraph.jl/blob/master/build/build.jl

Library called from Python 3.12.4

```shell
>>> from local import moleculargraphjl
>>> jl = moleculargraphjl.jl_init()
fatal: error thrown and no exception handler available.
InitError(mod=:Base, error=AssertionError(msg="isempty(loaded_precompiles)"))
__init__ at /usr/local/moleculargraphjl/lib/libmoleculargraph.dylib (unknown line)
...
```

It would be related to https://github.com/JuliaLang/julia/pull/55564 and hopefully fixed in the next release.

**Comment by DilumAluthge** [comment]
@mojaie Can you see if this error still occurs for you on Julia 1.11.0?

Because it looks like https://github.com/JuliaLang/julia/pull/55564 was backported to 1.11.0-rc4 and 1.11.0.

**Comment by mojaie** [comment]
My library build described above works well with 1.11.0 and 1.11.1.
Thank you very much!
